Implement BC compatibel BackedEnum switch
doctrine/doctrine2 pull request #10158
Opened 2022-10-19 17:14 UTC by SerethiX

2022-10-19 17:17 UTC, SerethiX commented
Fixes  #10132

2022-10-19 17:22 UTC, derrabus requested changes
Thank you, but as always: we need a test that covers your change.

2022-10-19 17:22 UTC, derrabus commented on lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php
> +                } elseif (class_exists('\BackedEnum') && is_a($data[$fieldName], '\BackedEnum')) {
The `class_exists()` feels unnecessary and also wrong, given that `BackedEnum` is actually an interface.

2022-10-26 09:33 UTC, derrabus commented
Closing due to lack of feedback and given that the patch is apparently not correct. Feel free to open a new PR if you want to pick up the work.

2022-10-26 09:33 UTC, closed without merging