Migrate more documentation towards attributes
doctrine/doctrine2 pull request #10157
Opened 2022-10-19 14:05 UTC by greg0ire

The previous rework missed some details / left the documentation in an inconsistent state. Searching for "annotation" case insensitively allows to find discrepancies and forgotten things.

2022-10-19 19:41 UTC, greg0ire commented
I also added another commit to address [@stof 's comment](https://github.com/doctrine/orm/pull/10126#discussion_r997892384)

2022-10-21 08:09 UTC, stof commented on docs/en/cookbook/strategy-cookbook-introduction.rst
> +         * This is a doctrine field, so make sure that you use an @[Column] attribute or setup your
should not be a `@` here

2022-10-21 08:09 UTC, stof commented on docs/en/cookbook/validation-of-entities.rst
> +First Attributes:
the doc below shows other formats. So maybe it should keep annotations as well.

And for Yaml, there is a sentence saying `this will happen before Beta 1 though` which looks totally wrong in the doc (and it does not say beta 1 of which version)

2022-10-21 08:09 UTC, stof commented on docs/en/reference/advanced-configuration.rst
> +The attribute driver can be configured with a factory method on
there is no factory method (and before, it was not on the Configuration class)

2022-10-21 08:09 UTC, stof commented on docs/en/reference/association-mapping.rst
> +    .. code-block:: annotation
I would put attribute before annotation, as attribute is the default in the docs

2022-10-21 08:09 UTC, stof commented on docs/en/reference/basic-mapping.rst
>     same as leaving off the @GeneratedValue entirely.
`@GeneratedValue` should be replaced too, meaning the attribute instead

2022-10-21 08:09 UTC, stof commented on docs/en/tutorials/getting-started.rst
>      // or if you prefer YAML or XML
should we have a `or if you prefer annotation` ?

2022-10-21 08:35 UTC, derrabus requested changes

2022-10-21 08:35 UTC, derrabus commented on docs/en/cookbook/advanced-field-value-conversion-using-custom-mapping-types.rst
> +            private float$longitude,
```suggestion
            private float $longitude,
```

2022-10-21 08:35 UTC, derrabus commented on docs/en/cookbook/strategy-cookbook-introduction.rst
> +         * This is a doctrine field, so make sure that you use an @[Column] attribute or setup your
```suggestion
         * This is a doctrine field, so make sure that you use an #[Column] attribute or setup your
```

2022-10-21 08:35 UTC, derrabus commented on docs/en/cookbook/advanced-field-value-conversion-using-custom-mapping-types.rst
> +        #[Column()]
```suggestion
        #[Column]
```

2022-10-21 08:35 UTC, derrabus commented on docs/en/reference/events.rst
> +            public function prePersistHandler(User $user, LifecycleEventArgs $event) { // ... }
Shall we make the return type explicit to indicate that we don't expect the listener to return anything?

```suggestion
            public function prePersistHandler(User $user, LifecycleEventArgs $event): void { // ... }
```

2022-10-21 11:03 UTC, derrabus approved these changes

2022-10-21 19:25 UTC, merged