Added MultiManagerProvider
doctrine/doctrine2 pull request #10273
Opened 2022-12-06 19:42 UTC by jordan-schnur

A SingleManagerProvider was not enough for a more complex application using more than one entity manager in the cli.

2022-12-19 11:38 UTC, derrabus commented
Please add tests.

2022-12-28 15:36 UTC, derrabus commented on lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/MultiManagerProvider.php
> +    /** @var EntityManagerInterface[] */
To make Psalm happy:

```suggestion
    /** @var array<string, EntityManagerInterface> */
```

2022-12-28 15:36 UTC, derrabus commented on lib/Doctrine/ORM/Tools/Console/EntityManagerProvider/MultiManagerProvider.php
> +    /** @var EntityManagerInterface[] */
To make Psalm happy:

```suggestion
    /** @var array<string, EntityManagerInterface> */
```

2022-12-28 15:39 UTC, derrabus requested changes
Thank you for the test. However, that test does not really tell me that an instance of your provider can be used in a console application. Since that is the main purpose of such a provider, we should have a test that covers this scenario.

2022-12-28 15:39 UTC, derrabus commented on tests/Doctrine/Tests/ORM/Tools/Console/EntityManagerProvider/MultiManagerProviderTest.php
> +        parent::setUp(); // TODO: Change the autogenerated stub
TODO: Remove the comment.

2023-01-27 21:55 UTC, jordan-schnur commented
> Thank you for the test. However, that test does not really tell me that an instance of your provider can be used in a console application. Since that is the main purpose of such a provider, we should have a test that covers this scenario.

Sorry for taking awhile. The test are updated.

2023-01-27 22:29 UTC, derrabus approved these changes

2023-01-27 22:30 UTC, derrabus requested changes
Your test seems to be failing in our CI. Can you please check?

2023-05-26 18:58 UTC, jordan-schnur commented
> Your test seems to be failing in our CI. Can you please check?

Finally back, sorry for taking so long. Can we rerun the CI pipeline so I can get the logs back? Everything passes locally so I am confused as to where the error is occurring.

2024-11-15 03:11 UTC, closed without merging