Migrate classes with the fewest changes
doctrine/doctrine2 pull request #10378
Opened 2023-01-07 13:31 UTC by greg0ire

2023-01-09 03:44 UTC, derrabus requested changes, later dismissed

2023-01-09 03:44 UTC, derrabus commented on lib/Doctrine/ORM/Mapping/ReflectionEnumProperty.php
> +                $value = array_map(fn ($item): BackedEnum => $this->initializeEnumValue($object, $item), $value);
```suggestion
                $value = array_map(fn (int|string|BackedEnum $item): BackedEnum => $this->initializeEnumValue($object, $item), $value);
```

2023-01-09 03:44 UTC, derrabus commented on lib/Doctrine/ORM/Tools/Pagination/WhereInWalker.php
> +            array_map(static fn ($id): mixed => $connection->convertToDatabaseValue($id, $type), $identifiers),
```suggestion
            array_map(static fn (mixed $id): mixed => $connection->convertToDatabaseValue($id, $type), $identifiers),
```

2023-01-09 03:44 UTC, derrabus commented on lib/Doctrine/ORM/Mapping/DefaultQuoteStrategy.php
> +                static fn ($joinColumn) => isset($joinColumn['quoted'])
```suggestion
                static fn (array $joinColumn) => isset($joinColumn['quoted'])
```

2023-01-10 23:32 UTC, SenseException approved these changes

2023-01-11 08:33 UTC, merged