Migrate exceptions to PHP 8 syntax
doctrine/doctrine2 pull request #10380
Opened 2023-01-08 14:12 UTC by greg0ire

2023-01-09 03:28 UTC, derrabus requested changes

2023-01-09 03:28 UTC, derrabus commented on lib/Doctrine/ORM/Mapping/MappingException.php
> +        $cascades = implode(', ', array_map(static fn ($e) => "'" . $e . "'", $cascades));
```suggestion
        $cascades = implode(', ', array_map(static fn (string $e) => "'" . $e . "'", $cascades));
```

2023-01-09 03:28 UTC, derrabus commented on lib/Doctrine/ORM/Mapping/MappingException.php
> +    public static function invalidIndexConfiguration($className, $indexName): self
Types?

2023-01-09 03:28 UTC, derrabus commented on lib/Doctrine/ORM/Mapping/MappingException.php
> +    public static function invalidUniqueConstraintConfiguration($className, $indexName): self
Types?

2023-01-09 23:45 UTC, SenseException requested changes, later dismissed

2023-01-09 23:45 UTC, SenseException commented on lib/Doctrine/ORM/Mapping/MappingException.php
> +    public static function classIsNotAValidEntityOrMappedSuperClass($className): self
```suggestion
    public static function classIsNotAValidEntityOrMappedSuperClass(string $className): self
```

2023-01-09 23:45 UTC, SenseException commented on lib/Doctrine/ORM/Mapping/MappingException.php
> +    public static function fileMappingDriversRequireConfiguredDirectoryPath($path = null): self
```suggestion
    public static function fileMappingDriversRequireConfiguredDirectoryPath(string|null $path = null): self
```

2023-01-09 23:45 UTC, SenseException commented on lib/Doctrine/ORM/Mapping/MappingException.php
> +        $cascades = implode(', ', array_map(static fn (string $e) => "'" . $e . "'", $cascades));
```suggestion
        $cascades = implode(', ', array_map(static fn (string $e): string => "'" . $e . "'", $cascades));
```
... I guess

2023-01-10 10:01 UTC, derrabus approved these changes

2023-01-10 10:04 UTC, merged