Catch missing inheritance declarations early on
doctrine/doctrine2 pull request #10431
Opened 2023-01-19 09:02 UTC by mpdude

When my understanding is correct, inheritance has to be declared as soon as one entity class extends (directly or through middle classes) another one.

Catching missing inheritance declarations early on is important to avoid weird errors further down the road, giving users a clear indication of the root cause.

The documentation is updated accordingly at #10429.

2023-01-23 12:04 UTC, derrabus commented
As always, we don't introduce deprecations in bugfix releases. Please target 2.15.

2023-01-23 12:58 UTC, mpdude commented
Rebased onto 2.15.x, and tied a knot in my handkerchief.

2023-01-24 12:15 UTC, derrabus requested changes

2023-01-24 12:15 UTC, derrabus commented on tests/Doctrine/Tests/Models/DDC5934/DDC5934BaseContract.php
> +/** @MappedSuperclass() */
```suggestion
/** @MappedSuperclass */
```

2023-01-24 12:15 UTC, derrabus commented on UPGRADE.md
> +be declared by adding the appropriate configuration for the root entity.
We usually add new messages at the top.

2023-01-24 20:51 UTC, mpdude commented
Feedback addressed

2023-01-24 21:47 UTC, derrabus approved these changes

2023-01-24 21:47 UTC, merged

2023-01-24 21:47 UTC, derrabus commented
Thanks!

2023-01-24 22:05 UTC, mpdude commented
💪🏻

Let’s hope it will not cause too much confusion and problems for users in 2.15.

Shall I create a dedicated PR to make the switch in 3.0? Requires changes to be merged up before, though.