Use Rector to migrate to the object API of FieldMapping
doctrine/doctrine2 pull request #10617
Opened 2023-04-11 07:47 UTC by greg0ire

This makes the array access implementation of FieldMapping useful only to consumers, it is no longer useful internally, except for a few spots where we use union types that include association mapping arrays, and should be deprecated as of Doctrine 3.1.0

2023-04-11 21:48 UTC, SenseException requested changes

2023-04-11 21:48 UTC, SenseException commented on tests/Doctrine/Tests/ORM/Mapping/MappingDriverTestCase.php
> +        self::assertNotNull($class->fieldMappings['name']->type);
Do we need those at this point? It's not an array anymore and if `type` isn't initialized, we would get a "must not be accessed before initialization" (but afaik the props are initialized by default). Nevertheless, the actual value is checked in the next lines. Same with the other assertNotNull methods below.

2023-04-13 21:54 UTC, derrabus approved these changes

2023-04-13 22:03 UTC, SenseException approved these changes

2023-04-14 05:40 UTC, merged