Reject ID collisions in identity map unconditionally
doctrine/doctrine2 pull request #10968
Opened 2023-10-07 10:12 UTC by greg0ire

2023-10-07 10:12 UTC, greg0ire commented
Cc @mpdude :slightly_smiling_face:

2023-10-07 15:55 UTC, derrabus requested changes

2023-10-07 15:55 UTC, derrabus commented on lib/Doctrine/ORM/Configuration.php
>      public function setRejectIdCollisionInIdentityMap(bool $flag): void
We should throw if `$flag === false`.

2023-10-07 18:56 UTC, greg0ire commented on lib/Doctrine/ORM/Configuration.php
>      public function setRejectIdCollisionInIdentityMap(bool $flag): void
done

2023-10-07 19:11 UTC, derrabus approved these changes

2023-10-07 19:39 UTC, merged

2023-10-09 07:09 UTC, mpdude commented
Thank you :+1: