Prepare common severance
doctrine/doctrine2 pull request #10999
Opened 2023-10-11 17:49 UTC by greg0ire

2023-10-11 20:36 UTC, SenseException approved these changes, later dismissed

2023-10-11 20:36 UTC, SenseException commented on lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
> + * @deprecated The DQL command is deprecated and will be removed in Doctrine ORM 3.0.
```suggestion
 * @deprecated The DQL command is deprecated and will be removed without replacement in Doctrine ORM 3.0.
```

for the case that someone reads through the code and ignored UPGRADE.md

2023-10-11 20:36 UTC, SenseException commented on lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php
> +            'The "%s" command is deprecated and will be removed in Doctrine ORM 3.0.',
```suggestion
            'The "%s" command is deprecated and will be removed without replacement in Doctrine ORM 3.0.',
```

2023-10-11 22:14 UTC, SenseException submitted a review, later dismissed

2023-10-12 07:47 UTC, stof requested changes

2023-10-12 07:47 UTC, stof commented on UPGRADE.md
> +## Undeprecate `Doctrin\ORM\Proxy\Autoloader`
```suggestion
## Undeprecate `Doctrine\ORM\Proxy\Autoloader`
```

2023-10-13 08:58 UTC, stof approved these changes

2023-10-13 09:25 UTC, merged