Add TokenType class
doctrine/doctrine2 pull request #11228
Opened 2024-02-06 16:31 UTC by connorhu

The idea of a `TokenType` class was discussed to make it easier to support ORM2 and ORM3 together.
https://github.com/beberlei/DoctrineExtensions/pull/421#discussion_r1478274153

2024-02-06 16:36 UTC, derrabus commented on src/Query/TokenType.php
> +class TokenType
```suggestion
final class TokenType
```

2024-02-06 16:40 UTC, derrabus commented
I suggest we have the old `Lexer` constants point to the new `TokenType` ones and flag the `Lexer` constants as `@deprecated`.

2024-02-06 16:50 UTC, connorhu commented
@derrabus Should I deprecate each constant or is one per section enough? I would mark all of them, but I don't know if you have any policy for that.

2024-02-06 16:52 UTC, derrabus commented
If we want static analyzers to pick up the deprecation, we need to flag each constant as deprecated.

2024-02-06 17:05 UTC, greg0ire commented
I think you should search and replace occurrences of `Lexer::T_` throughout the project (including in docs).

2024-02-06 18:46 UTC, greg0ire submitted a review, later dismissed

2024-02-06 18:56 UTC, greg0ire commented
You will need to update this as well: https://github.com/doctrine/orm/blob/40fbbf4429b0d66517244051237a2bd0616a7a13/psalm-baseline.xml#L2047-L2050

Please take a look at [this guide](https://www.doctrine-project.org/contribute/#dealing-with-checks-and-tools) for more on how to try things locally.

2024-02-06 19:28 UTC, greg0ire reviewed
Ah sorry I forgot: please add something in UPGRADE.md regarding the new deprecation.

2024-02-07 07:21 UTC, connorhu commented
@greg0ire I made the change you asked for.

2024-02-07 07:23 UTC, greg0ire submitted a review, later dismissed

2024-02-07 09:05 UTC, derrabus requested changes

2024-02-07 09:05 UTC, derrabus commented on docs/en/reference/dql-doctrine-query-language.rst
> +            $parser->match(TokenType::T_CLOSE_PARENTHESIS);
Please fix the import in line 815.

2024-02-07 09:05 UTC, derrabus commented on src/Query/Lexer.php
> +    public const T_NONE = 1;
```suggestion
    /** @deprecated use {@see TokenType::T_NONE} */
    public const T_NONE = TokenType::T_NONE;
```

2024-02-07 11:54 UTC, connorhu commented
@derrabus I did this deprecation notation form based on the phpdoc in the ORMException file, which means it is in "wrong" format too. Should I fix it in a separate PR that file to use `@see`?

https://github.com/doctrine/orm/blob/40fbbf4429b0d66517244051237a2bd0616a7a13/src/ORMException.php#L18

2024-02-07 12:04 UTC, derrabus commented on src/Query/Lexer.php
> +    /** @deprecated use {@see TokenType::T_ALIASED_NAME} */
```suggestion
    /** @deprecated No Replacement planned. */
```

2024-02-07 12:30 UTC, derrabus approved these changes

2024-02-07 12:31 UTC, merged

2024-02-07 12:56 UTC, connorhu commented
Thank you for your help in the creation of the PR and thank you for merging it.

2024-02-07 13:32 UTC, derrabus commented
We missed a couple of references: #11234

2024-02-07 14:05 UTC, connorhu commented
It didn't occur to me to run phpstan with `phpstan-deprecation-rules` rules. That would have caught these mistakes.

2024-02-07 14:39 UTC, derrabus commented
We have Psalm for that, but we apparently allow deprecated constants to be used inside the Lexer class. 🙈

2024-03-01 09:17 UTC, stof commented on src/Query/TokenType.php
> +    /** @deprecated No Replacement planned. */
why adding a deprecated one in TokenType ?

2024-03-01 09:35 UTC, derrabus commented on src/Query/TokenType.php
> +    /** @deprecated No Replacement planned. */
Consistency, mainly. We've moved all token constants over to the new class.