Address issues caused by possibly falsy strings
doctrine/doctrine2 pull request #11271
Opened 2024-02-18 11:09 UTC by greg0ire

2024-02-18 16:13 UTC, derrabus requested changes
While I like that we're being more string about `null` and empty strings, I fear that we will silently break apps. A lot of logic that you're touching here are fallbacks for empty strings which will need extra handling now.

2024-02-18 16:13 UTC, derrabus commented on src/AbstractQuery.php
> +        if ($parameters !== null && count($parameters) !== 0) {
Previously, we've set even an empty `ArrayCollection`. This looks like a BC break to me.

```suggestion
        if ($parameters !== null && $parameters !== []) {
```

2024-02-18 16:13 UTC, derrabus commented on src/Cache/DefaultCacheFactory.php
> +                    'region' => $regionName ?? Cache::DEFAULT_QUERY_REGION_NAME,
Passing an empty string would get us the default region previously. I would bet that someone relies on that. 🙈

2024-02-18 16:20 UTC, greg0ire commented
> While I like that we're being more string about null and empty strings, I fear that we will silently break apps. A lot of logic that you're touching here are fallbacks for empty strings which will need extra handling now.

I think I might indeed break some apps with this. If I do, hopefully this will mean we become more explicit about it (as in, more tests are added).

There are not too many people using 3.1.x, so maybe this is a good time to do such things?

2024-02-18 22:08 UTC, derrabus commented
No, it's too late for this kind of breaking changes. Especially without prior depreciation.

2024-02-18 22:20 UTC, greg0ire commented
Oh but we would revert as soon as such breaking changes are reported. I didn't mean to say we voluntarily make breaking changes, I meant to say that most of this stuff is probably not going to break applications, and if there is, we can revert / make the condition more precise to fix the regression.

2024-02-18 22:41 UTC, greg0ire commented on src/Persisters/Entity/BasicEntityPersister.php
> +        $hydrator = $this->em->newHydrator($this->currentPersisterContext->selectJoinSql !== '' ? Query::HYDRATE_OBJECT : Query::HYDRATE_SIMPLEOBJECT);
I will revert this change and the ones related to `selectJoinSql` below since they are inconsistent.

2024-02-18 22:44 UTC, greg0ire commented on src/Persisters/Entity/BasicEntityPersister.php
> +        $hydrator = $this->em->newHydrator($this->currentPersisterContext->selectJoinSql !== '' ? Query::HYDRATE_OBJECT : Query::HYDRATE_SIMPLEOBJECT);
The rest of the changes seem innocuous to me :thinking:

2024-02-19 08:30 UTC, greg0ire commented
@derrabus I will split this so it becomes more palatable, and we can discuss what's risky and what isn't.

2024-02-19 08:30 UTC, closed without merging

2024-02-19 09:08 UTC, derrabus commented
Sounds good.