Fix #11278 QueryBuilder::setParameter and ArrayParameterType
doctrine/doctrine2 pull request #11279
Opened 2024-02-20 08:07 UTC by hanishsingla

2024-02-20 08:40 UTC, greg0ire commented
Should the same thing be done for `ParameterType` as well? It has also become an enum.

2024-02-20 08:56 UTC, derrabus requested changes
> Should the same thing be done for `ParameterType` as well? It has also become an enum.

Yes.

And maybe we should add tests that would've discovered this problem. 🙈

2024-02-20 08:56 UTC, derrabus commented on src/QueryBuilder.php
> +     * @param ArrayParameterType|string|int|null $type ParameterType::* or \Doctrine\DBAL\Types\Type::* constant or \Doctrine\DBAL\ArrayParameterType enum
```suggestion
     * @param ParameterType|ArrayParameterType|string|int|null $type ParameterType::*, ArrayParameterType::* or \Doctrine\DBAL\Types\Type::* constant
```

2024-02-20 08:56 UTC, derrabus commented on src/QueryBuilder.php
> +    public function setParameter(string|int $key, mixed $value, ArrayParameterType|string|int|null $type = null): static
```suggestion
    public function setParameter(string|int $key, mixed $value, ParameterType|ArrayParameterType|string|int|null $type = null): static
```

2024-02-20 11:12 UTC, hanishsingla commented
@derrabus This is my first PR to doctrine, so need some guidance. Should I create a new PR with latest changes as per your suggestions or there are other steps involved? Thanks

2024-02-20 11:14 UTC, derrabus commented
No need fir a new PR, just amend this one.

2024-02-21 23:08 UTC, derrabus commented
Closing in favor of #11287.

2024-02-21 23:08 UTC, closed without merging