Update Docs to show QueryBuilder::setParameters with array instead of ArrayCollection
doctrine/doctrine2 pull request #11295
Opened 2024-02-22 23:19 UTC by pableu

See https://github.com/doctrine/orm/pull/11292#issuecomment-1960135295.

2024-02-22 23:20 UTC, pableu commented on docs/en/reference/query-builder.rst
> +        '2' => 'value for ?2',
I don't know, do you think the array-keys should be strings (`'1'`, `'2'`) or ints ( `1`, `2`)?

2024-02-23 06:52 UTC, greg0ire commented on docs/en/reference/query-builder.rst
> +        '2' => 'value for ?2',
PHP will convert numeric keys to ints when used as array keys: https://3v4l.org/dajmE

So I think you might as well use integers directly.

2024-02-23 12:03 UTC, pableu commented on docs/en/reference/query-builder.rst
> +        '2' => 'value for ?2',
:+1:

2024-02-23 12:35 UTC, greg0ire commented
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

How to do that?

1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already push. Don't forget the `--force` option otherwise git will try to merge both things together.

2024-02-23 22:45 UTC, pableu commented
Squashed.

2024-02-23 23:02 UTC, greg0ire approved these changes

2024-02-24 00:29 UTC, SenseException approved these changes

2024-03-03 15:06 UTC, derrabus requested changes
With this change, we would promote the usage of a deprecated API. I don't think that this is what we want.

2024-03-03 21:02 UTC, greg0ire commented
Indeed, see the original discussion

2024-03-03 21:02 UTC, closed without merging