Inherits index from MappedSuperclass
doctrine/doctrine2 pull request #11410
Opened 2024-04-08 15:19 UTC by alexndlm

2024-10-15 06:47 UTC, alexndlm commented
@greg0ire could you check?

2024-10-15 06:52 UTC, greg0ire commented
Please improve your commit message according to [the contributing guide](https://www.doctrine-project.org/contribute/index.html#crafting-meaningful-commit-messages). Right now I can't even tell if this is going to be a bugfix or a feature just from a title.

2024-10-15 07:39 UTC, derrabus commented
Also, a PR delivering a feature deserves a proper description, including what the feature does and your motivation behind it.

2024-10-15 10:00 UTC, alexndlm commented
Description updated.

2024-10-17 15:56 UTC, greg0ire commented on tests/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
> +        $userMetadata = $cmf->getMetadataFor(Cat::class);
Why the name `userMetadata`?

2024-10-17 15:57 UTC, greg0ire requested changes
In the issue you mention, Ocramius says `@Table is not valid on a mappedsuperclass`. So… this is not OK I'm afraid.

2024-10-17 16:09 UTC, alexndlm commented on tests/Tests/ORM/Mapping/ClassMetadataFactoryTest.php
> +        $userMetadata = $cmf->getMetadataFor(Cat::class);
Copy paste. Fixed.

2024-10-17 16:16 UTC, alexndlm commented
> In the issue you mention, Ocramius says `@Table is not valid on a mappedsuperclass`. So… this is not OK I'm afraid.

But it works without any warnings. Why is it not valid to define a common index in a mappedsuperclass?

2024-10-17 16:25 UTC, derrabus commented
Well, the good news is that we don't deliver new features for 2.x anymore and on 3.x with attributes, indexes are not bound to tables anymore.

2024-10-17 18:04 UTC, greg0ire commented
Ah maybe it's no longer invalid then. Regardless, let's close as per @derrabus 's comment.

2024-10-17 18:04 UTC, closed without merging