DQL custom functions: document TypedExpression
doctrine/doctrine2 pull request #11550
Opened 2024-07-11 12:41 UTC by janedbal

Partially related to https://github.com/doctrine/orm/issues/11537

2024-07-25 20:55 UTC, SenseException requested changes

2024-07-25 20:55 UTC, SenseException commented on docs/en/cookbook/dql-user-defined-functions.rst
> +----------
```suggestion
Typed functions
---------------
```

2024-07-25 20:55 UTC, SenseException commented on docs/en/cookbook/dql-user-defined-functions.rst
> +If you want to be sure the type is always the same, your custom function can
```suggestion
If you want to be sure that the type is always the same, then your custom function needs to 
```

2024-07-25 20:55 UTC, SenseException commented on docs/en/cookbook/dql-user-defined-functions.rst
> +through ``convertToPhpValue`` method of the ``Type`` returned from ``getReturnType``.
```suggestion
through the ``Doctrine\DBAL\Types\Type::convertToPhpValue()`` method returned in ``getReturnType``.
```

2024-08-02 10:25 UTC, janedbal commented on docs/en/cookbook/dql-user-defined-functions.rst
> +through ``convertToPhpValue`` method of the ``Type`` returned from ``getReturnType``.
This suggestion feels more weird to me. No method is returned (obviously), Type is returned.

2024-08-02 21:42 UTC, SenseException commented on docs/en/cookbook/dql-user-defined-functions.rst
> +through ``convertToPhpValue`` method of the ``Type`` returned from ``getReturnType``.
I didn't expect that someone could read that a "method" is returned.

```suggestion
through ``Doctrine\DBAL\Types\Type::convertToPhpValue()`` of the ``Type`` returned in ``getReturnType()``.
```

2024-08-05 22:35 UTC, SenseException reviewed
:+1: Please [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing) your 4 commits into 1.

2024-08-06 07:14 UTC, janedbal commented
No problem. Just out of curiosity, why do you force contributors to squash it manually when you can do it with a single button?

![image](https://github.com/user-attachments/assets/d1a570ca-b572-4931-bfbb-e581cf28622e)

2024-08-06 15:45 UTC, greg0ire commented
For me, there are 2 reasons:
- Pressing that button forces us to come up with a commit message summarizing all the commits. Crafting that commit message should IMO be your job, since it's your changes.
- The commit hash stays the same before and after merging, when no squashing is involved. That can be handy when trying to figure out what branch contains a particular commit or whatnot.

2024-08-06 22:20 UTC, SenseException approved these changes

2024-08-09 20:50 UTC, merged

2024-08-09 20:50 UTC, greg0ire commented
Thanks @janedbal !