onFlush and postFlush Entity Listeners
doctrine/doctrine2 pull request #5822
Opened 2016-05-13 02:01 UTC by alexgurrola

Simply check if an onFlush or postFlush entity listener is subscribed
for the current class in the entity manager during dispatch.

2016-05-13 02:02 UTC, Ocramius commented
Seems like a follow-up of #5582 ?

2016-05-13 02:04 UTC, Ocramius commented on lib/Doctrine/ORM/UnitOfWork.php
> +        foreach ($this->entityChangeSets as $oid => $entityChangeSet) {
The subscribed listeners can be fetched once the class name is known. No need to fetch a listener for each single entity.

2016-05-13 02:04 UTC, alexgurrola commented
@Ocramius Correct, with the added postFlush and former commits wrapped together.

2017-02-22 08:16 UTC, mwansinck commented
Any progress on this?

2017-02-24 23:49 UTC, alexgurrola commented
@mwansinck The logic worked, but was not optimized.  I could attempt to golf it a bit more this weekend and see if @Ocramius approves of those changes.

2017-02-27 08:18 UTC, mwansinck commented
@alexgurrola Thanks for your response, I hope your pull request will be accepted. If I can help you in any way, let me know,

2017-03-15 11:23 UTC, mwansinck commented
@alexgurrola Any update on this?

2017-03-16 02:26 UTC, alexgurrola commented
@mwansinck Thanks much.  I had a little extra time, so I fixed the merge conflicts and added a simple map for the listener subscriptions, to reduce the amount of fetches.  I hope that helps it get approved.  What say you, @Ocramius?

2017-03-16 12:38 UTC, lcobucci requested changes

2017-03-16 12:38 UTC, lcobucci commented on lib/Doctrine/ORM/UnitOfWork.php
> +                    if (is_object($hash) && method_exists($hash, '__toString')) $hash = $hash->__toString();
```php
$hash = (string) $hash;
```

Is a bit cleaner than this `if`, don't you think?

2017-03-16 12:38 UTC, lcobucci commented on lib/Doctrine/ORM/UnitOfWork.php
> +        $subscribedSystems = [];
This whole part can be extracted to a method instead of duplicated with minor changes.

2017-03-16 12:38 UTC, lcobucci commented on lib/Doctrine/ORM/UnitOfWork.php
> +        foreach ($this->entityChangeSets as $oid => $entityChangeSet) {
Maybe refactoring (extract method, mostly) this to became more readable?

2017-03-16 12:38 UTC, lcobucci commented on lib/Doctrine/ORM/UnitOfWork.php
> +        foreach ($this->entityChangeSets as $oid => $entityChangeSet) {
@Ocramius this nested `foreach` would have a (small) performance impact, should we mind that?

2017-03-16 12:39 UTC, lcobucci commented
@alexgurrola could you also `rebase` the branch instead of `merging`? And we do need tests 😄

2017-03-16 22:59 UTC, closed without merging