Entity listeners are now processed by exporters
doctrine/doctrine2 pull request #5864
Opened 2016-06-08 16:22 UTC by tPl0ch

The current implementation of the exporters are not taking the entity
listeners into account. I have added test cases for most of the edge
cases I could think of and implemented the Exporter handling.

Again there are some test cases failing but I cannot see how they
are related.

2016-06-08 16:28 UTC, grimskin commented
+1

2016-06-08 16:29 UTC, akucherenko commented
+1

2016-06-08 16:34 UTC, iaroshukandrii commented
+1

2016-06-08 16:35 UTC, Ocramius commented
+1-ing issues serve no purpose besides making me want to archive email notifications: don't do it, please.

2016-11-26 06:01 UTC, Ocramius requested changes

2016-11-26 06:01 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/PhpExporter.php
> +        if (0 !== count($metadata->entityListeners)) {
To be moved to a private method

2016-11-26 06:01 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
> +        if (0 !== count($metadata->entityListeners)) {
To be moved to one or multiple private methods

2016-11-26 06:01 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/YamlExporter.php
> +        if (0 !== count($metadata->entityListeners)) {
To be moved to one or multiple private methods

2016-11-26 06:01 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/YamlExporter.php
> +                    if (isset($entityListener['method'])) {
Are there scenarios where `'method'` is not defined?

2016-11-26 06:01 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/PhpExporter.php
> +                    $lines[] = "\$metadata->addEntityListener('$event', '$class', '$method');";
Please don't interpolate. Use `sprintf()` instead. Also, please do use `var_export()` on values that end up being in PHP code.

2016-11-26 06:01 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/Export/annotation/Doctrine.Tests.ORM.Tools.Export.User.php
> + *     "Doctrine\Tests\ORM\Tools\Export\UserListener",
Can we use the `::class` syntax here?

2017-07-31 05:07 UTC, tPl0ch commented
@Ocramius I have been browsing my open PRs (of which I have forgotten half of them). I would actually finish this if you think it makes sense and would be worth it.

2017-07-31 15:17 UTC, Ocramius commented
@tPl0ch this is more a question for @guilhermeblanco, who just rewrote most of the metadata stuff.

@guilhermeblanco is this kind of exporter API still existing in 3.x?

2017-07-31 20:35 UTC, guilhermeblanco commented
@Ocramius it does, since this is part of convert mapping support (transition from yml to xml for example)

2017-08-01 10:17 UTC, tPl0ch commented
@guilhermeblanco The sheer amount of conflicts drove me creating a new PR for this hotfix: https://github.com/doctrine/doctrine2/pull/6593

I'll close this one here.

2017-08-01 10:17 UTC, closed without merging