Improved Output in Validation with no Entities
doctrine/doctrine2 pull request #5872
Opened 2016-06-13 10:08 UTC by rogerwalt

Instead of "OK - The mapping files are correct" it now says "FAIL - No
entities defined!".

Maybe someone can help me write a correct test for the
ValidateSchemaCommand, I wasn't able to provide that, mostly because
there is no test for this command yet.

2016-06-13 10:14 UTC, rogerwalt commented on lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
> +        } elseif (count($errors) > 0) {
Now by looking at this I think $error won't be defined here. I should really write a test for the `ValidateSchemaCommand`.

2016-11-26 05:56 UTC, Ocramius requested changes

2016-11-26 05:56 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/SchemaValidator.php
> +            return false;
1. return type is inconsistent with signature
2. an empty set of mappings is perfectly valid here

2016-11-26 05:56 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
> +        } elseif (count($errors) > 0) {
I suggest counting `$em->getMetadataFactory()->getAllMetadata()` and dealing with the case where 0 mappings are found directly in the CLI command. The validator context is much more specific, and an empty set of metadata is indeed valid.

2016-11-26 05:56 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/SchemaValidatorTest.php
> +        $this->assertFalse($result);
Should simply be `self::assertEmpty($result)`

2021-02-23 08:19 UTC, closed without merging