#5934 - add `fetch` option to `AssociationOverride` in order to override fetch strategy for subclasses of entities
doctrine/doctrine2 pull request #5938
Opened 2016-07-16 10:12 UTC by Ma27

adds the `fetch` option to the `association-override` sequence.

see #5934

2016-07-17 23:24 UTC, patrick-mcdougle commented on tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC5934.DDC5934BaseContract.dcm.xml
> +        <many-to-many target-entity="DDC5934Member" inversed-by="contract" fetch="LAZY" field="members" />
Is there a typo here? Should this be contracts?

2016-07-18 10:03 UTC, Ma27 commented on tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC5934.DDC5934BaseContract.dcm.xml
> +        <many-to-many target-entity="DDC5934Member" inversed-by="contract" fetch="LAZY" field="members" />
possibly. Some tests are still failing. Try to fix it somehow in the next days...

2016-08-16 22:24 UTC, Ma27 commented on tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.DDC5934.DDC5934BaseContract.dcm.xml
> +        <many-to-many target-entity="DDC5934Member" inversed-by="contract" fetch="LAZY" field="members" />
no, not a type ;)

2016-08-16 22:24 UTC, Ma27 commented
ok, fixed the tests now...

2016-08-17 17:53 UTC, patrick-mcdougle commented
Looks good to me! LGTM!

2016-09-11 03:05 UTC, patrick-mcdougle commented
Sad that this didn't make the release. Anything else to do for this one @Ocramius?

2016-09-11 03:08 UTC, Ocramius commented
Patch releases don't get new features, folks!

On 11 Sep 2016 5:05 a.m., "Patrick McDougle" <notifications@github.com>
wrote:

Sad that this didn't make the release. Anything else to do for this one
@Ocramius <https://github.com/Ocramius>?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/doctrine/doctrine2/pull/5938#issuecomment-246158899>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AAJakJo4yXGsBgmhgwM87OAaoksnct0bks5qo2_6gaJpZM4JN-7o>
.

2016-09-11 06:09 UTC, Ma27 commented
http://semver.org/ - the release yesterday was a release which shouldn't contain anything which is a new feature (and this one is definitly a new feature)

2016-11-07 18:48 UTC, patrick-mcdougle commented
Can we get this in 3.0?

2016-11-23 18:34 UTC, Ma27 commented
@patrick-mcdougle we'll see, 2.6 hopefully :-)

2017-05-30 13:41 UTC, koemeet commented
Any news on this?

2017-05-30 16:29 UTC, lcobucci approved these changes
I've rebased it to sync with `master`, made a tiny change (to use `::class` syntax) and it LGTM

2017-05-30 16:53 UTC, Ma27 commented
ok, thank you @lcobucci :-)

On Tue, May 30, 2017 at 6:29 PM, Luís Cobucci <notifications@github.com>
wrote:

> *@lcobucci* approved this pull request.
>
> I've rebased it to sync with master and made a tiny change (to use ::class
> syntax) and it LGTM
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/doctrine2/pull/5938#pullrequestreview-41003343>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFvwBHfXWf57NDx3vdjcShelzcSXqfnVks5r_EP7gaJpZM4JN-7o>
> .
>

2017-05-31 09:39 UTC, Ocramius requested changes

2017-05-31 09:39 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
> +                    $override['fetch'] = constant('Doctrine\ORM\Mapping\ClassMetadata::FETCH_' . (string) $overrideElement['fetch']);
Can we use `::class` for the first bit of the string?

2017-05-31 09:39 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
> +                    $override['fetch'] = constant('Doctrine\ORM\Mapping\ClassMetadata::FETCH_' . $associationOverride->fetch);
Can we use `::class` for the first bit of the string?

2017-05-31 09:39 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
> +                    $override['fetch'] = constant('Doctrine\ORM\Mapping\ClassMetadata::FETCH_' . $associationOverrideElement['fetch']);
Can we use `::class` for the first bit of the string?

2017-05-31 10:21 UTC, Ma27 commented
thanks for the review, hope I'll find some time tonight to address your comments :-)

> On 31. May 2017, at 11:39 AM, Marco Pivetta <notifications@github.com> wrote:
> 
> @Ocramius requested changes on this pull request.
> 
> In lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php:
> 
> > @@ -621,6 +621,11 @@ public function loadMetadataForClass($className, ClassMetadata $metadata)
>                      $override['inversedBy'] = (string) $overrideElement->{'inversed-by'}['name'];
>                  }
>  
> +                // Check for `fetch`
> +                if (isset($overrideElement['fetch'])) {
> +                    $override['fetch'] = constant('Doctrine\ORM\Mapping\ClassMetadata::FETCH_' . (string) $overrideElement['fetch']);
> Can we use ::class for the first bit of the string?
> 
> In lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php:
> 
> > @@ -470,6 +470,11 @@ public function loadMetadataForClass($className, ClassMetadata $metadata)
>                      $override['inversedBy'] = $associationOverride->inversedBy;
>                  }
>  
> +                // Check for `fetch`
> +                if ($associationOverride->fetch) {
> +                    $override['fetch'] = constant('Doctrine\ORM\Mapping\ClassMetadata::FETCH_' . $associationOverride->fetch);
> Can we use ::class for the first bit of the string?
> 
> In lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php:
> 
> > @@ -622,6 +622,11 @@ public function loadMetadataForClass($className, ClassMetadata $metadata)
>                      $override['inversedBy'] = (string) $associationOverrideElement['inversedBy'];
>                  }
>  
> +                // Check for `fetch`
> +                if (isset($associationOverrideElement['fetch'])) {
> +                    $override['fetch'] = constant('Doctrine\ORM\Mapping\ClassMetadata::FETCH_' . $associationOverrideElement['fetch']);
> Can we use ::class for the first bit of the string?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-05-31 12:55 UTC, Ocramius approved these changes
LGTM :+1:

2017-05-31 12:57 UTC, lcobucci requested changes

2017-05-31 12:57 UTC, lcobucci commented on lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
> +                    $override['fetch'] = constant(ClassMetadata::class . '::FETCH_' . $associationOverride->fetch);
This won't work since `ClassMetadata` points to `Doctrine\Common\Persistence\Mapping\ClassMetadata` and it doesn't have the constants.

2017-05-31 12:57 UTC, Ma27 commented on lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
> +                    $override['fetch'] = constant(ClassMetadata::class . '::FETCH_' . $associationOverride->fetch);
ouch, I'm sorry^^

2017-05-31 12:58 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php
> +                    $override['fetch'] = constant(ClassMetadata::class . '::FETCH_' . $associationOverride->fetch);
ARGH, good catch :S

2017-05-31 16:37 UTC, Ma27 commented
@lcobucci as travis-ci seems to not run on this PR, I just executed the corresponding tests on my machine:

```
→ ./vendor/bin/phpunit --group DDC-5934
PHPUnit 6.2-g3e3c42c32 by Sebastian Bergmann and contributors.

......                                                              6 / 6 (100%)

Time: 1.01 seconds, Memory: 36.00MB

OK (6 tests, 12 assertions)
```

2017-05-31 18:24 UTC, Ocramius commented
@Ma27 travis passed! :+1:

2017-05-31 18:24 UTC, merged