Avoid error when entityName isn't a string
doctrine/doctrine2 pull request #6017
Opened 2016-09-11 14:36 UTC by j0k3r

Previously I wasn't used the `->clear()` method in the correct way. I always put the full entity object in parameter instead of the entity name. It _worked_ before the 2.5.5 even if in fact it cleared nothing ...

With 2.5.5 a check has been added in `clearIdentityMapForEntityName` to verify if the given entity name exist in the entityMap.

Using `isset` with the entity object generated a PHP error `Illegal offset type in isset or empty`.

This PR aim to remove that error.

I'm not sure if this is the right way to fix that problem. I'm maybe the only person who gave the entity object as parameter to the `clear` function.
Maybe we should better detect if it's an object in the `clear` function and use the `:class` attribute to get the class name?

Like 

```php
public function clear($entityName = null)
{
    if (is_object($entityName)) {
        $entityName = $entityName::class;
    }
```

2016-09-11 15:30 UTC, phansys commented
Since the docblock states that the argument must be an string, I think your approach is more a workaround than a fix. Think by instance what will happen when the PHP version is bumped to `^7.0` and the `string` type declaration is used. For this reason, if you think it's a common situation to provide a non supported type for this method, IMO a better solution could be emulate the type declaration:
```php
if (!is_string($entityName)) {
    throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s() must be a string, %s given', __METHOD__, gettype($entityName)));
}
```

2016-09-11 15:38 UTC, j0k3r commented
Might be a better solution yeah.

2016-09-12 14:49 UTC, phansys commented on lib/Doctrine/ORM/UnitOfWork.php
> +        if ($entityName !== null && !is_string($entityName)) {
Please, use Yoda condition.

2016-09-12 14:54 UTC, j0k3r commented on lib/Doctrine/ORM/UnitOfWork.php
> +        if ($entityName !== null && !is_string($entityName)) {
I did it but then checked the file and see that it doesn't use yoda condition. Like on line below `if ($entityName === null) {` that's why I changed it :confused:

2016-11-25 17:30 UTC, j0k3r commented
Should I fix the coding style so this PR can have a chance to be merged?

2016-11-26 03:53 UTC, Ocramius requested changes

2016-11-26 03:53 UTC, Ocramius commented on lib/Doctrine/ORM/UnitOfWork.php
> +            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s() must be a string, %s given', __METHOD__, gettype($entityName)));
This should be something like `throw ORMException::fromInvalidEntityName($entityName)`

2016-11-26 03:54 UTC, Ocramius commented
@j0k3r sorry for missing the review of this before - likely ended in my mail backlog and was never checked later.

The patch is indeed legit, just need to throw an `ORMException` and code the message construction in a named constructor (static method) on the `ORMException` itself.

2016-11-26 22:14 UTC, j0k3r commented
@Ocramius no problem. I've added `ORMException::invalidEntityName`

2016-11-26 23:09 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
> +        $this->_unitOfWork->persist($entity);
Not needed

2016-11-27 17:05 UTC, j0k3r commented on tests/Doctrine/Tests/ORM/UnitOfWorkTest.php
> +        $this->_unitOfWork->persist($entity);
Both removed

2016-11-27 17:24 UTC, Ocramius commented
@j0k3r I'm taking ownership of the branch in order to merge it and apply a few adjustments that I just thought of. Thanks for fixing that unused method call!

Commits will be displayed here, stand by.

2016-11-27 17:40 UTC, closed without merging

2016-11-27 17:42 UTC, j0k3r commented
👍

2016-11-27 17:43 UTC, Ocramius commented
@j0k3r rebased and merged, thanks! doctrine/doctrine2@555e8ae641ef269c5b4793245d13d05170e69d2f

Here's what I added:

 * Checks were moved from `UnitOfWork` to `EntityManager`. While this reduces safety, I still consider `clear($entityName)` to be a deprecated feature, so it will be removed in future. Cluttering `UnitOfWork` seemed excessive, while `EntityManager` is doing the job just fine.
 * `$entityName` is now also checked for entity name validity (just a string is not sufficient!). If `$entityName` is not a valid class name, then a `MappingException` is thrown
 * `$entityName` can now also be a proxy name, so `$entityManager->clear(get_class($aProxy))` will work out of the box

👍