Added test for filtered eager joins
doctrine/doctrine2 pull request #6037
Opened 2016-09-15 13:30 UTC by nicoschoenmaker

An `SQLFilter` is not called on collections with eager loading enabled. This PR contains a unit-test that shows the problem.

If I have
* an order
* with a product
* and the product has a list of features
* where the feature collection has `fetch="EAGER"` enabled
* and only visible feature should be shown (enforced by an enabled `SQLFilter`).

then invisible features are still retrieved from the database!

This PR only contains a unit-test that shows the problem. The test passes if `fetch="EAGER"` is removed.

2017-01-12 10:46 UTC, lcobucci requested changes
Thanks for the work @nicoschoenmaker, could you please apply these changes?

2017-01-12 10:46 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +                $this->_em->getClassMetadata('Doctrine\Tests\ORM\Functional\Order'),
Please use the `::class` syntax instead

2017-01-12 10:46 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +        $conf->addFilter('visibility', '\Doctrine\Tests\ORM\Functional\VisibilityFilter');
Please use the `::class` syntax instead

2017-01-12 10:46 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +            'Doctrine\Tests\ORM\Functional\Feature',
Please use the `::class` syntax instead

2017-01-12 10:46 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +        if ($targetEntity->name !== 'Doctrine\Tests\ORM\Functional\Feature') {
Please use the `::class` syntax instead

2017-01-12 10:46 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +        self::assertSame(2, $count);
Please use `self::assertCount()` instead

2017-01-16 08:28 UTC, nicoschoenmaker commented
Thanks for the feedback @lcobucci.

Updated

2017-02-20 22:21 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +        $conf->addFilter('visibility', '\Doctrine\Tests\ORM\Functional\VisibilityFilter');
@nicoschoenmaker you forgot this one 😄

2017-02-20 22:27 UTC, lcobucci requested changes

2017-02-20 22:27 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +            'Doctrine\Tests\ORM\Functional\Feature',
And this too

2017-02-20 22:27 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +     * @todo If we can't replicate it, this used to be Id
Is this `todo` relevant?

2017-02-20 22:27 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/EagerJoinTest.php
> +        $this->visible = (bool)$visible;
Add space after closing parenthesis

2025-01-31 03:02 UTC, closed without merging