Solution bug Problem custom name sequeceGenerator YAML why not create…
doctrine/doctrine2 pull request #6071
Opened 2016-10-05 13:42 UTC by monstrodopantano

Hi please accept my pull request to fixed custom sequence name. [#5789](https://github.com/doctrine/doctrine2/issues/5789)
best regards

2016-10-06 00:09 UTC, Ocramius requested changes

2016-10-06 00:09 UTC, Ocramius commented on .gitignore
> +nbproject/
Please use your [global gitignore file](https://help.github.com/articles/ignoring-files/)

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
>              case ClassMetadata::GENERATOR_TYPE_SEQUENCE:
Please do not change file FS flags

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
>                      if (isset($fieldMapping['generator']['strategy'])) {
Please do not change file FS flags

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
> +                    $schemaElementName = is_array($customDefinition) ? $customDefinition['sequenceName'] : $this->getTargetPlatform()->fixSchemaElementName($sequenceName);
This check seems to be duplicated

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
> +                            && strtoupper($fieldMapping['generator']['strategy']) == 'SEQUENCE'){
Please use `===` when comparing

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
> +                            && strtoupper($fieldMapping['generator']['strategy']) == 'SEQUENCE'){
Also check CS: Space before `{`

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
> +                        if(isset($fieldMapping['generator']['sequenceGenerator'])
Check CS: space after `if`

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/YamlDriver.php
> +                        if(isset($fieldMapping['generator']['sequenceGenerator'])
This block needs to be tested (unit or integration test needed)

2016-10-06 00:09 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php
> +                if ( ! $definition || is_array($customDefinition) ) {
This added scenario needs tests

2016-10-06 12:51 UTC, Ocramius commented on .gitignore
>  .project
Please don't change FS flags here either

2016-10-06 12:55 UTC, monstrodopantano commented
Hi Ocraminus I fixed all bug requested. Only test scenario I will not do it due complexity framework. If you can not do the test then ignore my correction for bug.
best regards

2016-10-06 12:56 UTC, Ocramius commented
@monstrodopantano please look into https://github.com/doctrine/doctrine2/tree/d3f6c5ec70aac4b029a4b61ecf1e2ba61a1a4a6d/tests/Doctrine/Tests/ORM/Functional/Ticket for example tests. Without a test, a patch is never going to be considered.

2018-08-06 23:28 UTC, ostrolucky commented
I'm sorry, but this issue is no longer relevant in Doctrine 3.0

2018-08-06 23:28 UTC, closed without merging