Static Code Analysis with Php Inspections (EA Extended)
doctrine/doctrine2 pull request #6121
Opened 2016-11-06 13:25 UTC by kalessil

A few findings: security, performance, compatibility, potential bugs and couple of code style findings

2016-11-06 16:06 UTC, Ocramius requested changes

2016-11-06 16:06 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
> +        unset($dirName);
Not sure if I like this inspection. `$dirName` is not used after this location: let the stack garbage collection do its job.

2016-11-06 16:06 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
> +            unset($joinColumn);
Same as below: this inspection is (IMO) not a good idea.

2016-11-06 16:23 UTC, kalessil commented on lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
> +        unset($dirName);
It's more tricky: https://3v4l.org/QKOKH - here unset should clean the scope after foreach.

2016-11-06 16:53 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
> +        unset($dirName);
I know why this is applied, it just doesn't make sense if the variables are unused. I'd rather prefer extracting the loop into a private method instead.

2016-11-06 16:55 UTC, kalessil commented on lib/Doctrine/ORM/Tools/Console/Command/ConvertDoctrine1SchemaCommand.php
> +        unset($dirName);
I see, good approach btw. Reverting the change.

2016-11-06 16:57 UTC, kalessil commented on lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
> +            unset($joinColumn);
Reverting. I also curious why it's not a good idea, why?

2016-11-06 17:29 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
> +            unset($joinColumn);
It's just an additional instruction (also to read - not worried about performance)

2016-11-25 07:09 UTC, kalessil commented
@Ocramius : I reverted usset constructs here, but checks still saying that you requested changes.

2016-11-26 03:57 UTC, Ocramius commented
@kalessil thanks for this, merging!

2016-11-26 03:57 UTC, merged