Added unit test for boolean option values.
doctrine/doctrine2 pull request #6130
Opened 2016-11-16 16:57 UTC by kalimatas

It fails now. In `XmlDriver::_parseOptions` we need somehow to maintain a list of options, that are supposed to be boolean, and then call `$this->evaluateBoolean()` on them.

2016-11-16 16:57 UTC, Ocramius commented
Ref: #6129

2016-11-16 17:00 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
> +        $class = $this->createClassMetadata('Doctrine\Tests\ORM\Mapping\User');
Can use `::class` for new code

2016-11-16 17:00 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Mapping/XmlMappingDriverTest.php
> +    public function testBooleanValuesForOptionIsSetCorrectly()
Can you please add an `/** @group #6129 */` or similar?

2016-11-16 17:00 UTC, Ocramius commented
@kalimatas thanks for converting it into an actual failing scenario!

2016-11-17 19:44 UTC, Ocramius requested changes

2016-11-17 19:44 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
> +        $booleanOptions = ['unsigned', 'fixed'];
Since this constant is not used anywhere else, it can be inlined into the `in_array()` call

2016-11-17 19:44 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
> +                $attrName = (string) $attr->name;
Please don't abbreviate. I know the previous code did, but we should really call it `$attributeName` or such

2016-11-17 19:44 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
> +     * @depends testIdentifier
Shouldn't need `@depends`

2016-11-17 20:21 UTC, kalimatas commented
@Ocramius fixed

2016-11-17 20:24 UTC, Ocramius commented
@kalimatas thanks! This looks good, merging!

👍

2016-11-17 20:24 UTC, merged