[DX] Add details about invalid Connection passed at creation of EntityManager.
doctrine/doctrine2 pull request #6136
Opened 2016-11-17 16:27 UTC by SpacePossum

2016-11-17 19:07 UTC, Ocramius requested changes

2016-11-17 19:07 UTC, Ocramius commented on lib/Doctrine/ORM/EntityManager.php
> +            throw new \InvalidArgumentException(sprintf('Invalid argument for connection "%s".', is_object($connection) ? get_class($connection) : gettype($connection) . '#' . $connection));
The `#` is confusing in my opinion. The message should probably be `'Invalid $connection argument of type %s given: "%s"'`

2016-11-17 19:08 UTC, Ocramius requested changes

2016-11-17 19:08 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/EntityManagerTest.php
> +     * @expectedException \InvalidArgumentException
Please use `$this->expectExceptionMessage()` and `$this->expectException()` instead of the annotation

2016-11-17 20:27 UTC, SpacePossum commented on tests/Doctrine/Tests/ORM/EntityManagerTest.php
> +     * @expectedException \InvalidArgumentException
fine by me to change, but `setExpectedException` has been deprecated on PHPUnit
(for ref.: https://github.com/sebastianbergmann/phpunit/issues/2074#issuecomment-183472385)

2016-11-17 20:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/EntityManagerTest.php
> +     * @expectedException \InvalidArgumentException
@SpacePossum then the new API. We can bump the required PHPUnit version without any issues 👍

2016-11-18 07:07 UTC, SpacePossum commented on tests/Doctrine/Tests/ORM/EntityManagerTest.php
> +     * @expectedException \InvalidArgumentException
:+1: updated

2016-11-18 08:21 UTC, Ocramius commented
@SpacePossum 👍 merged, thanks a lot!

2016-11-18 08:21 UTC, merged

2016-11-18 08:25 UTC, SpacePossum commented
thanks @Ocramius :+1:   :)