Report that FROM and JOIN do not support Subqueries
doctrine/doctrine2 pull request #6162
Opened 2016-12-06 10:37 UTC by SimonHeimberg

Make obvious that this is not supported.

2016-12-06 10:38 UTC, SimonHeimberg commented
It is not obvious that Subqurries are not supported in FROM and JOIN. A question about how to do a subquery with dql pops up frequently.

Examples for questions:
 * http://stackoverflow.com/questions/27007090/inner-join-results-from-select-statement-using-doctrine-querybuilder#comment42611323_27007090
 * http://stackoverflow.com/questions/13163059/subquery-in-join-with-doctrine-dql
 * http://stackoverflow.com/questions/40617755/join-a-subquery-with-doctrine-dql/40715419#40715419


I can not run the unit test unfortunately because of too old php. Should I add a unit test? Where?

2016-12-12 07:32 UTC, Ocramius commented
Requires test case. Can be added to https://github.com/doctrine/doctrine2/blob/6e6be3fdd92728b26a79576f7f91abe4080e54ff/tests/Doctrine/Tests/ORM/Query/QueryTest.php

If you can't run tests locally, travis-ci will do for you.

2016-12-27 21:07 UTC, SimonHeimberg commented
Tests added

2016-12-28 01:40 UTC, Ocramius requested changes

2016-12-28 01:40 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Query/QueryTest.php
> +     * @expectedException        Doctrine\ORM\Query\QueryException
Please use `$this->expectException(QueryException::class)` and `$this->exceptExceptionMessage('Subquery')` directly before the code that is supposed to trigger the failure (I suppose it's `$query->getResult()` here?

2016-12-28 01:40 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Query/QueryTest.php
> +     * @expectedException        Doctrine\ORM\Query\QueryException
Please use `$this->expectException(QueryException::class)` and `$this->exceptExceptionMessage('Subquery')` directly before the code that is supposed to trigger the failure (I suppose it's `$query->getResult()` here?

2016-12-28 01:41 UTC, Ocramius commented
@SimonHeimberg thanks for looking into the tests! This is indeed a good addition for 2.6 :-)

2017-01-26 15:30 UTC, hkdobrev commented
@Ocramius @SimonHeimberg Is there anything else needed to be done for this? This would be a great addition!

2017-04-19 15:38 UTC, SimonHeimberg commented
oops, tests failed, wait a minute...

2017-04-19 16:11 UTC, SimonHeimberg commented
I finally managed to fix the typos, new commit ready for review now.

2017-06-21 03:39 UTC, closed without merging

2017-06-21 03:39 UTC, Ocramius commented
@SimonHeimberg this was manually rebased and merged into `master`, via doctrine/doctrine2@1e3bf6562e08b24b9973343b031e063ad6325d23, thanks! \o/