Fixed #6167 - Forced SELECT NEXTVAL to be run on master
doctrine/doctrine2 pull request #6168
Opened 2016-12-09 20:52 UTC by mkurzeja

A possible solution for #6167 - Doctrine ORM failing to insert to a master-slave PostgreSQL setup because of running NEXTVAL on a slave.

2016-12-09 20:54 UTC, Ocramius commented
Requires a test case

2016-12-09 20:57 UTC, mkurzeja commented
And it seems it broke support for other databases.

2016-12-09 21:55 UTC, mkurzeja commented
Ok, so this does not break any DB support, it just does not fit the tests written. I will provide a fix and a new test for this scenario.

2016-12-12 07:07 UTC, mkurzeja commented
@Ocramius I have fixed the existing test, but I cannot think about a good test that could be run in CI. Travis does not support master-slave setup, and the whole logic is inside MasterSlaveConnection that I did not touch at all. I would have to write a custom test that wouldn't be run on Travis, or I would have to mock a lot of things just to check that MasterSlaveConnection::query() is run on the master server. Please let me know if I'm missing something and there is a better way to test this case.

2016-12-12 07:15 UTC, Ocramius commented
@mkurzeja what you could do is writing a test that asserts that `query` is used, whereas `fetchColumn` isn't, is sufficient.

Can be done via a mock/spy, and indeed needs some documentation around it.

2016-12-12 12:40 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Id/SequenceGeneratorTest.php
> +                $nextId = array(array((int)($i / 10) * 10));
@mkurzeja please use short-array syntax here ;)

2016-12-12 18:14 UTC, phansys requested changes
Status: Needs work.

2016-12-12 18:14 UTC, phansys commented on tests/Doctrine/Tests/Mocks/ConnectionMock.php
> +        if ($this->_fetchOneException != null) {
Please, use Yoda condition and strict comparison.

2016-12-12 18:14 UTC, phansys commented on tests/Doctrine/Tests/Mocks/ConnectionMock.php
> +     * @param \Exception $exception
Please, update this docblock in order to reflect that this param also accepts `null`.

2016-12-12 18:14 UTC, phansys commented on tests/Doctrine/Tests/Mocks/ConnectionMock.php
> +    public function setQueryResult($result)
Can `$result` argument be declared as `Statement`?

2016-12-12 18:14 UTC, phansys commented on tests/Doctrine/Tests/ORM/Id/SequenceGeneratorTest.php
> +            new \Exception('Fetch* method used. Query method should be used instead, as NEXTVAL should be run on a master server in master-slave setup.')
SPL `\LogicException` or `\RuntimeException` could be less generic.

2016-12-12 19:22 UTC, mkurzeja commented
Thanks @phansys and @lcobucci for review and @Ocramius for help. Hope this is acceptable now ;)

2016-12-12 20:18 UTC, Ocramius commented on tests/Doctrine/Tests/Mocks/ConnectionMock.php
> +        if (null !== $this->_fetchOneException) {
This makes sense, but I'll probably have to change it to use the mocking framework to do this (on merge)

2017-06-21 04:05 UTC, closed without merging

2017-06-21 04:05 UTC, Ocramius commented
This has been manually rebased and merged into `master` via doctrine/doctrine2@07a9b10f3678664a15049be0fc3ff47374435152

Thanks @mkurzeja \o/

2017-11-15 01:09 UTC, wlzch commented
Hi,

Any reason why is this not merge into 2.5 branch? Also is there a workaround if I want to use it in v2.5? Thanks.

2017-11-20 12:29 UTC, gigi commented
Hi!
We need this fix in 2.5 too. Any solutions? Thanx

2017-11-24 02:17 UTC, lcobucci commented
@wlzch @gigi I've just tried to backport this and unfortunately it cannot be done easily, since it has dependencies on things that only exists on `v2.6` (and backporting these things might lead us down the rabbit hole).

As stated on every [single `v2.5.x` milestone in repo since `2.5.8`](https://github.com/doctrine/doctrine2/milestones?state=closed), we no longer actively support 2.5.x since we must release `v2.6` ASAP. So, sorry but this won't be part of any `v2.5.x` release.

2017-11-24 08:45 UTC, gigi commented
@lcobucci 
Thanks for answer! 
But is it not enough to replace `$this->_nextValue = (int)$conn->fetchColumn($sql);` with `$this->_nextValue = (int) $conn->query($sql)->fetchColumn();` in `\Doctrine\ORM\Id\SequenceGenerator::generate`?

2017-11-24 09:08 UTC, lcobucci commented
@gigi not really, we need to get the tests as well to make sure things work and that's the tricky part

2017-11-24 09:18 UTC, lcobucci commented
@gigi if you have the time and need this really badly (and can't update your stack to use 2.6) you can try to cherry-pick the commits related to the merge commit that @Ocramius mentioned with all the dependencies (ensuring that things are compatible with PHP 5.4) please do it and send us a PR.

2017-11-27 14:01 UTC, gigi commented
@lcobucci https://github.com/doctrine/doctrine2/pull/6852