Minor fixes to the 'getting started' page
doctrine/doctrine2 pull request #6179
Opened 2016-12-19 03:36 UTC by biggianteye

- Use consistent visibility for some fields.
- Fixing path of yaml file.
- Minor grammar changes.

2016-12-19 22:55 UTC, Ocramius requested changes

2016-12-19 22:55 UTC, Ocramius commented on docs/en/tutorials/getting-started.rst
> +        protected $reportedBugs = null;
Should stay `private`

2016-12-19 22:55 UTC, Ocramius commented on docs/en/tutorials/getting-started.rst
> +        protected $assignedBugs = null;
Should stay `private`

2016-12-21 02:01 UTC, biggianteye commented on docs/en/tutorials/getting-started.rst
> +        protected $reportedBugs = null;
Could you explain why? All other instance variables are marked as `protected`. Why should these two be `private`?

More importantly, they were declared as `protected` when first added to the `User` class. If there is a legitimate need for the change to the visibility, let me know and I'll incorporate it into the section where the visibility changes.

2016-12-23 01:32 UTC, Ocramius commented on docs/en/tutorials/getting-started.rst
> +        protected $reportedBugs = null;
I'd rather have everything as `private` around the code, but if you think that `protected` is better for consistency (for now), I can merge the PR as-is.

Should generally strive for `private` in future.

2016-12-23 02:22 UTC, biggianteye commented on docs/en/tutorials/getting-started.rst
> +        protected $reportedBugs = null;
I'm not trying to advocate one over the other (though if I were, I'd go for private). I'm just trying to remove any confusion caused by modifiers changing half way through introductory documentation without any explanation.

2016-12-23 03:02 UTC, Ocramius commented on docs/en/tutorials/getting-started.rst
> +        protected $reportedBugs = null;
Good, merging as-is then :-)

2016-12-23 03:03 UTC, merged

2016-12-23 10:35 UTC, biggianteye commented on docs/en/tutorials/getting-started.rst
> +        protected $assignedBugs = null;
👍

2016-12-23 10:35 UTC, biggianteye commented on docs/en/tutorials/getting-started.rst
> +        protected $reportedBugs = null;
👍