#6195 Add check for expressions from subqueries in LimitSubqueryOutputWalker#walkPathExpression
doctrine/doctrine2 pull request #6196
Opened 2016-12-24 19:21 UTC by Daegon

Issue #6195

2016-12-24 21:12 UTC, Ocramius commented
Tests needed

2016-12-28 15:56 UTC, phansys requested changes
Status: Needs work.

2016-12-28 15:56 UTC, phansys commented on lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
> +            if ($queryComp['nestingLevel'] == 0) {
Can this comparison be strict? BTW, please use Yoda condition.

2016-12-29 22:05 UTC, billschaller commented
This hoisting logic was hard as fuck to write... I hate limit/offset quirks with a passion.

2024-05-22 16:04 UTC, PastisD commented
Hello,

Sorry to up this very old PR but I have the same issue and this fix works on my side :)
Any chance this PR can be merged ?

2024-06-12 20:48 UTC, SenseException commented
If you like you can provide a new PR and apply what was asked back then.

2025-01-29 03:03 UTC, closed without merging