Remove unused "$className" argument
doctrine/doctrine2 pull request #6216
Opened 2017-01-05 21:24 UTC by malukenho

/cc @Ocramius @lcobucci

2017-01-05 21:34 UTC, Ocramius requested changes

2017-01-05 21:34 UTC, Ocramius commented on lib/Doctrine/ORM/Persisters/Entity/AbstractEntityInheritancePersister.php
> +    protected function getSelectJoinColumnSQL($tableAlias, $joinColumnName, $type)
This is a minor BC break, and needs to be documented in [`UPGRADE.md`](https://github.com/doctrine/doctrine2/blob/master/UPGRADE.md)

2017-01-11 20:39 UTC, malukenho commented
@Ocramius now that I looked at it more deeply, this change can break code on users' side as `AbstractEntityInheritancePersister#getSelectJoinColumnSQL` is protected and can be overwrited.

Still valid or can be closed?

2017-01-12 15:57 UTC, Ocramius requested changes

2017-01-12 15:57 UTC, Ocramius commented on UPGRADE.md
> +## Minor BC BREAK: remove $className parameter on AbstractEntityInheritancePersister#getSelectJoinColumnSQL
`removed`

2017-01-12 15:57 UTC, Ocramius commented on UPGRADE.md
> +## Minor BC BREAK: remove $className parameter on AbstractEntityInheritancePersister#getSelectJoinColumnSQL
Put backticks around `AbstractEntityInheritancePersister#getSelectJoinColumnSQL`

2017-01-12 15:57 UTC, Ocramius commented on UPGRADE.md
> +As `$className` parameter is not used on its method body, it was safely removed.
s/`is not used on its method body`/`was not used in the method`

2017-01-12 15:59 UTC, Ocramius commented
> @Ocramius now that I looked at it more deeply, this change can break code on users' side as `AbstractEntityInheritancePersister#getSelectJoinColumnSQL` is protected and can be overwrited.

Persisters are internal API, and we don't support custom userland persisters anyway. This is still valid.

2017-01-12 16:04 UTC, merged