Fix invalid joinColumn in ClassMetadata::associationMappings
doctrine/doctrine2 pull request #6222
Opened 2017-01-10 20:25 UTC by gadelkareem

Fix getting `Notice: Undefined index: user_id` for a user field association

2017-01-10 22:18 UTC, phansys requested changes
Status: Needs work.

2017-01-10 22:18 UTC, phansys commented on lib/Doctrine/ORM/Utility/IdentifierFlattener.php
> +            } elseif (array_key_exists($field, $id)) {
Can `$id[$field]` be `null`? If that isn't the case, `isset()` is able to deliver better performance.

2017-01-10 22:18 UTC, phansys commented on lib/Doctrine/ORM/Utility/IdentifierFlattener.php
> +
Please, remove surplus line break.

2017-01-11 00:54 UTC, Ocramius commented
Please re-send this against master. Also, tests are absolutely needed, as well as an example of where this is happening.

2017-01-11 10:51 UTC, gadelkareem commented on lib/Doctrine/ORM/Utility/IdentifierFlattener.php
> +            } elseif (array_key_exists($field, $id)) {
Yes $id[$field] is null if Eager loading is not enabled.

2023-01-31 20:57 UTC, mpdude commented
@gadelkareem is this still an issue?

2023-01-31 22:24 UTC, closed without merging