Fix issue where xml mapping cannot find file on certain configurations
doctrine/doctrine2 pull request #6254
Opened 2017-01-25 12:55 UTC by mistraal

Please refer to [this issue](https://github.com/wallabag/wallabag/issues/1828) and [this issue](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1062). 

While this is a very specific case, it is not exclusive to Nginx server as it also happens on my Apache setup.

2017-01-25 12:55 UTC, Ocramius commented
This needs a test case.

2017-01-25 12:56 UTC, Ocramius requested changes

2017-01-25 12:56 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
> +        $xmlData = file_get_contents($file);
Can be inlined

2017-02-01 07:29 UTC, phansys requested changes
Status: Answer pending.

2017-02-01 07:29 UTC, phansys commented on lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
> +        $xmlElement = simplexml_load_string(file_get_contents($file));
Is there any situation where [`simplexml_load_file()`](http://php.net/manual/en/function.simplexml-load-file.php) is not returning `false` with a not found file?

2017-02-01 10:07 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
> +        $xmlElement = simplexml_load_string(file_get_contents($file));
> Is there any situation where [`simplexml_load_file()`](http://php.net/manual/en/function.simplexml-load-file.php) is not returning `false` with a not found file?

Indeed, that's what a test would verify, but I see no tests.

2017-02-01 13:46 UTC, phansys commented
This is related to #930.

2017-02-20 22:29 UTC, lcobucci commented
@mistraal can you please rebase with `develop` dropping all commits that aren't yours please?

2017-02-20 22:55 UTC, closed without merging