Removing detach and merge from the entity manager
doctrine/doctrine2 pull request #6265
Opened 2017-01-29 21:58 UTC by mikeSimonson

and the related tests

2017-01-29 22:02 UTC, mikeSimonson commented
@Ocramius Not sure what to do with the last test that fails Doctrine\Tests\ORM\Functional\Ticket\DDC3303Test::testEmbeddedObjectsAreAlsoInherited ?

Travis does weird stuff for some reasons.

Is this sort of what you expected ?

2017-01-30 21:43 UTC, Ocramius requested changes

2017-01-30 21:43 UTC, Ocramius commented on lib/Doctrine/ORM/EntityManager.php
> -        $this->unitOfWork->detach($entity);
These methods are to be removed as well

2017-01-30 21:43 UTC, Ocramius commented on lib/Doctrine/ORM/EntityManager.php
> -        return $this->unitOfWork->merge($entity);
These methods are to be removed as well

2017-01-30 21:44 UTC, Ocramius commented
@mikeSimonson can't see failures, as the `EntityManagerInterface` is not fully covered by an implementation now.

2017-01-31 10:04 UTC, lcobucci commented
@mikeSimonson embeddables were temporarily disabled by @guilhermeblanco on `develop` 😉

2017-01-31 14:27 UTC, mikeSimonson commented
@lcobucci Thanks for the info, but still it's weird that the test passed before I removed the merge and detach functionality no ?

2017-01-31 16:32 UTC, guilhermeblanco commented
@lcobucci there's much more to be removed and decided than a blank removal of the EM methods.
UoW also contains a bunch of related methods to merge/detach, but the key decisions to be made are how do we handle the entity states now that there's no more detached state. If you look at UoW methods, there're lots of state detached handling there.

IMHO, whenever we have state detached we should either reintegrate the state as managed or consider it as new.

Once you have that sorted out, I can properly review the PR. =)

2017-02-01 07:01 UTC, Ocramius commented
I would honestly just don't deal with that, and instead let users decide
how to:

 * Hydrate from array data (custom hydrator)
 * Manage dirty state (if integrated entities need to be added to the ORM)
 * Load existing state on their own (they can assume existing records or
not, since they decided how to detach on their own)

On 31 Jan 2017 5:32 p.m., "Guilherme Blanco" <notifications@github.com>
wrote:

> @lcobucci <https://github.com/lcobucci> there's much more to be removed
> and decided than a blank removal of the EM methods.
> UoW also contains a bunch of related methods to merge/detach, but the key
> decisions to be made are how do we handle the entity states now that
> there's no more detached state. If you look at UoW methods, there're lots
> of state detached handling there.
>
> IMHO, whenever we have state detached we should either reintegrate the
> state as managed or consider it as new.
>
> Once you have that sorted out, I can properly review the PR. =)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/doctrine2/pull/6265#issuecomment-276415026>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakDqkucihhaFiq4kJ_ZkWZO7ueAyeks5rX2IogaJpZM4Lw7HR>
> .
>

2017-09-24 15:12 UTC, Ocramius commented
Handled in https://github.com/doctrine/doctrine2/pull/1577

2017-09-24 15:12 UTC, closed without merging