Fixing #5887 - lazy loading of one-to-one relationship with custom id object
doctrine/doctrine2 pull request #6274
Opened 2017-02-03 23:04 UTC by Necsord

Fixing case when lazy loading of entity in one-to-one relationship on the side without foreign key
did not return the entity because of custom type not being detected and properly formatted before
applying to database query.

2017-02-19 11:56 UTC, lcobucci requested changes
@Necsord thanks for the PR but unfortunately it doesn't solve the issue.

Your test is only passing because you're setting the parameter type on the query (`->setParameter('id', $customerId, Issue5887CustomIdObjectType::NAME)`).

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/Models/Issue5887/Issue5887Cart.php
> +class Issue5887Cart
Please move this class to the test file (like we have [here](https://github.com/doctrine/doctrine2/blob/e4704beaf9fad5a521fe7592dec382ae209b3cc1/tests/Doctrine/Tests/ORM/Functional/Ticket/GH6141Test.php)).

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/Models/Issue5887/Issue5887CustomIdObject.php
> +class Issue5887CustomIdObject
Please move this class to the test file (like we have [here](https://github.com/doctrine/doctrine2/blob/e4704beaf9fad5a521fe7592dec382ae209b3cc1/tests/Doctrine/Tests/ORM/Functional/Ticket/GH6141Test.php)).

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/Models/Issue5887/Issue5887CustomIdObjectType.php
> +class Issue5887CustomIdObjectType extends Type
Please move this class to the test file (like we have [here](https://github.com/doctrine/doctrine2/blob/e4704beaf9fad5a521fe7592dec382ae209b3cc1/tests/Doctrine/Tests/ORM/Functional/Ticket/GH6141Test.php)).

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/Models/Issue5887/Issue5887CustomIdObjectType.php
> +class Issue5887CustomIdObjectType extends Type
It can also inherit `StringType` instead so you don't need to implement the method `getSQLDeclaration()`.

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/Models/Issue5887/Issue5887Customer.php
> +class Issue5887Customer
Please move this class to the test file (like we have [here](https://github.com/doctrine/doctrine2/blob/e4704beaf9fad5a521fe7592dec382ae209b3cc1/tests/Doctrine/Tests/ORM/Functional/Ticket/GH6141Test.php)).

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/SchemaValidatorTest.php
> +            if (in_array($modelSet, ["customtype", "issue5887"])) {
Not needed for inlined classes

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/OrmFunctionalTestCase.php
> +        'issue5887' => [
Not needed for inlined classes

2017-02-19 11:56 UTC, lcobucci commented on tests/Doctrine/Tests/OrmFunctionalTestCase.php
> +        if (isset($this->_usedModelSets['issue5887'])) {
Not needed for inlined classes

2017-02-23 19:25 UTC, Necsord commented
@lcobucci Thanks for looking into this. I've applied changes regarding your comments and simplified test case to test only the most basic case I could come up with.

The problem is not with the first query for `Customer` which as you pointed out uses type, it's with the second one for `Cart` initiated in `\Doctrine\ORM\UnitOfWork::createEntity`:

```
// Inverse side of x-to-one can never be lazy
$class->reflFields[$field]->setValue($entity, $this->getEntityPersister($assoc['targetEntity'])->loadOneToOneEntity($assoc, $entity));
```

If you remove the applied change in `BasicEntityPersister` the test will fail.

2017-04-30 17:59 UTC, lcobucci approved these changes

2017-04-30 18:00 UTC, lcobucci commented
@Necsord I've just rebased your branch to sync with `master` and squash the commits. Patch LGTM just waiting for tests to pass and I'll merge it.

Thanks for your contribution 😉

2017-04-30 18:10 UTC, merged