Add tests for #6217
doctrine/doctrine2 pull request #6284
Opened 2017-02-10 16:19 UTC by gadelkareem

I recreated the branch for https://github.com/doctrine/doctrine2/pull/6217 which forced closing to PR so I am submitting this as a new PR. 

DESC: Handle AssociationCacheEntry identifier

Fixes Notice: Undefined property: Doctrine\ORM\Cache\AssociationCacheEntry::$id when retrieving an associated entity from a Composite primary key

2017-02-10 17:38 UTC, Ocramius commented
@lcobucci if you merge this one, can you please check if the test can be moved to a smaller SUT test?

2017-02-19 10:59 UTC, lcobucci approved these changes
@gadelkareem thanks for the patch!

@Ocramius I've managed to reduce the SUT and saw that the problem ONLY happens when the fetch mode is `EAGER`.

I've rebased it, removed some unrelated CS fixes and applied the same logic [here](https://github.com/doctrine/doctrine2/pull/6284/files#diff-093aaad4da679d0374260757bf7bafcaR722).

@Ocramius although it LGTM would be nice to have your eyes too

2017-06-21 04:41 UTC, Ocramius requested changes
Ouch, forgot to send in this review :-\

2017-08-21 07:03 UTC, Ocramius commented
Re-iterating this: I don't think that classmetadata should ever interact with an `AssociationCacheEntry` object. This patch fixes a symptom, rather than the cause of the issue, which is the fact that an `AssociationCacheEntry` object is given to the metadata in first place.

2017-08-22 18:40 UTC, Ocramius commented
I checked this patch locally, and the bug is fixed on the wrong end here: the `DefaultQueryCache` is passing incorrect data to `UnitOfWork#createEntity()`. I'm currently fixing that :+1:

2017-08-22 22:32 UTC, Ocramius commented
@gadelkareem please check #6640 and verify it against your codebase.

2017-08-23 10:10 UTC, gadelkareem commented
@Ocramius thanks for the fix and sorry for having no time to help
All tests are passing including GH6217Test so I think this is fixed.

2017-08-25 07:22 UTC, closed without merging