Issue #6297 functional test
doctrine/doctrine2 pull request #6301
Opened 2017-02-23 14:45 UTC by podorozhny

2017-02-23 14:57 UTC, lcobucci requested changes
Now I could see better what's happening.

According to the [documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#joincolumn)

> referencedColumnName: Name of the primary key identifier that is used for joining of this relation.

So that's indeed an invalid mapping and I'd say that the `SchemaValidator` should warn about that. What do you say @Ocramius?

2017-02-23 14:57 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> +    public function __construct($id, GH6297Group $group)
`master` requires PHP7+ so you can use `int $id`

2017-02-23 14:57 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> +    public function __construct($primaryId, $secondaryId)
Add typehints here instead of casting the values

2017-02-23 14:57 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> +     * @Id()
Parentheses are not needed here

2017-02-23 14:57 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> +     * @Id()
Parentheses are not needed here

2017-02-23 14:59 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> + * @Table(name="gh6297_users")
You can just drop `@Table` here

2017-02-23 14:59 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> + * @Table(name="gh6297_groups")
You can just drop `@Table` here

2017-02-23 15:05 UTC, podorozhny commented
> referencedColumnName: Name of the primary key identifier that is used for joining of this relation.

So, I can't use "secondary" properties to join entities? Seems like must-have feature.
It's a pity!

2017-02-23 15:08 UTC, podorozhny commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> + * @Table(name="gh6297_groups")
Already renamed table name with issue number prefix.

2017-02-23 15:08 UTC, podorozhny commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH6297Test.php
> + * @Table(name="gh6297_users")
Already renamed table name with issue number prefix.

2017-02-25 09:20 UTC, podorozhny commented
@Ocramius

2017-02-25 11:48 UTC, Ocramius commented
An identifier is an identifier, and for the ORM it means that:
 * it doesn't change (immutable)
 * it is unique
 
The ORM will always require identifiers to be referenced for any kind of association mapping, as it would otherwise also be impossible to identify those associations in the ORM's in-memory state.

This is both a reasonable and an intentional limitation, and also is good DB design (if you remove the ORM from the discussion).

Closing as `invalid`

2017-02-25 11:48 UTC, closed without merging