Improve exception message (quick to review)
doctrine/doctrine2 pull request #6325
Opened 2017-03-06 19:11 UTC by Isinlor

Hello,
I have added path expression to the exception about single-valued association to an inverse side being not supported. The path expression makes it easier to identify the issue among many other expression in potentially complex query. 

[Seems like many people had an issue with this exception.](https://www.google.com/search?q=A+single-valued+association+path+expression+to+an+inverse+side+is+not+supported+in+DQL+queries.)

For a query:
```sql
SELECT u FROM Doctrine\Tests\Models\CMS\CmsUser u WHERE u.address IN (?1, ?2)
```

The exception message before:

> A single-valued association path expression to an inverse side is not supported in DQL queries. Use an explicit join instead.

The exception message after:

> A single-valued association path expression to an inverse side is not supported in DQL queries. Instead of 'u.address' use an explicit join.

2017-03-06 21:02 UTC, lcobucci approved these changes
Even though it's a very tiny BC break it LGTM. @Ocramius should we document this in the v2.6 changelog?

2017-03-12 15:51 UTC, Ocramius requested changes
LGTM besides nitpicking. As @lcobucci mentioned, we need an entry in `UPGRADE.md` for this, since it still counts as BC Break.

2017-03-12 15:51 UTC, Ocramius commented on lib/Doctrine/ORM/Query/QueryException.php
> +    public static function associationPathInverseSideNotSupported($pathExpr)
I know the caller side uses abbreviations, but please don't abbreviate here.

2017-03-12 15:51 UTC, Ocramius commented on lib/Doctrine/ORM/Query/QueryException.php
> +     * @param object $pathExpr
Is there really nothing more detailed than `object`? :| Sounds like the `SqlWalker` internal API could need a DTO

2017-03-12 15:51 UTC, Ocramius commented
And yep, a test for the static method is needed :-\

2017-03-12 19:38 UTC, Isinlor commented on lib/Doctrine/ORM/Query/QueryException.php
> +    public static function associationPathInverseSideNotSupported($pathExpr)
[I was following this example.](https://github.com/Isinlor/doctrine2/blob/4f854ae7cca3f94df363321b5e9ab878c0580249/lib/Doctrine/ORM/Query/QueryException.php#L150) Are you fine with the inconsistency?

2017-03-24 23:13 UTC, Ocramius commented on lib/Doctrine/ORM/Query/QueryException.php
> +    public static function associationPathInverseSideNotSupported($pathExpr)
If you can add it to the patch, could also rename the variable there please?  👍

2017-06-21 06:17 UTC, closed without merging

2017-06-21 06:17 UTC, Ocramius commented
@Isinlor I manually applied the patch after a rebase and some minor fixes: see doctrine/doctrine2@9b9128ae774ed20d8ccfd03d2fd2a540c140acdd

Thanks!