onFlush and postFlush Entity Listeners
doctrine/doctrine2 pull request #6345
Opened 2017-03-16 23:04 UTC by alexgurrola

Simply check if an onFlush or postFlush entity listener is subscribed
for the current class in the entity manager during dispatch.

This is a rebased followup to #5822, per @lcobucci's review.

2017-03-20 03:32 UTC, phansys requested changes
Status: Needs work.

2017-03-20 03:32 UTC, phansys commented on lib/Doctrine/ORM/UnitOfWork.php
> +                $hash = (isset($this->entityIdentifiers[$oid]) && isset($this->entityIdentifiers[$oid]['id'])) ? $this->entityIdentifiers[$oid]['id'] : null;
You could use a single call to `isset()`:
```php
$hash = isset($this->entityIdentifiers[$oid], $this->entityIdentifiers[$oid]['id']) ? $this->entityIdentifiers[$oid]['id'] : null;
```

2017-03-20 03:32 UTC, phansys commented on lib/Doctrine/ORM/UnitOfWork.php
> +                    if (is_object($hash) && method_exists($hash, '__toString')) $hash = $hash->__toString();
Please, use curly braces within `if` control structures.

2017-03-20 03:32 UTC, phansys commented on lib/Doctrine/ORM/UnitOfWork.php
> +                        if ($oid == spl_object_hash($entity)) {
Please, use Yoda condition and strict comparison.

2017-03-20 03:32 UTC, phansys commented on lib/Doctrine/ORM/UnitOfWork.php
> +                            if (!isset($subscribedSystems[$entityClass])) {
Please, respect CS.

2017-03-20 03:32 UTC, phansys commented on lib/Doctrine/ORM/UnitOfWork.php
> +                            if ($invoke !== ListenersInvoker::INVOKE_NONE) {
Please, use Yoda condition.

2017-03-20 09:49 UTC, lcobucci commented
@alexgurrola you can rebase the branch and keep the same PR (github plays well with that)... my comments are now on the other PR and you forgot to apply them. Please apply the changes I've asked together with the ones @phansys said.

Also there was a question to @Ocramius regarding the performance impact of these changes.

2017-04-12 18:06 UTC, closed without merging

2017-04-25 06:45 UTC, mwansinck commented
@alexgurrola, I see both your pull request are closed without any merge, I am not sure about the current progress of your improvements, please can you give me an update?

2017-04-26 17:01 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                            if (!isset($subscribedSystems[$entityClass])) {
I'm not entirely sure what this line is violating.  Can you elaborate a bit more?

2017-04-26 17:10 UTC, alexgurrola commented
@mwansinck I set aside a bit of time this morning to address the issues that were present.  A new Pull Request will be available momentarily.