Fix wrong variable name
doctrine/doctrine2 pull request #6356
Opened 2017-03-23 18:14 UTC by gander

Fix $fieldMapping to $embeddedClass in generateEmbeddedPropertyDocBlock
#6314

2017-03-23 18:14 UTC, Ocramius requested changes
Needs tests

2017-03-23 18:18 UTC, gander commented
I am a lama in tests. I'm giving a fix, maybe someone else will do the tests?

2017-03-23 18:19 UTC, Ocramius commented
@gander you just need to create an example that touches this code path - use existing tests as example 👍

2017-04-03 08:43 UTC, gander commented
@Ocramius, I tried to do these unit tests, but they are terribly complicated and I do not know what to duplicate. It is still too difficult for me :(

2017-04-03 08:45 UTC, Ocramius commented
@gander how did you reach the issue? Don't you have some code that triggered the problem?

2017-06-23 10:52 UTC, lcobucci commented
Closing in favor of #6494

2017-06-23 10:52 UTC, closed without merging