This should fix Criteria startsWith and endsWith
doctrine/doctrine2 pull request #6397
Opened 2017-04-13 13:37 UTC by svycka

using like this:
```php
$criteria = Criteria::create();
//$criteria->andWhere(Criteria::expr()->contains("appName", 'a'));
$criteria->andWhere(Criteria::expr()->startsWith("group", 'doct'));
$repository->matching($criteria);
```
```sql
# before
SELECT ... FROM app_data t0 WHERE t0.`group`
# after
SELECT ... FROM app_data t0 WHERE t0.`group` LIKE ?
```
and exception if more than one expression:

> An exception occurred while executing 'SELECT ... FROM app_data t0 WHERE (t0.appName LIKE ? AND t0.`group` )' with params ["%a%", "doct"]:
> 
> SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

2017-04-13 14:19 UTC, svycka commented
not sure why tests failing. Maybe travis caching issue?

2017-04-13 14:48 UTC, lcobucci commented
@svycka that's just weird but I restarted the job, let's wait and see 😉

2017-04-13 15:02 UTC, lcobucci commented
@svycka I just cloned you branch and ran the tests after running `composer update --prefer-lowest` and the test suite is broken, can you please investigate the reason?

2017-04-13 15:12 UTC, svycka commented
@lcobucci found the reason its because startsWith and endsWwith were introduced in doctrine/collection:1.4.0 https://github.com/doctrine/collections/pull/78 hmm not sure what to do :) require ^1.4 :D

2017-04-13 15:22 UTC, lcobucci commented
@svycka feel free to bump up the dependency

2017-04-13 15:31 UTC, lcobucci commented
@svycka I labelled it as `New Feature` since it adds support for the new `ExpressionBuilder` methods and will get it reviewed ASAP.

Thanks for you collaboration 😉

2017-04-14 19:53 UTC, phansys requested changes
Status: Needs work.

2017-04-14 19:53 UTC, phansys commented on tests/Doctrine/Tests/ORM/Functional/EntityRepositoryTest.php
> +        $this->assertEquals(0, count($users));
Please, use `assertCount()` instead.

2017-04-30 11:34 UTC, lcobucci commented
@svycka manually merged on a557c97a93adc1c7c0232e78290cce842a92a6bd thanks for contributing!

2017-04-30 11:34 UTC, closed without merging