Fix quoting issues related to ticket #6402
doctrine/doctrine2 pull request #6404
Opened 2017-04-18 17:46 UTC by lemartin

Apply quoting strategy to foreign key columns of one-to-one relation so
that correct select statements are generated. And use unquoted column
names in result mapping instead of quoted ones, as consumers (namely
IdentifierFlattener) expect unquoted column names.

2017-04-19 10:54 UTC, lemartin commented
Is there any way to rerun the Travis CI build? The mariadb problem looks to me like a transient error.

2017-04-19 13:10 UTC, lcobucci commented
@lemartin restarted, I'll also review your PR in a few hours ;)

2017-04-24 09:05 UTC, lcobucci requested changes
After restarting the job twice it passed (quite odd tbh).
Besides of these small things it LGTM, any comment @Ocramius

2017-04-24 17:48 UTC, phansys requested changes
Status: Needs work.

2017-04-24 17:54 UTC, phansys approved these changes

2017-04-24 17:54 UTC, lemartin commented
Thanks for the reviews, sorry for spamming Travis.

2017-04-30 14:00 UTC, lcobucci commented
@lemartin manually merged on 7c6c5d87c82ad3bb1b4987f65f5201a99cede2d2 talking with @Ocramius we decided to keep in `v2.6.x` only since it depends on the cleanup [made by @guilhermeblanco](https://github.com/doctrine/doctrine2/commit/843966ac50d216b7c55e9f5fde7441fbf25dad57#diff-0c8825d1265a66bb8b20f3d99c276961R758) ages ago.

2017-04-30 14:00 UTC, closed without merging

2017-05-02 07:42 UTC, Ocramius commented
Handled in #6416