"Notice: Undefined offset: 0" when there is no ID Column defined
doctrine/doctrine2 pull request #6412
Opened 2017-04-25 09:02 UTC by JarJak

When you forget about defining the ID/PK Column, then this ugly Notice appear.

This PR is not ready for merge, but shows where the problem exist.

Could you fix this or tell me the way this Pull Request would be acceptable? Thanks.

2017-04-25 09:17 UTC, Ocramius commented
@JarJak metadata without identifier isn't really valid metadata - is this for an embeddable? Can a test be added?

2017-04-25 14:23 UTC, JarJak commented
@Ocramius I agree that metadata without identifier is invalid, however if you throw nice Exception than this Notice, then this mistake would be much easier to debug and fix.

I will add test later.

2017-04-27 19:26 UTC, JarJak commented
@Ocramius I've updated PR with two nearly identical tests (I don't know where exactly I should put my test). However this change might be a BC Break if someone has error reporting turned off (previously it would silently fail instead of throwing exception).

2017-04-29 10:57 UTC, lcobucci requested changes

2017-04-29 10:57 UTC, lcobucci commented on lib/Doctrine/ORM/Mapping/MappingException.php
> +        return new self('No ID defined for entity '.$entity);
Please add spaces before and after the concatenation operator (`'No ID defined for entity ' . $entity`)

2017-04-29 10:57 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6412Test.php
> +class DDC6412Test extends OrmTestCase
I'd say it's better to leave this check in `ClassMetadataTest.php` only, then we keep it together with the other mapping assertions

2017-04-29 11:01 UTC, lcobucci commented on lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
> +        if ( ! isset($this->identifier[0])) {
Can you also mention this change in the docblock? We currently have `@throws MappingException If the class has a composite primary key.` but would be good to say something like `@throws MappingException If the class doesn't have an identifier or it has a composite primary key.`

2017-04-29 11:02 UTC, lcobucci commented
> This change might be a BC Break if someone has error reporting turned off

@JarJak It's not really considered a BC Break since we already expected that type of exception. It was actually something that we missed. Thanks for addressing it 😉

2017-04-29 15:05 UTC, JarJak commented
@lcobucci I polished the code according to your tips, thanks :)

2017-04-29 17:43 UTC, JarJak commented on lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
> +        if ( ! isset($this->identifier[0])) {
done

2017-04-30 09:36 UTC, lcobucci approved these changes
LGTM I'll just rebase the branch, remove the methods in the sample entity (since they're not needed) and merge it. Basically nitpicking 😜

Thanks @JarJak

2017-04-30 09:40 UTC, lcobucci commented
Merged manually in 38bfcc6a7ad264b880b847b69cafa10e3df5cf5d. @Ocramius should we backport this to 2.5.x?

2017-04-30 09:40 UTC, closed without merging

2017-05-02 09:09 UTC, Ocramius commented
@lcobucci no, I think this is fine with `2.6.0`-only