onFlush and postFlush Entity Listeners
doctrine/doctrine2 pull request #6414
Opened 2017-04-26 17:10 UTC by alexgurrola

Simply check if an onFlush or postFlush entity listener is subscribed
for the current class in the entity manager during dispatch.

This is a followup to #6345, #5822, and #5582.

2017-04-26 21:23 UTC, theofidry commented on lib/Doctrine/ORM/UnitOfWork.php
> +                            if (ListenersInvoker::INVOKE_NONE !== $invoke) {
doing early returns here would avoid to go to 6 levels of nesting

2017-04-26 21:23 UTC, theofidry commented
It missing some tests as well and it would be nice to check the performance impact as well.

2017-04-26 23:54 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                            if (ListenersInvoker::INVOKE_NONE !== $invoke) {
Wouldn't a return close the function and not allow it to continue to the next Entity Listener?

2017-04-27 11:01 UTC, theofidry commented on lib/Doctrine/ORM/UnitOfWork.php
> +                            if (ListenersInvoker::INVOKE_NONE !== $invoke) {
`continue`* (same idea)

2017-04-27 15:57 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                            if (ListenersInvoker::INVOKE_NONE !== $invoke) {
I added all the continues rather than the nested if statements.

2017-04-29 10:27 UTC, lcobucci requested changes
Please extract some methods to make the code more readable, the `UnitOfWork` is already a mess...

Obviously we need tests we also need to check the performance impact (@guilhermeblanco and @Ocramius are the best ones to say something regarding that).

And finally, as I asked before, please **stop creating new PRs for the same thing**, just rebase your branch. What your doing doesn't help the review, in fact it makes it more difficult since we have to check more than one place to track all the review comments.

2017-04-29 10:27 UTC, lcobucci commented on lib/Doctrine/ORM/UnitOfWork.php
> +                if (!isset($this->identityMap[$className][$hash])) {
CS not followed https://github.com/doctrine/doctrine2/blob/master/CONTRIBUTING.md#coding-standard

2017-04-29 10:27 UTC, lcobucci commented on lib/Doctrine/ORM/UnitOfWork.php
> +                if (!isset($subscribedSystems[$entityClass])) {
CS not followed https://github.com/doctrine/doctrine2/blob/master/CONTRIBUTING.md#coding-standard

2017-04-30 11:09 UTC, ostrolucky requested changes
Stopped the further review because as I read further, I now doubt this actually works. Needs tests definitely.

2017-05-01 16:46 UTC, alexgurrola commented
@lcobucci When I tried to rebase the last Pull Request, it wouldn't let me push to the repo, and the other one that did messed up all the commits in the log, so I had to delete the branch to recreate it, which ended up closing the Pull Request.

2017-05-01 16:48 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                $hash = (string) $hash;
I was having problems with the tests trying to pass in Objects as IDs, so I implemented the Type Cast to pass said tests.

2017-05-01 16:57 UTC, alexgurrola commented
@ostrolucky This pull request is the only reason we maintain a fork at https://github.com/Sitetheory/doctrine2 for composer to get these features on our web servers, which do require such functionality to correctly time various sets of business logic, and have worked perfectly fine with our fork for over a year.  That said, I'm certain there are better ways of providing this level of functionality, but as @lcobucci stated, the `UnitOfWork.php` is already a mess, so this sort of implementation has become quite difficult for us to build, maintain, and optimize without said expertise in this particular file.

2017-05-01 17:02 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                $hash = (isset($this->entityIdentifiers[$oid], $this->entityIdentifiers[$oid]['id'])) ? $this->entityIdentifiers[$oid]['id'] : null;
I may have some time later today or tomorrow to give you a better answer than this one, but the main reason that I was using the nested `foreach` loop was due to an attempt at creating logic similar to that of the other Entity Listeners, but on the `onFlush` and `postFlush` events, which do not digest each entity as easily as the other events, which can piggyback off the loops already available.

2017-05-01 17:15 UTC, lcobucci commented
> @lcobucci When I tried to rebase the last Pull Request, it wouldn't let me push to the repo, and the other one that did messed up all the commits in the log, so I had to delete the branch to recreate it, which ended up closing the Pull Request.

@alexgurrola I'm sorry if what I said was a bit harsh, I didn't mean to be rude.

Since you didn't say the reason why you open/closed PRs for the same thing I understood it was your way to do (and it was really confusing for me). So if you need help regarding rebase let us know, we can help you on that 😉.

2017-05-30 21:42 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                if (!isset($this->identityMap[$className][$hash])) {
@lcobucci Good eye.  I fixed the spacing there.

2017-05-30 21:42 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                if (!isset($subscribedSystems[$entityClass])) {
@lcobucci I fixed the spacing here as well.

2017-05-30 22:58 UTC, alexgurrola commented on lib/Doctrine/ORM/UnitOfWork.php
> +                $hash = (isset($this->entityIdentifiers[$oid], $this->entityIdentifiers[$oid]['id'])) ? $this->entityIdentifiers[$oid]['id'] : null;
@ostrolucky I've addressed all of your issues, and it is now much more concise.  👍

2017-05-30 23:02 UTC, alexgurrola commented
I have fixed any CS issues and cut down on the resources utilized by this routine, drastically.  It should now be much more efficient, solid, and easy to maintain in the future.  If you need anything else, let me know.  😄 

Reviewers: @lcobucci @theofidry @ostrolucky @Ocramius

2017-05-30 23:36 UTC, alexgurrola commented
The only check that was unsuccessful seems to be a Travis timeout?

2017-05-31 09:37 UTC, Ocramius commented
@alexgurrola restarted that failed task

2017-06-05 23:34 UTC, alexgurrola commented
@lcobucci Your requested changes are holding the merge back.  Can you review the code and see if it addresses all complaints?

Thanks,
-- Alex

2017-06-05 23:50 UTC, Ocramius requested changes
@alexgurrola tests weren't added: tests describing the change and verifying this new behavior are required

2017-07-28 09:36 UTC, mwansinck commented
Hi @alexgurrola, any progress on this?

2017-09-06 22:29 UTC, alexgurrola commented
@mwansinck This Pull Request was held back due to lack of tests, but I have attempted to put the correct bindings for these new Entity Listener events.  Sadly, rebasing caused me to have to clean the branch and rebuild based on the files altered, thus closing and reopening this Pull Request.

2017-09-06 22:46 UTC, alexgurrola commented
@lcobucci @Ocramius: I attempted to add bindings to the branch for Travis CI, but I'm not sure if I've done something wrong or not.  I don't _really_ understand Travis, so is there some way that I can run some of those checks locally or something?  I'm not really sure how to go forward with the Testing Functionality...  😕

2017-09-07 23:27 UTC, Majkl578 commented
@alexgurrola Travis is failing because there are test failures caused by your changes. You can see the details when you open a single job (normally there are multiple jobs for different PHP versions and RDBMS) and scroll through the log. I.e. here: https://travis-ci.org/doctrine/doctrine2/jobs/272685091#L595 is failure under PHP 7.1 and SQLite.
You can run tests locally simply by running vendor/bin/phpunit, these will run with SQLite by default. To run against different RDBMS, you would need to copy phpunit.xml.dist to phpunit.xml, uncomment and adjust `db_` variables at bottom. I'd suggest to stick with defaults when not testing DB-specific code (not this case) and leave the rest on Travis.

2018-08-09 22:44 UTC, ostrolucky commented
continues in https://github.com/doctrine/doctrine2/pull/7310

2018-08-09 22:44 UTC, closed without merging