Fix expire result cache
doctrine/doctrine2 pull request #6417
Opened 2017-04-30 19:20 UTC by lcobucci

Simplifying test provided in #6390 and process the result set cache eviction when flag was passed.

2017-04-30 19:58 UTC, guilhermeblanco commented on lib/Doctrine/ORM/Query.php
> +                $this->_queryCacheProfile->generateCacheKeys($executor->getSqlStatements(), $sqlParams, $types)[0]
If this is a list, iterate over it (even though now it only returns one item) and delete each record.

2017-04-30 20:00 UTC, lcobucci commented on lib/Doctrine/ORM/Query.php
> +                $this->_queryCacheProfile->generateCacheKeys($executor->getSqlStatements(), $sqlParams, $types)[0]
I thought that but although the docblock says it returns an `array` it's actually a string 😱

2017-05-02 07:48 UTC, Ocramius requested changes

2017-05-02 07:48 UTC, Ocramius commented on tests/Doctrine/Tests/OrmFunctionalTestCase.php
> +        if (is_null(self::$_resultCacheImpl)) {
`null ===`

2017-05-02 07:48 UTC, Ocramius commented on tests/Doctrine/Tests/OrmFunctionalTestCase.php
> +    private static $_resultCacheImpl = null;
If we introduce new properties, we shouldn't use the prefix... Also, the fact that this is a static smells a lot: what if it is accidentally not unset between test cycles? Is it supposed to always be set?

2017-05-02 07:48 UTC, Ocramius commented on lib/Doctrine/ORM/Query.php
> +        foreach ((array) $executor->getSqlStatements() as $statement) {
Why the `(array)` cast? Smelly :|

2017-05-02 07:48 UTC, Ocramius commented on lib/Doctrine/ORM/Query.php
> +            $cacheDriver->delete($this->_queryCacheProfile->generateCacheKeys($statement, $sqlParams, $types)[0]);
That `[0]` is also a bit smelly

2017-05-02 07:48 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +    public function __toString()
We can start violently adding type hints everywhere

2017-05-02 07:48 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +    public function __construct($brand)
We can start violently adding type hints everywhere

2017-05-02 07:48 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +class GH2947Test extends OrmFunctionalTestCase
Do we have a `Query`-specific test that we can use here?

2017-05-02 08:25 UTC, lcobucci commented on lib/Doctrine/ORM/Query.php
> +        foreach ((array) $executor->getSqlStatements() as $statement) {
It's indeed... cause: https://github.com/doctrine/doctrine2/pull/6417#discussion_r114082839

2017-05-02 08:26 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +    public function __construct($brand)
except for `: void` 😭

2017-05-02 08:27 UTC, Ocramius commented on lib/Doctrine/ORM/Query.php
> +        foreach ((array) $executor->getSqlStatements() as $statement) {
@lcobucci can you add that as a comment in the code?

2017-05-02 08:29 UTC, lcobucci commented on lib/Doctrine/ORM/Query.php
> +        foreach ((array) $executor->getSqlStatements() as $statement) {
Sure 😉

2017-05-02 08:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +    public function __construct($brand)
@lcobucci bump it

2017-05-02 08:35 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +class GH2947Test extends OrmFunctionalTestCase
As in a unit test?

2017-05-02 08:37 UTC, lcobucci commented on lib/Doctrine/ORM/Query.php
> +            $cacheDriver->delete($this->_queryCacheProfile->generateCacheKeys($statement, $sqlParams, $types)[0]);
What do you suggest? `first()`? `list()`?

2017-05-02 09:07 UTC, Ocramius commented on lib/Doctrine/ORM/Query.php
> +            $cacheDriver->delete($this->_queryCacheProfile->generateCacheKeys($statement, $sqlParams, $types)[0]);
`reset()` or similar works fine

2017-05-02 20:40 UTC, lcobucci commented on tests/Doctrine/Tests/OrmFunctionalTestCase.php
> +    private static $_resultCacheImpl = null;
True thing, I'll keep it non-static and leave the instantiation to the test that actually uses it. Thanks

2017-05-02 21:28 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +class GH2947Test extends OrmFunctionalTestCase
[`Doctrine\Tests\ORM\Query\QueryTest#testResultCacheEviction()`](https://github.com/doctrine/doctrine2/pull/6417/files#diff-8839a19e4228e39f37c3000d51e43beeR250) not strictly unit test though but should be enough 😉

2017-05-03 10:40 UTC, Ocramius approved these changes

2017-05-03 10:40 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH2947Test.php
> +class GH2947Test extends OrmFunctionalTestCase
Thanks for adding these :-)

2017-05-03 10:40 UTC, merged

2017-05-03 10:40 UTC, Ocramius commented
@lcobucci :ship: \o/

2017-05-03 10:47 UTC, lcobucci commented
@Ocramius awesome thanks!