remove loosely comparison
doctrine/doctrine2 pull request #6441
Opened 2017-05-15 05:22 UTC by sensorario

The expression $this->fileLockRegionDirectory of type string|null is loosely compared to false; this is ambiguous if the string can be empty. You might want to explicitly use === null instead.

2017-05-16 12:51 UTC, Ocramius requested changes

2017-05-16 12:51 UTC, Ocramius commented on lib/Doctrine/ORM/Cache/DefaultCacheFactory.php
> +            if ( null === $this->fileLockRegionDirectory) {
Space before should be removed

2017-05-18 15:33 UTC, phansys commented
@sensorario, could you please add a test in order to avoid regressions related to this change?

2017-08-18 02:38 UTC, Ocramius approved these changes
Looking good! :ship:

2017-08-18 02:38 UTC, merged