Fix #6460 - \Doctrine\ORM\Mapping\ClassMetadataInfo::hasField should return true for embedded fields
doctrine/doctrine2 pull request #6462
Opened 2017-05-22 12:45 UTC by mkosiedowski

This fixes https://github.com/doctrine/doctrine2/issues/6460

2017-05-22 13:29 UTC, Ocramius requested changes

2017-05-22 13:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        } catch (\Exception $e) {
Please only catch schemaexception

2017-05-22 13:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $this->assertTrue($isFieldMapped);
This test should probably be on the class metadata tests

2017-05-22 13:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $this->assertNotNull($proxy->lazyLoaded->embedded);
Please use `self::assertInstanceOf()`

2017-05-22 13:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $this->_em->flush();
Why two flush operations?

2017-05-22 13:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $proxy = $this->_em->getRepository(DDC6460ParentEntity::class)->findOneById(1);
This is not a proxy here: please add assertions to verify if it is a proxy, and if it is loaded

2017-05-22 13:29 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $this->assertNotNull($proxy->lazyLoaded->embedded);
I would also check the value of `field` after this call

2017-05-22 13:52 UTC, mkosiedowski commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $this->assertTrue($isFieldMapped);
I've added similar test there

2017-05-22 13:53 UTC, mkosiedowski commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $this->_em->flush();
I've added cascade persist in order to remove one flush

2017-06-01 13:50 UTC, Ocramius approved these changes

2017-06-01 13:50 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/DDC6460Test.php
> +        $this->_em->flush();
Thanks!

2017-06-01 13:51 UTC, Ocramius commented
LGTM! :+1: 

Note that I'm not changing this for `2.5.x`, because there's a subtle behavioral change when this API is used when looping over fields. It will land in `2.6.0`

2017-06-01 13:52 UTC, merged