Fixes #5804
doctrine/doctrine2 pull request #6485
Opened 2017-06-05 09:51 UTC by alle

This PR fixes #5804.
It's not a my own solution, but the one provided by @ngrevet-lightspeed.
Since I need this fixed, I made this PR on behalf of @ngrevet-lightspeed.

2017-06-05 15:09 UTC, Ocramius requested changes
@alle the patch needs tests to be validated

2017-06-06 15:51 UTC, alle commented
@Ocramius @ngrevet-lightspeed Everything should be fine, now. I was too hurried, last time. Sorry.

2017-06-06 15:59 UTC, Ocramius commented
@alle I still don't see test changes though :-\

2017-06-06 16:11 UTC, alle commented
@Ocramius Well, I thought tests shouldn't change, should they?
I thought I fixed this bug, working on the `BasicEntityPersister::fetchVersionValue()` method, by passing the involved tests, without changing them. Humbly, am I missing something?

2017-06-06 16:13 UTC, Ocramius commented
@alle a test demonstrating the original bug (failing with the original repository state, passing with this patch) is needed ;-)

2017-06-12 14:03 UTC, alle commented
@ocramius: @astepin did the job (in #6496) that I should have done from myself.
@astepin The only change I made is in the custom type `getSQLDeclaration()` method: your version was failing against the Postgres platform, since Doctrine maps to a specific datatype for that platform.

2017-06-14 14:55 UTC, alle commented
I changed the involved classes in tests, complying to other tests' structure, in order to avoid a merge conflict on the `SchemaValidatorTest`, due to recent updates

2017-06-20 05:16 UTC, lcobucci commented on lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
> +            foreach ($this->getTypes($field, $value, $versionedClass) as $type) {
Do we need to iterate this too? I mean in theory we could use `array_merge()` right, like:

```php
$types = [];

foreach ($id as $field => $value) {
    $types = array_merge($types, $this->getTypes($field, $value, $versionedClass));
}
```

2017-06-20 07:26 UTC, alle commented on lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
> +            foreach ($this->getTypes($field, $value, $versionedClass) as $type) {
@lcobucci You're simply right.

2017-07-06 09:23 UTC, alle commented
@Ocramius @lcobucci Is there any possibility to have this PR merged? I didn't see any news since the last changes.

2017-07-06 12:00 UTC, alcaeus commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +    ")
Syntax error ;)

2017-07-06 12:00 UTC, alcaeus commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +     * @CustomIdGenerator(class="\Doctrine\Tests\Models\GH5804\GH5804Generator")
Could/Should use `::class` constant

2017-07-06 13:21 UTC, alle commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +    ")
Aaargh! Didn't see that!

2017-07-06 13:21 UTC, alle commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +     * @CustomIdGenerator(class="\Doctrine\Tests\Models\GH5804\GH5804Generator")
In which form? Any example?

2017-07-06 13:30 UTC, alcaeus commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +     * @CustomIdGenerator(class="\Doctrine\Tests\Models\GH5804\GH5804Generator")
Paired with a `use` statement: `@CustomIdGenerator(class=GH5804Generator::class)`. Works with Annotations >= 1.2 IIRC.

2017-07-06 14:57 UTC, alle commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +     * @CustomIdGenerator(class="\Doctrine\Tests\Models\GH5804\GH5804Generator")
I guessed it was that way, but my local tests fail. I even update merged with the latest `master` release, updated the dependencies (my Annotations version was right, anyway), but your suggestion (which seems to be logical) doesn't work to me. Did you try by yourself?
Anyway, even without that `::class` notation, everything is fine.

2017-07-06 14:58 UTC, alcaeus commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +     * @CustomIdGenerator(class="\Doctrine\Tests\Models\GH5804\GH5804Generator")
That's strange. I've been using that for a couple of years now.

2017-07-22 18:50 UTC, lcobucci commented
I'll take a look at this in a bit

2017-07-22 20:22 UTC, lcobucci commented on tests/Doctrine/Tests/Models/GH5804/GH5804Article.php
> +     * @CustomIdGenerator(class="\Doctrine\Tests\Models\GH5804\GH5804Generator")
It requires the FQCN, just that 😉

2017-07-22 20:30 UTC, lcobucci commented
@alle thanks for your contribution, I've simplified things a bit (kept all test related classes together).

@Ocramius it LGTM, can you check this one to see if we're good to go?

2017-07-22 20:30 UTC, lcobucci approved these changes

2017-07-22 20:36 UTC, Ocramius approved these changes
Some nitpicks apply

2017-07-22 20:36 UTC, Ocramius commented on lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php
> +        $types = [];
Can this block be moved to a private method?

2017-07-22 20:36 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH5804Test.php
> +    /**
Spacing

2017-07-22 20:36 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH5804Test.php
> + * @Table(name="gh5804_articles")
Not really needed

2017-07-22 21:29 UTC, merged

2017-07-22 21:29 UTC, lcobucci commented
@alle 🚢 thanks!

2017-07-24 08:09 UTC, alle commented
Thank you so much, guys!
This was my first opportunity to contribute to this project, even to "calibrate" myself to future contributions. Or at least I hope so!