Add failing test for #6314  and PR #6356
doctrine/doctrine2 pull request #6494
Opened 2017-06-08 21:23 UTC by astepin

This is a failing test for issue #6314 in addition to fix in PR #6356 .

2017-06-09 08:03 UTC, Ocramius requested changes

2017-06-09 08:03 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
> +        $needle = sprintf('@Embedded(class="%s", columnPrefix=\'%s\')', $testMetadata->name,'prefix');
Fairly sure that we don't use single quotes on any annotations (see `columnPrefix`)

2017-06-09 08:03 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
> +        self::assertContains($needle, $docComment);
I see [from the test runs](https://travis-ci.org/doctrine/doctrine2/jobs/240964836#L342) that this is the only failing bit: a fix should be easy to provide now :-)

2017-06-09 08:03 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
> +
Remove this empty line

2017-06-09 08:03 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
> +
Remove this empty line

2017-06-09 08:03 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/EntityGeneratorTest.php
> +        $isbnMetadata = $this->generateIsbnEmbeddableFixture(['testEmbedded' => $testMetadata], 'prefix');
Please use a random value for the prefix passed in here - makes it harder to escape checks

2017-06-09 20:32 UTC, astepin commented
I had to merge PR #6356 to my PR in order to solve another issue i've discovered. 
As described [here](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html#column-prefixing), columnPrefix could be a string or a boolean.This has an impact on the generation of this annotation. I've fixed this and added appropriet tests.

2017-06-23 10:54 UTC, Ocramius commented
LGTM :+1:

2017-06-23 10:54 UTC, merged

2017-06-23 10:54 UTC, Ocramius commented
Thanks @astepin, sorry for the late feedback :-)