Throw exception when APCu cache is used by cli commands
doctrine/doctrine2 pull request #6498
Opened 2017-06-12 07:32 UTC by tommyseus

It isn't possible to access the APCu cache (same behaviour as APC and XCache) from cli.
The commands (MetadataCommand, QueryCommand and ResultCommand) don't throw an exception when APCu cache is used.

**Changes**
- Created a AbstractCommand with one method to check the $cacheDriver and throws a \LogicException for APC, APCu and XCache.
- Created unittests for MetadataCommand, QueryCommand and ResultCommand.
- Moved RegionCache unittests to the corresponding namespace.

2017-06-12 07:35 UTC, Ocramius requested changes

2017-06-12 07:35 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Console/Command/ClearCache/AbstractCommand.php
> +        } elseif ($cacheDriver instanceof Cache\ApcuCache) {
There's no need for the `else` keyword anywhere here

2017-06-12 07:35 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Console/Command/ClearCache/AbstractCommand.php
> +        if (isset($name)) {
Instead of checking for a variable existence, make a private method that throws the exception

2017-06-12 07:35 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Console/Command/ClearCache/AbstractCommand.php
> +    protected function checkCacheDriverType($cacheDriver)
This can be a public static utility: inheritance is not needed

2017-06-12 07:35 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Console/Command/ClearCache/MetadataCommand.php
> +        $this->checkCacheDriverType($cacheDriver);
`assertCacheDriverAllowsClearingInConsole()` maybe?

2017-06-13 05:02 UTC, lcobucci commented
@tommyseus @Ocramius does it make sense to move the validation to the method that ensures production settings? I think it would be better to keep these things together.

2017-06-13 11:59 UTC, Ocramius commented
> does it make sense to move the validation to the method that ensures production settings?

These commands are unrelated to that though...

2017-06-13 12:56 UTC, lcobucci commented
>These commands are unrelated to that though... 

Yeah I know, I'm just saying that I think it's more logical to check the cache driver as part of the production settings checking and thus making users responsible for following our suggestions or not (and dealing with the consequences of that decision).

That reduces the amount of changes we need to do and brings the responsibility to the correct hands. I mean, we don't have control on how people decide to use the ORM (and that's why we can't solve all N+1 errors).

I'm fine on going on with this path but my intention is more to "educate" people to use the correct stuff. If we decide to proceed with this implementation we should also add it to L2C commands and also add `ArrayCache` to the list (since it simply doesn't need to be cleaned).

2025-01-19 03:05 UTC, closed without merging