Allow internal functions to be overridden.
doctrine/doctrine2 pull request #6500
Opened 2017-06-13 09:19 UTC by ThePixelDeveloper

Background
------------

This came about because we're writing a driver for [PrestoDB](https://prestodb.io) and wanted to implement windowing for the aggregate functions. This is fine for anything new, but we struggled when trying to add windowing support for count, avg, etc ... 

> All Aggregate Functions can be used as window functions by adding the OVER clause. The aggregate function is computed for each row over the rows within the current row’s window frame.

Source: [6.15. Window Functions — Presto 0.178 Documentation](https://prestodb.io/docs/current/functions/window.html)

Solution
--------

Obvious solution for us was to have the ability to override the internal aggregate functions. We also moved the internal aggregate functions into the `$_NUMERIC_FUNCTIONS` property so they can be overridden; They were handled in a special manner before.

The only part we weren't sure of was the `dctrn` alias used: https://github.com/SamKnows/doctrine2/pull/1/files#diff-0c8825d1265a66bb8b20f3d99c276961 

If that doesn't matter and we can go with `sclr`, then this is another path that can be removed.

Thoughts? 

PS. First big PR for the Doctrine internals 👍

2017-06-13 11:53 UTC, Ocramius commented
Overall, this removes the internal and non-internal functions separation, which is quite an improvement.

I'm not sure if I'd like folks to override stuff like `MAX` or `AVG` though: lots of space for hurting yourself there... Also, the `SqlWalker` still treats them as "special" via `instanceof` checks, so it's not like they became reusable or replaceable anyway...

2017-06-14 13:19 UTC, ThePixelDeveloper commented
> Also, the SqlWalker still treats them as "special" via instanceof checks, so it's not like they became reusable or replaceable anyway...

The only reason there's a case in SqlWalker is because of the `dctrn` alias. I didn't know if it had special meaning within Doctrine. If it doesn't, I'll remove that case statement and let it be handled by the one below it.

> I'm not sure if I'd like folks to override stuff like MAX or AVG though: lots of space for hurting yourself there...

I'm not sure I agree, there's plenty of other places to shoot yourself in the foot already. Custom SQL Walkers allow us to rewrite the output SQL in ways that don't relate to the SQL we write.

I'd rather have a clean / consistent way to override functionality. Before I came up with this solution I was trying to think of alternatives via custom SQL Walkers, which would have been far more magical. At least with this I can look for a DQL function with the key `count` and see what the new logic is.

2017-06-19 00:36 UTC, Ocramius commented
Just a note here: patch looks very much clean and IMO it should be merged, but I'd like to have @beberlei, @guilhermeblanco and @lcobucci look at it first.

2017-06-19 01:07 UTC, guilhermeblanco commented
LGTM.

2017-06-19 01:46 UTC, Ocramius requested changes

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/ORMException.php
> -    public static function overwriteInternalDQLFunctionNotAllowed($functionName)
This method removal is effectively a BC break, and while it is an internal method, it should be documented in `UPGRADE.md`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Configuration.php
> -        if (Query\Parser::isInternalFunction($name)) {
`@throws` in docblock needs to be removed

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Configuration.php
> -        if (Query\Parser::isInternalFunction($name)) {
`@throws` in docblock needs to be removed

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Configuration.php
> -        if (Query\Parser::isInternalFunction($name)) {
`@throws` in docblock needs to be removed

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/AvgFunction.php
> +    public $aggregateExpression;
Can this be made `private`?

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/AvgFunction.php
> +    public function getSql(SqlWalker $sqlWalker)
Add a return type

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/AvgFunction.php
> +    public function parse(Parser $parser)
Add ` : void`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/CountFunction.php
> +    public $aggregateExpression;
Make it `private`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/CountFunction.php
> +    public function getSql(SqlWalker $sqlWalker)
add ` : string`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/CountFunction.php
> +    public function parse(Parser $parser)
Add ` : void`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MaxFunction.php
> +    public $aggregateExpression;
`private`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MaxFunction.php
> +    public function getSql(SqlWalker $sqlWalker)
` : string`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MaxFunction.php
> +    public function parse(Parser $parser)
` : void`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MinFunction.php
> +    public $aggregateExpression;
`private`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/AvgFunction.php
> + * @since   2.0
`2.6`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/CountFunction.php
> + * @since   2.0
`2.6`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MaxFunction.php
> + * @since   2.0
`2.6`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MinFunction.php
> + * @since   2.0
`2.6`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/SumFunction.php
> + * @since   2.0
`2.6`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/SumFunction.php
> + * @link    www.doctrine-project.org
remove

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MinFunction.php
> + * @link    www.doctrine-project.org
remove

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/MaxFunction.php
> + * @link    www.doctrine-project.org
remove

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/CountFunction.php
> + * @link    www.doctrine-project.org
remove

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/AvgFunction.php
> + * @link    www.doctrine-project.org
remove

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/SumFunction.php
> +    public $aggregateExpression;
`private`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/SumFunction.php
> +    public function getSql(SqlWalker $sqlWalker)
` : string`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/SumFunction.php
> +    public function parse(Parser $parser)
` : void`

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/Parser.php
> -    static public function isInternalFunction($functionName)
This method removal is potentially a BC break, and it needs to be documented in `UPGRADE.md` even though this is internal API

2017-06-19 01:46 UTC, Ocramius commented on lib/Doctrine/ORM/Query/SqlWalker.php
> +            case ($expr instanceof AST\Functions\AvgFunction):
Since custom expressions are allowed, why not simply checking against `$expr instanceof FunctionNode`? Any reason why that wasn't done?

2017-06-19 01:46 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/CustomFunctionsTest.php
> +    public function parse(Parser $parser)
Add return hints

2017-06-19 01:46 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/CustomFunctionsTest.php
> +    public function getSql(SqlWalker $sqlWalker)
Add return hints

2017-06-19 09:09 UTC, ThePixelDeveloper commented
@Ocramius Think I've covered everything, although are you sure you want to have void return types? Just making sure. Tests are failing because of that reason alone.

2017-06-19 09:24 UTC, lcobucci commented
@ThePixelDeveloper @Ocramius tests are failing because these changes depends on #6507. I'll review your PR now 😉

2017-06-19 09:37 UTC, lcobucci requested changes
Besides that it LGTM

2017-06-19 09:37 UTC, lcobucci commented on lib/Doctrine/ORM/Query/AST/Functions/AvgFunction.php
> +class AvgFunction extends FunctionNode
Since it's brand new class we can make it final, right?

2017-06-19 09:37 UTC, lcobucci commented on lib/Doctrine/ORM/Query/AST/Functions/CountFunction.php
> +class CountFunction extends FunctionNode
Since it's brand new class we can make it final, right?

2017-06-19 09:37 UTC, lcobucci commented on lib/Doctrine/ORM/Query/AST/Functions/MaxFunction.php
> +class MaxFunction extends FunctionNode
Since it's brand new class we can make it final, right?

2017-06-19 09:37 UTC, lcobucci commented on lib/Doctrine/ORM/Query/AST/Functions/MinFunction.php
> +class MinFunction extends FunctionNode
Since it's brand new class we can make it final, right?

2017-06-19 09:37 UTC, lcobucci commented on lib/Doctrine/ORM/Query/AST/Functions/SumFunction.php
> +class SumFunction extends FunctionNode
Since it's brand new class we can make it final, right?

2017-06-19 10:12 UTC, ThePixelDeveloper commented
@lcobucci Agreed, updated.

2017-06-20 05:19 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/AvgFunction.php
> +class AvgFunction extends FunctionNode
Yup, they should all be `final` if they are new.

2017-06-20 05:28 UTC, lcobucci approved these changes

2017-06-20 05:28 UTC, lcobucci commented
@Ocramius @ThePixelDeveloper I've just rebased the branch to sync with `master` and I think it's good to go.

2017-06-20 05:29 UTC, Ocramius approved these changes

2017-06-20 05:29 UTC, merged

2017-06-20 05:30 UTC, Ocramius commented
@lcobucci seen, :shipit: