Update Generation way of the options
doctrine/doctrine2 pull request #6530
Opened 2017-06-27 15:48 UTC by PyRowMan

When the options array was created, only the unsigned value were setted.

2017-06-28 04:27 UTC, Ocramius commented
Misses test cases, plus the additional conditionals should be stashed in a separate private method.

2017-06-28 08:02 UTC, PyRowMan commented
I updated the code, and put it into a function, but i'm not the best at doing tests and i currently cannot test them on my machine.

If someone could do them for me, it would be much appreciated :)

2017-06-28 09:29 UTC, PyRowMan commented
There still is a bug with the comments with double quotes, even escaping them doesn't work. for myself i replaced them all with simple quotes, but it's a solution only for my projet, not for long therm.

2017-07-12 07:58 UTC, Ocramius commented
> I updated the code, and put it into a function, but i'm not the best at doing tests and i currently cannot test them on my machine.

Travis can test things for you. Also, read https://github.com/doctrine/doctrine2/blob/e3ecec36ad77525553bfd4e6a2ec86e80d39ac27/CONTRIBUTING.md#unit-tests please :-)

2017-12-08 02:46 UTC, Majkl578 requested changes
Just found this months old unsent review. :)
Please also add tests.

2017-12-17 01:58 UTC, Majkl578 commented
I'm going to close this PR as we will be removing EntityGenerator in Doctrine 3.0 completely and 2.x is closed feature-wise. Thank you for the PR.

2017-12-17 01:58 UTC, closed without merging

2017-12-17 02:12 UTC, PyRowMan commented
Yeah, I completely forgot to update theses :/


Sorry for that.