[master] PHPStan integration - levels 0 + 1
doctrine/doctrine2 pull request #6535
Opened 2017-06-29 21:55 UTC by Majkl578

Based on #6440, rebased & moved from composer.json to .travis.yml (to be installed only during CI builds). Fixed `lib/` for levels 0 & 1.

I don't like the changes for level 1 though. Some of the changes shouldn't be even needed - PHPStan limitation reported in https://github.com/phpstan/phpstan/issues/349.

2017-06-29 22:07 UTC, Majkl578 commented
Wow, removal of the `return` from `PersistentCollection#offsetSet()` breaks 26 tests... Well, that is..., unexpected... at least. :)

2017-06-30 07:50 UTC, Ocramius requested changes

2017-06-30 07:50 UTC, Ocramius commented on .travis.yml
> +  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 1 -c phpstan.neon lib; fi
Can we eventually also analyse the tests dir?

2017-06-30 14:03 UTC, Majkl578 commented
@Ocramius Ok, I'll see what could be done there, it won't work out-of-box though...
```
$ vendor/bin/phpstan analyse -l 1 -c phpstan.neon tests/
  19/835 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   2%PHP Fatal error:  Class 'Doctrine\Common\Cli\Tasks\AbstractTask' not found in /www/doctrine/doctrine2/tests/Doctrine/Tests/Mocks/TaskMock.php on line 12
```

2017-06-30 15:19 UTC, Majkl578 commented
Damn, the tests are in a really bad shape, it'll be massive donkey work to improve them and bring at bring at level 1 (or 0 at least). It's over 150 issues even for level 0, over 300 for level 1.
Fixed some of them, but manywill require more than just simply fixing a type (i.e. dependencies between test files, undefined `::class` references etc.). 😞

2017-06-30 21:01 UTC, Ocramius commented
@Majkl578 then let's skip it for now.

2017-07-06 22:30 UTC, Majkl578 commented
@Ocramius Can we merge this then? Or anything else?

2017-07-07 08:35 UTC, lcobucci approved these changes

2017-07-07 08:36 UTC, merged

2017-07-07 08:36 UTC, lcobucci commented
@Majkl578 🚢  thanks!