Case insensitive like
doctrine/doctrine2 pull request #6547
Opened 2017-07-11 15:08 UTC by okoehler

This pull request adds Comparison::CONTAINS_CI to create a case insensitive like. 

Existing case sensitive like
`fieldname LIKE %value%`

New case insensitive like
`LOWER(fieldname) LIKE (%value%)`
with value converted to lowercase by php, and fieldname surrounded by platforms lower function. 

UnitTests will run if you use [this version of doctrine collections](https://github.com/okoehler/collections/tree/6de7e7ce5e3b0f5d50b5152366efbb9e721db212). I will create a PR for this too.

2017-07-11 15:19 UTC, Majkl578 requested changes
Needs functional tests.

2017-07-11 15:19 UTC, Majkl578 commented on lib/Doctrine/ORM/Query/QueryExpressionVisitor.php
> +                $parameter->setValue('%' . strtolower($parameter->getValue()) . '%', $parameter->getType());
This should use multibyte safe variant, mb_strtolower.

2017-07-11 15:20 UTC, Majkl578 commented
Maybe `ICONTAINS` would be better naming for this?

2017-07-12 06:29 UTC, mvrhov commented
This will work only on Mysql, postgresql uses ILIKE keyword for that.

2017-07-13 15:04 UTC, okoehler commented
> This will work only on Mysql, postgresql uses ILIKE keyword for that.

I use **LIKE** with left and right value converted to lower for multi platform support:

`LOWER(fieldname) LIKE (%value%)`

2017-07-14 11:58 UTC, tobiasoberrauch commented
This is exactly what I need. I hope this feature will merged as soon a possible. Thank you for contributing @okoehler

2017-07-22 07:22 UTC, Ocramius commented
> `LOWER(fieldname) LIKE (%value%)`

This will disable any kind of index usage, unless the column has an index on `LOWER(fieldname)` (only possible in PostgreSQL and advanced RDBMSs)

2017-08-01 13:13 UTC, tobiasoberrauch commented
@Ocramius What solution what you suggest?
It would be sad if we don't use this PR

2017-08-01 13:25 UTC, Ocramius commented
@tobiasoberrauch I don't have a solution: I just exposed another problem.

2017-08-31 07:49 UTC, okoehler commented
@Ocramius I created this PR to provide a feature which some people are missing. I created tests, it works for all supported databases. Of course there are some possible improvements, which could be created if there is a need for. 
But for now, I think, the benefit is high enough to see this as a first releasable version. So, what do you think, is there any chance to that this PR will be merge?

2017-08-31 07:58 UTC, Ocramius commented
> So, what do you think, is there any chance to that this PR will be merge?

Not until a solution is found here, at least in my opinion. Other @doctrine/doctrinecore folks may disagree.

2018-03-15 10:36 UTC, sschleue commented
In my opinion the usage of indexes is nice to have not mandatory. This (some kind of slow) solution is better than none. Case insensitive like would be a very nice feature. Else you always have to build it on your own which bloats your code and makes it ugly. I think a notice in documentation should be enough to be aware of that performance issue. At least for now.
I highly appreciate this PR.

2025-01-18 03:02 UTC, closed without merging