Fix return value of removeElement for extra lazy collections
doctrine/doctrine2 pull request #6550
Opened 2017-07-13 06:18 UTC by alcaeus

Fixes #5745.

As indicated in the ticket, calling `removeElement` on an uninitialized collection that uses the extra_lazy fetch mode does not return a bool, breaking the contract specified in the collection interface. This PR changes `removeElement` to return a bool value in those cases as well.

2017-07-13 12:52 UTC, Ocramius commented
@alcaeus an additional test for the `false` scenario (that was now removed, it was the `null` scenario) is needed.

The test would basically attempt to call `removeElement()` with a non-existing or unrelated entity.

2017-07-13 12:53 UTC, Ocramius requested changes
@alcaeus an additional test for the `false` scenario (that was now removed, it was the `null` scenario) is needed.

The test would basically attempt to call `removeElement()` with a non-existing or unrelated entity.

2017-07-13 14:39 UTC, alcaeus commented
@Ocramius done!

2017-07-22 07:26 UTC, Ocramius commented
:ship:

2017-07-22 07:26 UTC, merged

2017-07-22 07:28 UTC, Ocramius commented
Backported to `2.5` via doctrine/doctrine2@b3ceef0fb6f822c876571311a5431b771efaab98, thanks!