Entity listeners are now processed by exporters
doctrine/doctrine2 pull request #6593
Opened 2017-08-01 10:15 UTC by tPl0ch

The current implementation of the exporters are not taking the entity
listeners into account. I have added test cases for most of the edge
cases I could think of and implemented the Exporter handling.

This PR originates from https://github.com/doctrine/doctrine2/pull/5864,
I was overwhelmed by the amount of conflicts I had to resolve so I
started anew on a clean master HEAD.

2017-08-03 20:43 UTC, Ocramius requested changes

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/PhpExporter.php
> +                        $entityListener['class'],
Where is this code tested? Can't seem to find it. Also, use `var_export()` instead of single quotes around a `%s`

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
> +            $entityListenerXml = $entityListenersXmlMap[$entityListener['class']];
Use an early return. Swap the negation on the `if` to get rid of the `else` overall

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/YamlExporter.php
> +    private function processEntityListeners(ClassMetadataInfo $metadata, $array)
You can now add return hints (we're on PHP 7.1 ;-) )

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/EntityGenerator.php
> +    protected function generateEntityListenerAnnotation(ClassMetadataInfo $metadata)
Return type

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/PhpExporter.php
> +    private function processEntityListeners(ClassMetadataInfo $metadata, &$lines)
Can you remove the by-ref usage, and instead use `array_merge()` in the caller?

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
> +    private function exportTableOptions(SimpleXMLElement $parentXml, array $options)
Return type to be added, if any

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
> +    private function processEntityListeners(ClassMetadataInfo $metadata, SimpleXMLElement $root)
` : void`

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
> +    private function generateEntityListenerXml(ClassMetadataInfo $metadata, array $entityListenersXmlMap, SimpleXMLElement $entityListenersXml)
` : void`. You can also remove docblocks that are redundant to the type declarations.

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/XmlExporter.php
> +    private function addClassToMapIfExists(array $entityListenersXmlMap, array $entityListener, SimpleXMLElement $entityListenersXml)
Return type - drop the docblock

2017-08-03 20:43 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/YamlExporter.php
> +    private function processEntityListenerConfig($array, $entityListenerConfig, $event)
Return type

2017-08-03 20:43 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/Export/AbstractClassMetadataExporterTest.php
> +    public function testEntityListenersGetExported($class)
` : void`

2017-08-03 20:43 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/Export/AbstractClassMetadataExporterTest.php
> +     * @depends testExportedMetadataCanBeReadBackIn
Do you really want to use `@depends` here?

2017-08-03 20:43 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/Export/AbstractClassMetadataExporterTest.php
> +        $this->assertEquals(UserListener::class, $class->entityListeners[Events::prePersist][0]['class']);
Ah, this is the test that I was missing.

2017-08-03 20:43 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/Export/annotation/Doctrine.Tests.ORM.Tools.Export.User.php
> + *     Doctrine\Tests\ORM\Tools\Export\UserListener::class,
These should probably be prefixed with `\` to avoid import collisions

2017-08-04 10:33 UTC, tPl0ch commented on tests/Doctrine/Tests/ORM/Tools/Export/AbstractClassMetadataExporterTest.php
> +     * @depends testExportedMetadataCanBeReadBackIn
That's how all other export tests are structured, so I just adhered to the structure within the test case.

2017-08-04 10:36 UTC, tPl0ch commented on tests/Doctrine/Tests/ORM/Tools/Export/annotation/Doctrine.Tests.ORM.Tools.Export.User.php
> + *     Doctrine\Tests\ORM\Tools\Export\UserListener::class,
There is a weird issue with this, the resulting string is `"\Doctrine\Tests\ORM\Tools\Export\UserListener"`, although `::class` notation normally results in class names without root namespace:

```
php > echo \SimpleXMLElement::class;
SimpleXMLElement
```

2017-08-14 00:48 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/Export/annotation/Doctrine.Tests.ORM.Tools.Export.User.php
> + *     Doctrine\Tests\ORM\Tools\Export\UserListener::class,
Moved to https://github.com/doctrine/annotations/issues/141

2017-08-14 00:49 UTC, Ocramius commented
@tPl0ch see failures on https://travis-ci.org/doctrine/doctrine2/jobs/260960064#L594

2017-08-14 10:39 UTC, tPl0ch commented
@Ocramius I think I have fixed the issues regarding the nullable return types. I totally forgot that a method that has no return statement now actually is `none` and not `null`. Also inversed a few conditions to have early returns.

2017-08-15 08:22 UTC, Ocramius requested changes

2017-08-15 08:22 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/Export/Driver/AnnotationExporter.php
> +        if (!$this->_entityGenerator) {
Eh, we use `if ( ! $withTheSpace`

2017-08-16 10:28 UTC, tPl0ch commented
@Ocramius should be fine now (hopefully)...

2017-08-16 17:59 UTC, merged

2017-08-16 18:00 UTC, Ocramius commented
@tPl0ch manually merged via doctrine/doctrine2@76e2155fb34f69901bff7c0e3cd3768fc54dcf75

Sorry for the method hints - I had to revert them, since those classes are open for inheritance, so the additional hints are a BC break.

See https://3v4l.org/kSIhN for the specifics.

2017-08-16 18:03 UTC, Ocramius commented
Also, thanks for enduring the review hell we generally fire in contributors' direction :-)

2017-08-16 19:10 UTC, tPl0ch commented
@Ocramius is there a `phpcs` standards configuration file for Doctrine so that all that CS issues can be caught during development?

2017-08-16 19:44 UTC, Ocramius commented
There is, but we don't apply CS changes yet due to the amount of open PRs that would conflict for no good reason

2017-08-16 19:45 UTC, Ocramius commented
https://github.com/doctrine/coding-standard

On 16 Aug 2017 9:10 PM, "Thomas Ploch" <notifications@github.com> wrote:

> @Ocramius <https://github.com/ocramius> is there a phpcs standards
> configuration file for Doctrine so that all that CS issues can be caught
> during development?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/doctrine2/pull/6593#issuecomment-322870388>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakDnXSzCZ5F10qVpA0dtIVkMNhAJiks5sYz61gaJpZM4OphCN>
> .
>