Adding the final keyword for EntityManager to enforce no extension
doctrine/doctrine2 pull request #6596
Opened 2017-08-02 14:01 UTC by usmanzafar

Added the final keyword for EntityManager to indicate that extending EntityManager is not a valid extension point as recommended in https://github.com/doctrine/doctrine2/pull/6595 by @Ocramius / @Majkl578 
Let me know what do you guys think, very excited - first time contributing to a project that i use almost everyday for the last 3 years.

2017-08-02 15:12 UTC, Majkl578 commented
Unfortunately it won't be _that_ easy as just uncommenting the modifier. There is at least one case that needs to be adressed first: Doctrine\Tests\Mocks\EntityManagerMock currently extends EntityManager. :/

2017-08-02 15:28 UTC, Ocramius commented
To be added:

 * [ ] document breaking change in `UPGRADE.md` or equivalent
 * [ ] change test suite so the mock wraps a real `EntityManager` and implements the `EntityManagerInterface`
 * [ ] (maybe) consider killing `EntityManagerDecorator`?

2017-08-02 23:15 UTC, usmanzafar commented
Yes, should have checked thats my bad. Let me have a look at this and get back asap.

2017-08-03 12:52 UTC, alcaeus commented on tests/Doctrine/Tests/Mocks/EntityManagerMock.php
> +        return isset($this->uowMock) ? $this->uowMock : $this->em->getUnitOfWork();
`$this->uowMock ?? $this->em->getUnitOfWork();`

2017-08-03 12:52 UTC, alcaeus commented on tests/Doctrine/Tests/Mocks/EntityManagerMock.php
> +        return isset($this->proxyFactoryMock) ? $this->proxyFactoryMock : $this->em->getProxyFactory();
`$this->proxyFactoryMock ?? $this->em->getProxyFactory()`

2017-08-03 14:30 UTC, usmanzafar commented on tests/Doctrine/Tests/Mocks/EntityManagerMock.php
> +        return isset($this->proxyFactoryMock) ? $this->proxyFactoryMock : $this->em->getProxyFactory();
ahh yes! PHP 7 love. Will do it now. thanks @alcaeus :)

2017-08-03 14:59 UTC, usmanzafar commented
Hey @alcaeus i have updated the Mock / tests as per the recommendation, i have also merged https://github.com/doctrine/doctrine2/pull/6599 by @Majkl578 as this was necessary for the tests to pass. 
Let me know your thoughts.  Thanks

2017-08-05 07:16 UTC, Ocramius commented
Please rebase: the interface patch was merged to `develop`

2017-08-05 08:14 UTC, usmanzafar commented
@Ocramius  - done captain!

2017-08-05 08:33 UTC, Ocramius requested changes

2017-08-05 08:33 UTC, Ocramius commented on UPGRADE.md
> +## BC Break: Removed `EntityManager#flush($entity)` and `EntityManager#flush($entities)`
Something went wrong in the rebase here, and your BC break heading is gone

2017-08-05 08:33 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
> +        $this->markTestSkipped('Fix with StaticProxy Factory as ProxyFactory::class does not exist anymore');
Skipping this is unrelated to your patch

2017-08-05 08:33 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Hydration/ObjectHydratorTest.php
> +        $this->markTestSkipped('Fix with StaticProxy Factory as ProxyFactory::class does not exist anymore');
Same

2017-08-05 08:33 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/QueryBuilderTest.php
>      }
Correct the type of the `em` property in this test

2017-08-05 08:33 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/EntityManagerTest.php
> +        self::assertSame($this->em->getEM(), $em);
Correct the type of the `em` property in this test

2017-08-07 13:46 UTC, usmanzafar commented
Hey @Ocramius apologies for not replying earlier, i have fixed the tests and updated others as per your advice. Let me know your thoughts on this. Thanks

2017-08-07 13:57 UTC, Ocramius requested changes

2017-08-07 13:57 UTC, Ocramius commented on lib/Doctrine/ORM/EntityManager.php
> +    public function __construct(Connection $conn, Configuration $config, EventManager $eventManager)
@usmanzafar was this made `public` on purpose?

2017-08-09 12:37 UTC, usmanzafar commented
Hey @Ocramius having that method to public was a major mistake at my end. I have updated the mock to create an EM via static method. 
Secondly, after this change to mock i was getting an error/exception of  "Cannot use different EventManager instances for EntityManager and Connection" - i have fixed that issue and updated the creation of EntityManager via Mock so that eventManager and connection's event manager remain similar where applicable. If you believe that this is outside the scope of the patch then let me know i am happy to take them away from tests and keep EntityManager / EntityManagerMock changes.
Thanks

2017-08-10 09:01 UTC, Ocramius approved these changes
LGTM :+1:

2017-08-10 09:02 UTC, Ocramius commented
> Lastly, as per the new changes merged into develop the test `OnClassMetadataNotFoundEventArgsTest::testEventArgsMutability` is creating a mock of a final class which generates a warning in phpunit - shall we ignore this or do i need to update this - let me know your thoughts ?

@usmanzafar is it related to this patch?

2017-08-10 09:15 UTC, usmanzafar commented
@Ocramius   Technically no, visually I was being annoyed looking at the fact that final class is being mocked  haha. I think we are good man. so happy to be part of this project. Happy to see if this gets merged to develop :)

2017-08-10 09:17 UTC, Ocramius commented
:ship: then!

Thanks @usmanzafar \o/

2017-08-10 09:17 UTC, merged