Add support second, minute, week, year on DATE_ADD and DATE_SUB
doctrine/doctrine2 pull request #6742
Opened 2017-10-02 10:08 UTC by Legenyes

The DATE_ADD and DATE_SUB built-in function of Doctrine supports only the "hour", "month" and "day" intervals. I don't see the point of not having all the intervals available. These should be "minute", "second" and "year". I didn't check compatibility with other database vendors rather than MySQL but I don't think it should be a problem

Cfr Also Ticket https://github.com/doctrine/doctrine2/issues/3698

2017-10-02 11:35 UTC, Ocramius requested changes
Overall, patch looks good, but misses testing (especially integration with other DBs

2017-10-02 11:35 UTC, Ocramius commented on lib/Doctrine/ORM/Query/AST/Functions/DateAddFunction.php
> +			case 'minute':
I spotted some `\t` here ;-)

2017-10-03 07:01 UTC, Legenyes commented
Can i do something again ?

2017-10-03 12:43 UTC, Ocramius commented
Looks good to me: so far.

Assigning to @lcobucci for another pair of eyes.

2017-10-03 19:47 UTC, lcobucci requested changes
It LGTM, just some nitpicking. Also, aren't we missing tests for year and week add/sub?

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +    public function testDateAddTime()
Please add ` : void`

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Use `self::assert*()` instead

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Wouldn't be better to use a more specific assertion?

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Use `self::assert*()` instead

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Use `self::assert*()` instead

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Use `self::assert*()` instead

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Use `self::assert*()` instead

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Use `self::assert*()` instead

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Wouldn't be better to use a more specific assertion?

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Wouldn't be better to use a more specific assertion?

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Wouldn't be better to use a more specific assertion?

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Wouldn't be better to use a more specific assertion?

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +        $this->assertTrue(strtotime($arg[0]['add']) > 0);
Wouldn't be better to use a more specific assertion?

2017-10-03 19:47 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Functional/QueryDqlFunctionTest.php
> +    public function testDateSubTime()
Please add ` : void`

2017-10-04 09:47 UTC, Legenyes commented
@lcobucci I cannot change for` self::assert*()` and `: void `. 
These changes must be the subject of another PR.

2017-10-04 09:52 UTC, lcobucci commented
@Legenyes you can change for the code you're inserting.

2017-10-04 10:08 UTC, Legenyes commented
It's worse. 
Mixing two syntax in the same file is not a good practice.
I will not make this change in this PR

What about BC for `: void` ?

2017-10-04 10:43 UTC, Ocramius commented
This patch would land in 2.6 only, which is 7.1 only anyway

On 4 Oct 2017 12:08, "Sébastien Lévêque" <notifications@github.com> wrote:

> It's worse.
> Mixing two syntax in the same file is not a good practice.
> I will not make this change in this PR
>
> What about BC for : void ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/doctrine2/pull/6742#issuecomment-334110142>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakIsNIeuJfwNJ6M0wMq73_S22-w2Cks5so1kmgaJpZM4Pqbxg>
> .
>

2017-10-04 11:02 UTC, lcobucci commented
@Legenyes `self::assert*()` has already been fixed for v3 on the entire codebase, this means that new code should adhere to that, otherwise we need to reapply things over and over again. In the other hand, if we apply the change on v2 as well we'll be creating conflicts.

I agree that it's ideal to have mixed syntaxes but the least worse solution given this context.

2017-10-06 11:25 UTC, Legenyes commented
What' news ?

2017-10-06 12:56 UTC, lcobucci commented
@Legenyes we still don't have tests for `week` and `year` and we still have the same `self::assertTrue()` checks that IMO are not really helpful since it doesn't provide you enough info about the operation that has been done.

2017-10-18 14:45 UTC, greg0ire commented
[The docs](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html) currently say:

> DATE_ADD(date, days, unit) - Add the number of days to a given date. (Supported units are DAY, MONTH)

please change that too (add your units, and change "number of days")

2017-10-18 14:46 UTC, greg0ire commented
Closes #5835 ?

2017-10-31 15:34 UTC, lcobucci approved these changes

2017-10-31 19:46 UTC, merged

2019-06-03 17:53 UTC, JoppeDC commented
This wasn't in the docs yet, leading me to a search for how to do it. Luckily i found this old PR. I've created a PR to add this to the docs. 
https://github.com/doctrine/orm/pull/7729