Fixing setResultCacheProfile when handling null profile
doctrine/doctrine2 pull request #6861
Opened 2017-11-30 20:34 UTC by sandvige

Just bumping https://github.com/doctrine/doctrine2/pull/5842

Here is the code I'd like to use:

``` php
$tasks = $em
    ->createQuery('SELECT wt FROM Something wt')
    ->setHint(Query::HINT_LOCK_MODE, LockMode::PESSIMISTIC_WRITE)
    ->useResultCache(false)
    ->setHydrationCacheProfile(null)
    ->getResult()
;
```

Here is the result:

```
PHP Fatal error:  Call to a member function getResultCacheDriver() on a non-object in /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php on line XXX
```

Here is the workaround we're using:

``` php
class DisabledCache implements Cache
{
    function fetch($id)
    {
        return false;
    }

    function contains($id)
    {
        return false;
    }

    function save($id, $data, $lifeTime = 0)
    {
        return true;
    }

    function delete($id)
    {
        return true;
    }

    function getStats()
    {
        return null;
    }
}

$tasks = $em
    ->createQuery('SELECT wt FROM Something wt')
    ->setHint(Query::HINT_LOCK_MODE, LockMode::PESSIMISTIC_WRITE)
    ->useResultCache(false)
    ->setHydrationCacheProfile(new QueryCacheProfile(0, 'disabled', new DisabledCache))
    ->getResult()
;
```

2017-12-06 00:29 UTC, Majkl578 requested changes
Although pretty straightforward, this change will still require a test case.

2017-12-06 09:35 UTC, sandvige commented
I have no time to write a unit test for that, but this is a simple bug that currently exists. Fixing the way I purpose (which is exactly the same fix as this one 3 years ago 8625ca5187c05dbf5b4bfb3b3725f7c806e0644a) is just removing a bug :)

2017-12-06 09:37 UTC, Ocramius commented
@sandvige we don't consider fixes without tests, sorry

2017-12-17 02:08 UTC, lcobucci commented
Closing as duplicate of #6748

2017-12-17 02:08 UTC, closed without merging