[Parameter] Prevent names from starting or ending with a colon
doctrine/doctrine2 pull request #6881
Opened 2017-12-12 14:40 UTC by fancyweb

As requested by @Majkl578 in #5996

2018-04-13 15:59 UTC, Ocramius commented
@fancyweb can you check out `master`, cherry-pick https://github.com/doctrine/doctrine2/pull/6881/commits/d069ee3f85c54851dd272bd4e26b50c752671de3 into a new branch and force-push it here please?

2018-05-22 07:19 UTC, fancyweb commented
@Ocramius Sorry for the delay, it's done.

2018-05-22 08:59 UTC, Ocramius requested changes

2018-05-22 08:59 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Query/ParameterTest.php
> +     * @expectedException \InvalidArgumentException
Please move these to explicit calls to `expect*()` in the test body

2022-05-11 10:04 UTC, derrabus commented
I'm removing this PR from the 3.0.0 milestone for now because it's blocked by #6880.

2023-10-19 09:51 UTC, closed without merging