ManyToManyPersister fails to remove join table entry if there is multiple join columns
doctrine/doctrine2 pull request #6997
Opened 2018-01-19 17:10 UTC by NicolaF

This is due to a typo in `\Doctrine\ORM\Persisters\Collection\ManyToManyPersister::getDeleteSQLParameters`:

```
        foreach ($mapping['relationToSourceKeyColumns'] as $columnName => $refColumnName) {
            $params[] = isset($sourceClass->fieldNames[$refColumnName])
                ? $identifier[$sourceClass->fieldNames[$refColumnName]]
                : $identifier[$sourceClass->getFieldForColumn($columnName)];
        }

```

It should be `$sourceClass->getFieldForColumn($refColumnName)`, as `$columnName` is the join table column, not the entity table column.

2018-01-22 06:57 UTC, Ocramius requested changes
Overall good patch. Comments are really just nits, but we may need to check whether removal of the `EntityManager#flush()` call is possible. This is done elsewhere via `UnitOfWork#registerManaged()` (which may not even be needed here)

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/Models/ManyToManyPersister/ChildClass.php
> +/**
To be dropped

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/Models/ManyToManyPersister/ChildClass.php
> +    public function getId1(): int {
Remove all public API that isn't strictly needed. Use public properties instead

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/Models/ManyToManyPersister/ParentClass.php
> +    public function getId(): int {
Remove all public API that isn't strictly needed

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/Models/ManyToManyPersister/ChildClass.php
> + */
Prefix table names to avoid collisions with other test cases.

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/Models/ManyToManyPersister/ChildClass.php
> + * Class ChildClass
Redundant

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/Models/ManyToManyPersister/ChildClass.php
> + * @package Doctrine\Tests\Models\ManyToManyPersister
Redundant

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/Models/ManyToManyPersister/ParentClass.php
> +/**
To be removed

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Persisters/ManyToManyPersisterTest.php
> +/**
To be removed

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Persisters/ManyToManyPersisterTest.php
> +        $this->assertEquals([1,2], $lastUpdate['params']);
Consider using fixed assigned identifiers instead of `AUTO_INCREMENT` to prevent issues with subsequent test runs.

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Persisters/ManyToManyPersisterTest.php
> +        $updates = $conn->getExecuteUpdates();
Wondering if a full mock connection would be better here, assuming that we completely get rid of that `EntityManager#flush()` call

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Persisters/ManyToManyPersisterTest.php
> +        $this->assertEquals([1,2], $lastUpdate['params']);
Errata: I see you are already doing that 👍

2018-01-22 06:57 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Persisters/ManyToManyPersisterTest.php
> +    /**
Docblock redundant

2018-01-22 09:41 UTC, NicolaF commented
Hi @Ocramius,

I cleaned the test case as you requested. Howerver, I'm not sure to understand what you want to do with the `EntityManager#flush()` call. `ManyToManyPersister#delete` requires a `PersistentCollection` (because it needs the mapping to construct the delete statement), so `UnitOfWork#registerManaged()` won't do the job IMO.

Best Regards,
NicolaF

2018-01-23 09:31 UTC, lcobucci requested changes
I've just executed your tests without the fix and it passed, this doesn't look like an issue IMO...

2018-01-23 09:45 UTC, NicolaF commented
@lcobucci Yes it looks like the test case is not correct. The original code is :
```php
            $params[] = isset($sourceClass->fieldNames[$refColumnName])
                ? $identifier[$sourceClass->fieldNames[$refColumnName]]
                : $identifier[$sourceClass->getFieldForColumn($columnName)];
```

When I stumble upon this issue, `isset($sourceClass->fieldNames[$refColumnName])` evaluated to `false` which caused the subsequent call to `$sourceClass->getFieldForColumn($columnName)`

which cannot work as `$columnName` is the column in the join table, not in the entity table.

I will investigate further and update the unit test to make it useful.

2018-01-23 10:10 UTC, NicolaF commented
Test case update. To actually reproduce the issue, we need :
* multiple join columns
* the join column and the referenced column have different names
* the referenced column is a foreign key.

In this case the `$referencedColumn` is not in $sourceCles

2018-01-23 10:40 UTC, lcobucci commented
@NicolaF I will check it in a bit, can you please execute `phpcbf` on the files you created to ensure they follow our coding standard?

2018-01-23 16:20 UTC, NicolaF commented
@lcobucci done

2018-01-26 10:25 UTC, Ocramius commented
@NicolaF I think this is good to go. @lcobucci can you give it another check? This would need merging to `2.6.1`, `2.7` and `master`

2018-01-30 00:05 UTC, lcobucci approved these changes

2018-01-30 00:19 UTC, lcobucci commented
> @NicolaF I think this is good to go. @lcobucci can you give it another check? This would need merging to 2.6.1, 2.7 and master

@Ocramius I've made some minor changes to simplify the SUT and organise the annotations. It LGTM now. The build is failing for nightly PHP and mysql/pgsql but I think this is fine.

2018-01-30 00:19 UTC, merged

2018-01-30 00:22 UTC, lcobucci commented
@NicolaF 🚢 thanks!

2018-01-30 00:58 UTC, lcobucci commented
@NicolaF the good thing is that your test already passes in the current state of `master`, but I've added to the suite to ensure we won't have any regression (via 79282317d1006f48e6016ba6876f298605eb207d).

2018-01-30 09:45 UTC, NicolaF commented
You're welcome!