Cannot persist new entity if primary key contains a foreign key and the referenced object is in state new and its id is not assigned
doctrine/doctrine2 pull request #7003
Opened 2018-01-23 11:19 UTC by NicolaF

As the id of the referenced entity is generated, when `UnitOfWork#persistNew` computes the primary key, it may contain some `null` values.

Because of https://github.com/doctrine/doctrine2/commit/1cb8d790b64f542406a576b878d67abe284e7275 , `UnitOfWork#addToIdentityMap` does not allow this anymore, which is a good thing.

We need to delay the insertion into `identityMap` and `entityIdentifiers` after the actual insert to ensure that we have a complete primary key, as we do with post-insert ID generators.

This kinda worked in 2.5, but in the end `identityMap` and `entityIdentifiers` contained wrong values anyway.

2018-01-26 10:37 UTC, Ocramius requested changes

2018-01-26 10:37 UTC, Ocramius commented on lib/Doctrine/ORM/UnitOfWork.php
> +        $theseInsertions = [];
`$theseInsertions` is a bad name here

2018-01-26 10:37 UTC, Ocramius commented on lib/Doctrine/ORM/UnitOfWork.php
> +                    foreach ($idFields as $idField) {
This block seems to detect whether an identifier is incomplete. Can it be moved to a `private` method?

2018-01-26 10:37 UTC, Ocramius commented on lib/Doctrine/ORM/UnitOfWork.php
> +            foreach ($theseInsertions as $oid => $entity) {
If the commit order calculator is working correctly, then this should simply be pushed down in the execution path, no?

2018-01-26 10:38 UTC, Ocramius commented
Related: https://github.com/doctrine/doctrine2/issues/7002
Related: https://github.com/doctrine/doctrine2/issues/7006

Please check if #7006 fixes this for you.

2018-01-26 14:21 UTC, NicolaF commented
Hi @Ocramius,
I'll make the requested changes.

This is actually not related to #7006. Here, the code path starts with `UnitOfWork#persist`
and what happens is:
* set identifier if possible
* schedule for insert
* add to identity map if identifier has been set
* cascade persist for all associations

The commit order calculator is not involved here, it is just basic tree walking.

Actually the commit order calculator does the job, otherwise the second part of the patch (in `executeInserts`) would not work : the referenced entity is correctly inserted first, and we can finally have a complete identifier for the referencing entity.

2018-01-26 14:25 UTC, Ocramius commented
Thanks for clarifying that!

On 26 Jan 2018 15:21, "Nicolas FRANÇOIS" <notifications@github.com> wrote:

> Hi @Ocramius <https://github.com/ocramius>,
> I'll make the requested changes.
>
> This is actually not related to #7006
> <https://github.com/doctrine/doctrine2/issues/7006>. Here, the code path
> starts with UnitOfWork#persist
> and what happens is:
>
>    - set identifier if possible
>    - schedule for insert
>    - add to identity map if identifier has been set
>    - cascade persist for all associations
>
> The commit order calculator is not involved here, it is just basic tree
> walking.
>
> Actually the commit order calculator does the job, otherwise the second
> part of the patch (in executeInserts) would not work : the referenced
> entity is correctly inserted first, and we can finally have a complete
> identifier for the referencing entity.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/doctrine2/pull/7003#issuecomment-360797021>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakG13poHjtKGkmsYtnLNgPDQYvur7ks5tOd9agaJpZM4RpenL>
> .
>

2018-02-12 09:08 UTC, tmbdrogba commented
Is this PR ready to be merged ?

2018-02-12 09:38 UTC, NicolaF commented
It is IMHO, but I'm not the maintainer. @Ocramius, is it OK for you ?

2018-02-16 09:34 UTC, ste93cry commented
Actually I think this is breaking a lot of projects as it's not possible anymore after upgrading to 2.6 to persist any entity related to a new one in the same batch. Can we get this merged or at least a feedback to get it merged asap?

2018-02-16 09:47 UTC, Ocramius commented
I'm simply busy with other work stuff ATM - don't expect any deep involved OSS work from me for a while, sorry.

2018-02-16 09:49 UTC, ste93cry commented
Can we get at least another maintainer have a look at this? It's a really high priority bug to fix

2018-02-19 20:59 UTC, lcobucci commented
The code provided here doesn't follow our coding standards and we already had a test that reproduces this issue in #6701 (with a simpler set of entities too). I'll try to combine everything and adjust stuff to make this part of `v2.6.1` (also checking for any kind of performance impact).

2018-02-19 22:12 UTC, lcobucci commented
Fix was ported to #6701 and everything works as expected (with a minor, acceptable, performance impact) and it will be released on `v2.6.1` ASAP.

@NicolaF thank you for you help on the fix.

2018-02-19 22:18 UTC, closed without merging

2018-02-19 22:18 UTC, ste93cry commented
This is a huge news, thank you for your time!