Fixed updating of entity with quoted identifier join column
doctrine/doctrine2 pull request #7012
Opened 2018-01-26 14:31 UTC by janlanger

When entity has `JoinColumn` as its identifier, and this `JoinColumn` is quoted, the identifier is not quoted when building `UPDATE` query.

Quoting works fine when entity is inserted or selected...

2018-01-26 15:22 UTC, janlanger commented
Not really sure how to fix the failing tests... :(

2018-01-31 07:18 UTC, Ocramius requested changes

2018-01-31 07:18 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Functional/QuotedIdentifierAssociationTest.php
> +		$this->assertSQLEquals('UPDATE `quote-user-data` SET `name` = ? WHERE `user-id` = ?', $queries[$this->_sqlLoggerStack->currentQuery - 1]['sql']);
Quoting depends on the platform, so the backticks are not valid with all the various phpunit setups we have for different platforms. In postgresql (and other standard RDBMSs), identifiers are quoted via `"`, for example.

The test will need to be adapted as following, in my opinion:

1. quote all these 3 identifiers (`quote-user-data`, `name` and `user-id`)
2. expect them to NOT be equals to the non-quoted version
3. assert on the actual performed query with the quoted identifiers passed in via `sprintf()`

2018-01-31 16:46 UTC, janlanger commented
@Ocramius I hope I understand you correctly :-) Updated.

2018-01-31 16:50 UTC, Ocramius commented
@janlanger looks good 👍 

Will just need few cleanups (reducing code size, mostly). Shall do on merge.

2018-02-19 11:31 UTC, Ocramius commented
@lcobucci can you take over the merging and merging upstream here?

2018-02-19 12:25 UTC, lcobucci commented
@Ocramius will do

2018-02-25 19:02 UTC, lcobucci commented
@janlanger I've synced the branch with the latest state of `v2.6` and simplified things to have a single test to port to `master`. I was going to override your branch but didn't have access so had to open a new PR (#7093) to solve that, which will be merged when we have everything green.

Thanks for your contribution!

2018-02-25 19:02 UTC, closed without merging