Fix ID generation of foreign keys
doctrine/doctrine2 pull request #7054
Opened 2018-02-09 15:16 UTC by cb8

this patch is an alternate approach to #7003 which tries to fix #7002. however, it applies to the `master` branch. so far, i didn't clean up my test cases. in case this patch will get merged despite/instead of #7003, i will push them for review.

2018-02-20 07:20 UTC, lcobucci commented
@cb8 thanks for your patch, we just merged in the fix for 2.6 and were porting it to master. I'll check your changes to see if it works better for the new version of the code.

2018-02-20 08:53 UTC, lcobucci commented
@cb8 your changeset makes the tests of #6701 pass but breaks `SecondLevelCacheCompositePrimaryKeyWithAssociationsTest` because it tries to update a read only entity, I'll investigate further this week but it would be nice if you could check it as well.

2018-02-24 14:17 UTC, cb8 commented
thank you for the review. the deferred IDs were inadvertently flattened when they were added to the original data of the entity. as far as i could see, the failing tests on Travis are not caused by the patch (but don't hold me to that ;)).

2018-02-25 18:05 UTC, lcobucci requested changes
Some small changes, I'll take care of these in a bit. @cb8 thanks a lot for your help!

2018-02-25 18:05 UTC, lcobucci commented on lib/Doctrine/ORM/UnitOfWork.php
> +                $this->entityIdentifiers[$oid]  = $this->em->getIdentifierFlattener()->flattenIdentifier($class, $id);
@guilhermeblanco this looks ok, but I'd like your eyes here

2018-02-25 18:31 UTC, lcobucci approved these changes

2018-02-25 18:33 UTC, guilhermeblanco approved these changes

2018-02-25 18:37 UTC, merged

2018-02-25 18:38 UTC, lcobucci commented
@cb8 🚢 thanks for your contribution!