Fix/#7068 entitymanager find with pessimistic lock does not check for transaction
doctrine/doctrine2 pull request #7075
Opened 2018-02-17 14:55 UTC by BreiteSeite

Fix for #7068

2018-02-17 17:56 UTC, lcobucci commented
@BreiteSeite could you please rebase this branch, we just fixed the build =)

2018-02-17 17:58 UTC, BreiteSeite commented
@lcobucci Sure. :) Done. Thanks for fixing the build.

2018-04-13 16:11 UTC, Ocramius requested changes
Besides the suggestion to move the checks to a `private` method, this is nice and clean :+1:

2018-04-13 16:11 UTC, Ocramius commented on lib/Doctrine/ORM/EntityManager.php
> +        switch ($lockMode) {
Should probably move this entire thing to a `private` method

2018-04-15 11:40 UTC, Ocramius submitted a review, later dismissed

2018-04-15 11:41 UTC, Ocramius commented
We'll fix conflicts and CS issues on merge, thanks @BreiteSeite! :+1:

2018-06-27 18:32 UTC, Majkl578 commented
Since this is milestoned as 2.6, I changed base branch, but it will require rebase. It can be done on merge.

2018-07-03 01:02 UTC, Majkl578 commented
2.6 is too different unfortunately, so I picked changes from here into  #7291.

2018-07-03 01:12 UTC, Majkl578 commented
Rebased and squashed this PR, also fixed CS and other issues after rebase.

2018-07-03 07:42 UTC, Ocramius approved these changes
:+1:

2018-07-03 07:43 UTC, merged