[RFC] Tighten owning side resolution
doctrine/doctrine2 pull request #7085
Opened 2018-02-22 05:26 UTC by guilhermeblanco

Fixed bug with potential double owning side in OneToOne when JoinColumns were mapped on both association sides. In that case, the ownership was determined based on association flow (in A -> B, A:b was owning, while in B -> A, B:a was owning).

2018-02-22 10:42 UTC, Ocramius requested changes
@guilhermeblanco I only see changes in existing tests, yet no new test showing the actual issue (with a single assertion) here

2018-02-23 09:53 UTC, lcobucci requested changes

2018-02-23 09:53 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Mapping/AbstractMappingDriverTest.php
> +    public function testOwningSideResolution() : void
Please split this into multiple tests, each `//` can be a separate method. Things would be much simpler to understand.

2018-02-23 09:53 UTC, lcobucci commented on doctrine-mapping.xsd
> +      <xs:pattern value="[a-zA-Z\-_u01-uff.]+" id="tablename.pattern">
Do we have more chars that should be allowed here?

2018-02-23 15:13 UTC, lcobucci approved these changes

2018-02-23 15:13 UTC, Ocramius approved these changes

2018-02-23 15:13 UTC, Ocramius commented
:ship:

2018-02-23 15:13 UTC, merged

2018-02-23 16:16 UTC, Majkl578 commented
Shouldn't this go to UPGRADE as well?