DDC-3063 #comment add a helpful error so a developer can decide what to do next
doctrine/doctrine2 pull request #7108
Opened 2018-03-02 21:08 UTC by jackdpeterson

Current error: '[Syntax Error] line X, col Y: Error: Expected Literal, got ')''

The outcome is still the same with a Syntax Error being thrown.

New syntax error contains helpful directions to resolve this problem.

2018-03-03 11:28 UTC, Ocramius requested changes
Requires test case additions

@greg0ire anything you can suggest about the exception to be used?

2018-03-03 11:55 UTC, greg0ire commented
I'm fine with it, but ultimately `syntaxError` will have to be extracted (by me, probably) from `QueryException`

2019-05-28 06:03 UTC, jackdpeterson commented
I see this got assigned back over to me. Where specifically can I assist in moving this forward?

2019-05-28 06:39 UTC, greg0ire commented
You should ensure the new code is covered by extensive tests.

2019-08-08 17:23 UTC, closed without merging