DDC-2842: Leave out discriminator part of Doctrine' generated SQL on root entity
doctrine/doctrine2 pull request #7119
Opened 2018-03-07 04:42 UTC by 11ya

Fix for [#2842](https://github.com/doctrine/doctrine2/issues/3596)

2018-03-07 06:14 UTC, Ocramius requested changes
The reason why the `t.discriminator_column IN()` condition is added is that we do not assume totality of record ownership on that table.

Records may have an unknown discriminator or belong to other inheritance trees.

While this change is possibly an improvement, it also represents a BC break, as hydration would just choke when encountering an unknown discriminator value.

2018-03-10 09:57 UTC, 11ya commented
@Ocramius Ok, if I understand you correctly, check on root entity class name should solve the problem of "belong to other inheritance trees". As for "unknown discriminator", I see only one decision - add checking discriminator value constraint to the table definition and separate option in discriminator map for that.

2018-03-10 10:12 UTC, Ocramius commented
> I see only one decision - add checking discriminator value constraint to the table definition and separate option in discriminator map for that.

No way: this is a lot of added complexity for something that DB indexes solved already

2018-03-12 19:02 UTC, Ocramius requested changes

2018-03-12 19:02 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/DiscriminatorColumn.php
> +    public $strict;
As I mentioned before, an addition here is not to be considered unless an actual problem is being solved by it. So far, it seems like this only leads to removal of an `IN()` condition on discrimitor values when set to `false`

2018-03-12 19:02 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/SchemaTool.php
> +            $column->setCustomSchemaOption('check', 'CHECK (' . $discrColumn['name'] . ' IN (' . implode(',', $values) . '))');
Don't think we'll manage to make this work cross-platform

2018-04-13 15:53 UTC, Ocramius commented
Taking a decision not to pursue this further: there is some improvement in the generated SQL, yes, but most decent SQL query optimisers can deal with these details anyway.

Therefore, closing as `won't fix` here, sorry @11ya!

2018-04-13 15:53 UTC, closed without merging