Fix/7141 xml order by default asc
doctrine/doctrine2 pull request #7146
Opened 2018-03-21 08:58 UTC by Awkan

Problem
--------

As mentioned in issue #7141 , when we use XML mapping for a `<one-to-many>` relation with an `<order-by>` node, the default value `direction=ASC` isn't set by default.

Solution
--------
In this PR, I define the default direction to `ASC` if not set

2018-03-21 09:30 UTC, Ocramius commented on lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php
> +                            : 'ASC'
`Criteria::ASC` if possible

2018-03-21 09:30 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.Models.Cache.City.dcm.xml
> -        <order-by-field name="name" direction="ASC"/>
Please do define new mapping files for tests

2018-03-21 09:30 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Mapping/xml/Doctrine.Tests.ORM.Mapping.User.dcm.xml
> -                <order-by-field name="number" direction="ASC" />
Revert: use your own mapping file/scenario here please

2018-03-21 09:31 UTC, Ocramius commented on tests/Doctrine/Tests/ORM/Tools/Export/xml/Doctrine.Tests.ORM.Tools.Export.User.dcm.xml
> -                <order-by-field name="number" direction="ASC" />
Revert: use your own mapping file/scenario here please

2018-03-21 09:31 UTC, Ocramius requested changes
Test additions are still needed here

2018-03-22 19:11 UTC, Awkan commented
@Ocramius I've added a test, this was what you expect ?

2018-03-22 21:58 UTC, Ocramius commented
@Awkan yep, this matches, thanks :+1:

2018-03-22 21:58 UTC, Ocramius approved these changes

2018-03-22 23:29 UTC, jwage approved these changes

2018-04-12 20:29 UTC, merged