Add BETWEEN() expr and fix the PHPDoc.
doctrine/doctrine2 pull request #7181
Opened 2018-04-09 09:43 UTC by frag-seb

The parameters $x and $y can also be a string, for example a date.

2018-04-09 11:28 UTC, holtkamp commented
Nice, maybe this can be combined with resolving https://github.com/doctrine/doctrine2/issues/6450

2018-04-09 11:40 UTC, lcobucci requested changes
@frag-seb please change the destination branch to `master` and rebase your branch, more info: https://github.com/doctrine/doctrine2#which-branch-should-i-choose

Also keep in mind that only security fixes will be applied in `2.5`, so if you're still using it we recommend you to upgrade to `2.6` ASAP.

2018-04-09 11:40 UTC, lcobucci commented on lib/Doctrine/ORM/Query/Expr.php
> +    public function notBetween($val, $x, $y)
Return type declaration missing

2018-04-09 11:40 UTC, lcobucci commented on lib/Doctrine/ORM/Query/Expr/Between.php
> +class Between
This class should be marked as `final` since it doesn't make much sense in extending it

2018-04-09 11:40 UTC, lcobucci commented on lib/Doctrine/ORM/Query/Expr/Between.php
> +    const NOT_BETWEEN = 'NOT BETWEEN';
Visibility missing

2018-04-09 11:40 UTC, lcobucci commented on lib/Doctrine/ORM/Query/Expr/Between.php
> +    protected $operator;
Property should be private

2018-04-09 11:40 UTC, lcobucci commented on lib/Doctrine/ORM/Query/Expr/Between.php
> +    public function getKey()
The getters could be removed since they're not used publicly.

2018-04-09 11:40 UTC, lcobucci commented on lib/Doctrine/ORM/Query/Expr/Between.php
> +     * Constructor.
This line doesn't say anything we should either remove it or have meaningful explanation (I'd simply remove it 😛)

2018-04-09 11:40 UTC, lcobucci commented on lib/Doctrine/ORM/Query/Expr/Between.php
> +    public function __toString()
Return type declaration can be added and doc block removed

2018-04-09 11:40 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Query/ExprTest.php
> +    public function testNotBetweenExpr()
Missing ` : void`

2018-04-09 11:40 UTC, lcobucci commented on tests/Doctrine/Tests/ORM/Query/ExprTest.php
> +        $this->assertEquals('u.id NOT BETWEEN 3 AND 6', (string) $this->_expr->notBetween('u.id', 3, 6));
Please use `self::assertSame()` to avoid weird type juggling/comparison

2018-04-09 13:10 UTC, Ocramius commented
Closing as `invalid`.

`Improvement` patches are to be sent to `master` only: we will only fix bugs on `2.x`, and `2.5` will only receive security fixes.

2018-04-09 13:10 UTC, closed without merging

2018-04-09 13:40 UTC, frag-seb commented
Does it make sense to send this PullRequest for the master?

2018-04-09 13:43 UTC, Ocramius commented
@frag-seb yes, if it improves `master` :+1:

2018-05-28 14:09 UTC, holtkamp commented
@frag-seb did this eventually land in `master`? I am asking because I am wondering about the status of https://github.com/doctrine/doctrine2/issues/6450