Split and deprecate AbstractQuery#useResultCache()
doctrine/doctrine2 pull request #7213
Opened 2018-05-06 22:15 UTC by someniatko

Split `useResultCache($boolFlag, ...)` into `enableResultCache()` and `disableResutCache()`.

To create tests for `enableResultCache()` and `disableResultCache()`, `useResultCache()`'s tests were copy-pasted, but I think that's fine.

2019-05-03 06:58 UTC, greg0ire requested changes

2019-05-03 06:58 UTC, greg0ire commented on lib/Doctrine/ORM/AbstractQuery.php
> +    public function enableResultCache($lifetime = null, $resultCacheId = null)
```suggestion
    public function enableResultCache(?int $lifetime = null, ?string $resultCacheId = null): self
```

2019-05-03 06:58 UTC, greg0ire commented on lib/Doctrine/ORM/AbstractQuery.php
> +    public function disableResultCache()
```suggestion
    public function disableResultCache(): sef
```

2019-05-03 06:59 UTC, greg0ire commented
You will probably need to rebase as your branch contains commits that you did not author.

2019-05-03 07:25 UTC, someniatko commented
okay, will work on it later today

2019-05-07 20:19 UTC, closed without merging

2019-05-07 20:27 UTC, someniatko commented
created new MR: https://github.com/doctrine/orm/pull/7701