Bugfix with namespaces
doctrine/doctrine2 pull request #7235
Opened 2018-05-22 09:22 UTC by aashmelev

For a schema of metadata, namespaces were not created. Because of this, there was a difference between the current schema and the schema from the metadata when you run `doctrine:migrations:diff` command.

2018-05-22 10:11 UTC, Ocramius requested changes
@aashmelev this kind of patch requires a test case addition

2018-05-22 10:12 UTC, Ocramius requested changes

2018-05-22 10:12 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/SchemaTool.php
> +    private function getNamespaces() {
` : array`

2018-05-22 10:12 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/SchemaTool.php
> +     * Gets namespaces for the current platform
This description can be made the method name

2018-05-22 10:12 UTC, Ocramius commented on lib/Doctrine/ORM/Tools/SchemaTool.php
> +        $namespaces = $this->em->getConnection()->getSchemaManager()->listNamespaceNames();
Can return directly. I suggest one `->` per line though, which aids stack trace handling

2018-06-13 13:45 UTC, aashmelev commented
Do I need to add any more tests?

2018-07-17 10:01 UTC, brizzz commented on lib/Doctrine/ORM/Tools/SchemaTool.php
> +        $namespaces = ! $withNamespaces ? [] : $this->getPlatformNamespaces();
I think 
`$namespaces = $withNamespaces ? $this->getPlatformNamespaces() : [];`
would be more clear to read.

2025-01-15 03:02 UTC, closed without merging