Add a polyfill for ctype
doctrine/doctrine2 pull request #7283
Opened 2018-07-01 15:55 UTC by BackEndTea

A cytpe function is used here: https://github.com/doctrine/doctrine2/blob/2726636e55fdbdf6fb1ed466f22d34de116fb8f9/lib/Doctrine/ORM/Query/Lexer.php#L163

But ctype is not always enabled, especially for minimalist distributions like alpine.

2018-07-01 16:01 UTC, Ocramius requested changes

2018-07-01 16:01 UTC, Ocramius commented on composer.json
> +        "symfony/polyfill-ctype": "~1.8"
Probably better to require `"ext-ctype"` and have consumers include `"symfony/polyfill-ctype"` or any other polyfill that implements the `"provides"` clause in their `composer.json`

2018-07-01 18:35 UTC, BackEndTea commented
I have changed it to require ext-ctype instead

2018-07-01 18:38 UTC, Majkl578 commented
Two things here:
Can we you retarget this to 2.6 branch? It's affected too.
Can you please move it just below `php`? The `require` section is `platform -> exts -> dependencies`.

2018-07-01 18:39 UTC, Majkl578 commented
Also do we have any other extensions with similar "issue"?

2018-07-03 08:48 UTC, Ocramius commented
Let's keep it to `master` - the backporting is up to us or to separate PRs targeting the older branches.

2018-07-03 08:49 UTC, Ocramius approved these changes

2018-07-03 08:51 UTC, merged

2018-07-03 08:54 UTC, Ocramius commented
Hmm, I can't pull this into `2.6` due to the added dependency. Since it's an added dependency, it may break security updates for people not touching this code path and still running stable ORM versions.

2018-07-03 08:54 UTC, BackEndTea commented
Thank you @Ocramius & @Majkl578