Improvements
doctrine/doctrine2 pull request #7297
Opened 2018-07-05 01:31 UTC by carusogabriel

Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to Doctrine :smile: 

PS: The commits will be squashed before the merge, they are only this way to inform what was done in each commit.

2018-07-05 02:26 UTC, Majkl578 requested changes
Good overall, just some nitpicks (forward compatibility with new CS) and 3 bugs. :)
Also please squash the changes into one or two commits.

2018-07-05 18:17 UTC, carusogabriel commented on lib/Doctrine/ORM/Mapping/AbstractClassMetadataFactory.php
> -     * @throws ReflectionException
But the concept of `@throws` annotations arent in the method they happen?

2018-07-05 18:18 UTC, carusogabriel commented on lib/Doctrine/ORM/Query/Parser.php
> -        return $updateItem;
Yes, just need to figure out how. Maybe https://github.com/sirbrillig/phpcs-variable-analysis can help us

2018-07-05 18:18 UTC, carusogabriel commented on lib/Doctrine/ORM/QueryBuilder.php
> -            $this->dqlParts[$dqlPartName] = ($isMultiple) ? [$dqlPart] : $dqlPart;
Yeah, we definitely do

2018-07-05 18:19 UTC, carusogabriel commented on lib/Doctrine/ORM/AbstractQuery.php
> +                return $key === $parameterName || (string) $key === $parameterName;
Gotcha, thanks!

2018-07-05 18:45 UTC, Majkl578 commented on lib/Doctrine/ORM/Query/Parser.php
> -        return $updateItem;
This specific case looks rather easy - if `return` has a single variable, and previous _effective_ statement is an assignment to this variable, then this variable should be useless.

WDYT @kukulich? UselessVariableSniff?

2018-07-05 19:57 UTC, kukulich commented on lib/Doctrine/ORM/Query/Parser.php
> -        return $updateItem;
Interesting idea :) Probably all variables that are used just once could be marked as useless.

2018-07-26 00:58 UTC, carusogabriel commented
Anything left to be done here?

2018-07-26 10:52 UTC, Ocramius commented
Yes:

 1. rename PR to describe what is being done
 2. smash the commit description into a single line (it fits)

Also: what's missing to get the build green?

2018-07-26 11:07 UTC, carusogabriel commented
> What's missing to get the build green?

Strange, it was before I rebase with `master`. Gonna debug what went wrong and fix what you've requested :)

2018-08-10 00:10 UTC, carusogabriel commented
Closing as these changes will be add in the next version of https://github.com/doctrine/coding-standard and be done automatically :tada:

2018-08-10 00:10 UTC, closed without merging