Use dedicated assertContainsOnlyInstancesOf PHPUnit assertion
doctrine/doctrine2 pull request #7440
Opened 2018-10-22 15:03 UTC by carusogabriel

2018-10-22 16:58 UTC, Ocramius requested changes
@carusogabriel please make sure the minimum PHPUnit version in `composer.json` has these assertions built in (may already be the case)

2018-10-22 17:27 UTC, Ocramius approved these changes

2018-10-30 11:41 UTC, carusogabriel commented
@Ocramius Can we merge this one?

2018-10-30 11:44 UTC, merged

2018-10-30 11:44 UTC, Ocramius commented
:ship: (had to disable checks to merge, since `master` is red