Added doc about exception in Query#getOneOrNullResult()
doctrine/doctrine2 pull request #7443
Opened 2018-10-29 20:35 UTC by naitsirch

When calling `Query#getOneOrNullResult()` and there are more than one objects in the result an `NonUniqueResultException` is thrown.
This information was missing in the documentation about the query result
formats.

This PR addresses #6793 (@lcobucci).

2019-06-21 14:09 UTC, SenseException submitted a review, later dismissed

2019-06-22 09:54 UTC, greg0ire requested changes

2019-06-22 09:54 UTC, greg0ire commented on docs/en/reference/dql-doctrine-query-language.rst
> +   result contains more than one object, an ``NonUniqueResultException``
```suggestion
   result contains more than one object, a ``NonUniqueResultException``
```

2019-06-24 20:12 UTC, naitsirch commented
Thanks @greg0ire for the correction ;-)

2019-06-24 20:15 UTC, greg0ire approved these changes

2019-10-02 02:07 UTC, merged

2019-10-02 02:07 UTC, lcobucci commented
@naitsirch thanks :+1: