Added clarification of using change tracking policy on entities with embeddables
doctrine/doctrine2 pull request #7495
Opened 2018-11-30 20:00 UTC by carnage

Spend a good long time figuring this one out today; figured it'd help someone else in the future

2018-11-30 20:54 UTC, greg0ire requested changes

2018-11-30 20:54 UTC, greg0ire commented on docs/en/reference/change-tracking-policies.rst
> +separatly for each property in the embeddable when it changes
```suggestion
separately for each property in the embeddable when it changes 
```

2018-11-30 20:54 UTC, greg0ire commented on docs/en/reference/change-tracking-policies.rst
> +                //notice the entityField.embeddableField notation for referencing the property
```suggestion
                // notice the entityField.embeddableField notation for referencing the property
```

2018-11-30 20:54 UTC, greg0ire commented on docs/en/reference/change-tracking-policies.rst
> +                $this->embedable = $embeddable;
```suggestion
                $this->embeddable = $embeddable;
```

2021-08-29 10:11 UTC, carnage commented
@greg0ire Noticed this hadn't been merged; rebased & retargeted to 2.9 should be good to go in.

2021-08-29 10:30 UTC, greg0ire approved these changes

2021-08-29 21:43 UTC, SenseException approved these changes

2021-08-29 21:44 UTC, merged

2021-08-29 21:44 UTC, derrabus commented
Thank you @carnage!