Prefer PhpFileCache for caching docs
doctrine/doctrine2 pull request #7500
Opened 2018-12-02 05:08 UTC by shadowhand

Removes APC and XCache because they are deprecated.

Remvoes APCu because it is not as performant as PhpFileCache and cannot
be cleared using using console tools.

Refs https://github.com/doctrine/doctrine2/pull/7493#pullrequestreview-180007007

2018-12-02 12:19 UTC, greg0ire commented
Please amend your commit message:

```diff
- Remvoes APCu because it is not as performant as PhpFileCache and cannot
be cleared using using console tools.
+ Removes APCu because it is not as performant as PhpFileCache and cannot
be cleared using console tools.
```

2018-12-02 12:24 UTC, greg0ire requested changes

2018-12-02 15:32 UTC, greg0ire submitted a review, later dismissed

2018-12-02 15:33 UTC, greg0ire commented
Please amend your commit message:

```diff
- be cleared using using console tools.
+ be cleared using console tools.

2018-12-02 20:29 UTC, shadowhand commented
@greg0ire fixed.

2018-12-02 21:37 UTC, greg0ire approved these changes

2018-12-03 03:09 UTC, shadowhand commented
@Majkl578 clearing PhpFileCache means removing files, and opcache detects the removal of files.

2018-12-03 03:30 UTC, Majkl578 commented
> opcache detects the removal of files

Only if configured to do so, and this setting should be disabled on production.

2018-12-05 12:17 UTC, Ocramius approved these changes

2018-12-05 12:26 UTC, Majkl578 requested changes
As per my comment above, one can of worms is being replaced by another can of worms while the original issue remains.
I support getting rid of APCu, but this is not the correct way.

2018-12-05 12:34 UTC, Ocramius commented
The PhpFileCache is perfectly fine for any static-ish setups, like
metadata: even better, it fits most deployment strategies too.

On Wed, 5 Dec 2018, 13:26 Michael Moravec <notifications@github.com wrote:

> *@Majkl578* requested changes on this pull request.
>
> As per my comment above, one can of worms is being replaced by another can
> of worms while the original issue remains.
> I support getting rid of APCu, but this is not the correct way.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine/doctrine2/pull/7500#pullrequestreview-181730005>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJakEh6SlFw40IBdEyiqR928VgIXPOZks5u17uEgaJpZM4Y9PlG>
> .
>

2018-12-05 15:32 UTC, shadowhand commented
@lcobucci since the there is no filesystem change being done, will running apps see the cache clear, _even when the server is **not** restarted_?

2018-12-05 17:39 UTC, lcobucci commented
@shadowhand let's remove opcache from equation for one sec. When we do the `PhpFileCache#removeAll()`, we get the file that stores the namespace version and write the new namespace version to it. That's how the upcoming commands/requests know which version to use.

For production, opcache usually is configured like this (apart from other ones):

```
opcache.validate_timestamps=0
opcache.enable_file_override=1
```

The comments of the first one give us the answer to your question:

```
; When disabled, you must reset the OPcache manually or restart the
; webserver for changes to the filesystem to take effect.
```

So, no, namespace version change won't be propagated unless opcache is cleared manually or via webserver restart.

2018-12-06 13:48 UTC, shadowhand commented
@lcobucci thanks.

@Majkl578 given that your concern is about how opcache *might* be configured, how do you suggest that this PR be changed to address that?

2019-08-13 21:52 UTC, lcobucci commented
@shadowhand sorry about the huge delay here... I'd say that it's fine to use file system cache for annotations, query, and metadata cache but for result set and L2C I'd rather suggest Redis.

2019-11-14 21:50 UTC, ostrolucky approved these changes

2019-11-15 10:01 UTC, lcobucci requested changes
I would also not remove APCu and XCache from the docs because they're also helpful scenarios where it's just fine to use them (containerised apps or blue-green deployments).

2019-11-15 10:04 UTC, lcobucci commented
@shadowhand thanks a lot for the initial write-up. I hope my suggestions make sense to you and help us move this further.

We're working to finalise the `2.6.x` minor and since this is not a really urgent bug fix I moved it to `2.7.1` so that we have time to discuss and organise this well.

Thanks again for your contribution :+1:

2019-11-17 23:30 UTC, SenseException requested changes

2019-11-17 23:30 UTC, SenseException commented on docs/en/reference/caching.rst
> +    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCacheCache(
```suggestion
    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCache(
```

2019-11-17 23:30 UTC, SenseException commented on docs/en/reference/caching.rst
> +    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCacheCache(
```suggestion
    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCache(
```

2019-11-17 23:30 UTC, SenseException commented on docs/en/reference/caching.rst
> +    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCacheCache(
```suggestion
    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCache(
```

2019-11-17 23:30 UTC, SenseException commented on docs/en/reference/caching.rst
> +    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCacheCache(
```suggestion
    $cacheDriver = new \Doctrine\Common\Cache\PhpFileCache(
```

2019-11-17 23:30 UTC, SenseException commented on docs/en/reference/caching.rst
> +cache items and writes them to a file. This allows for opcode caching
Because an external resource might disappear, that short mention of the impact would be nice as an extra.

2020-01-08 18:39 UTC, beberlei commented
Merged in 20c46035d129a478e438a4c65d94063ef234f4ea

2020-01-08 18:39 UTC, closed without merging