Update working-with-objects.rst
doctrine/doctrine2 pull request #7553
Opened 2019-01-04 09:37 UTC by CraicOverflow89

Spelling.

2019-01-04 10:06 UTC, greg0ire submitted a review, later dismissed

2019-01-04 10:51 UTC, deeky666 approved these changes

2019-01-06 04:48 UTC, malukenho approved these changes

2019-01-06 11:05 UTC, Majkl578 requested changes
Change is good but I'm going to be annoying and ask for a better commit message, at least i.e. _"Fix typo in Working with Objects chapter"_.

2019-01-06 12:18 UTC, greg0ire commented
@CraicOverflow89 I see this is your first contribution so here is some help:

```
cd /tmp
git clone git@github.com:CraicOverflow89/orm.git
cd orm
git checkout patch-1
git commit --amend
git push --force
```

2025-01-01 23:25 UTC, SenseException approved these changes

2025-01-01 23:25 UTC, merged

2025-01-01 23:26 UTC, SenseException commented
Thank you @CraicOverflow89
Special thanks to the newly added reminder-bot