Allow all datetime types to be used as version
doctrine/doctrine2 pull request #7554
Opened 2019-01-04 12:11 UTC by nico-incubiq

I am working on an existing database with fields of type `timestamp`. In order to map that to a DateTime object in Doctrine, I've found the solution of adding the `@Version` annotation. But I'd really prefer to get a DateTimeImmutable, which is impossible.

At the moment a field of type `datetime_immutable` with annotation `@Version` will trigger this following error:
```
Locking type "datetime_immutable" (specified in "App\Entity\Bakery", field "createdAt") is not supported by Doctrine.
```

I cannot see any reason not to allow any type of datetime to be mapped to a timestamp in database, so this PR allows all of them. Please tell me if i'm missing something.

2019-01-04 12:28 UTC, SenseException requested changes
Thank you for your contribution. Can you please add tests for all the supported types?

I'm not sure about if the ORM version 2.6 should introduce these changes. I'll wait what others have to say about the version.

2019-01-04 13:32 UTC, lcobucci commented
@nico-incubiq according to our docs `datetime` is supported, have you tried that? https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/transactions-and-concurrency.html#optimistic-locking

2019-01-04 13:33 UTC, lcobucci commented
As @SenseException this would be ok for v3 (`master`)

2019-01-04 14:44 UTC, nico-incubiq commented
Yeah i'm currently working with "datetime", but i'd rather get a DatetimeImmutable rather than just a DateTime. When is v3 due? Since this isn't a breaking change I expected it to be fine in 2.6.

2019-01-04 16:39 UTC, lcobucci commented
@nico-incubiq this is considered a new feature, which should go in a new `minor` release - not `patch`. You can propose this to `v2.7` but we were planning to only have deprecation notices there, however there's no due date set for `v3`.

2019-01-05 12:04 UTC, nico-incubiq commented
I've opened a new PR targeting v3 and added tests to it, I'll close this one then.

2019-01-05 12:04 UTC, closed without merging