update phpstan to 0.11
doctrine/doctrine2 pull request #7645
Opened 2019-03-12 22:39 UTC by CZechBoY

There is issue which I dont know how you want to resolve:
`Doctrine\ORM\Persisters\Entity\BasicEntityPersister.php:`
```
Array has 2 duplicate keys with value '=' (\Doctrine\Common\Collections\Expr\Comparison::EQ, \Doctrine\Common\Collections\Expr\Comparison::IS).
```

Just tell me which one I should delete and I fix it in this PR.

2019-03-17 01:14 UTC, carusogabriel commented
@CZechBoY I believe that one should be ignored. Whoever is using `Comparison::EQ` or `Comparison::IS` is gonna be a BC 😕

2019-03-22 18:16 UTC, CZechBoY commented
@carusogabriel The collision is in private static property, but keys and values are the same.
```
class BasicEntityPersister implements EntityPersister
{
    /** @var string[] */
    private static $comparisonMap = [
        Comparison::EQ          => '= %s',
        Comparison::IS          => '= %s',
        Comparison::NEQ         => '!= %s',
        Comparison::GT          => '> %s',
        Comparison::GTE         => '>= %s',
        Comparison::LT          => '< %s',
        Comparison::LTE         => '<= %s',
        Comparison::IN          => 'IN (%s)',
        Comparison::NIN         => 'NOT IN (%s)',
        Comparison::CONTAINS    => 'LIKE %s',
        Comparison::STARTS_WITH => 'LIKE %s',
        Comparison::ENDS_WITH   => 'LIKE %s',
    ];
```

So should I remove IS/EQ? Or change constant value?

2019-04-22 04:04 UTC, carusogabriel requested changes
> So should I remove IS/EQ? Or change constant value?

Let's add it to the `phpstan.neon` file under `ignoreErrors` for now.

2019-04-22 04:04 UTC, carusogabriel commented on lib/Doctrine/ORM/Tools/Pagination/CountOutputWalker.php
>       * @param ParserResult $parserResult
You can drop these two phpDocs.

2019-04-22 04:04 UTC, carusogabriel commented on lib/Doctrine/ORM/Query/TreeWalkerChain.php
> +use Doctrine\ORM\AbstractQuery;
This should go before the `use function *` section.

2019-04-22 04:04 UTC, carusogabriel commented on lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php
>       * @param ParserResult $parserResult
You can remove these two phpDocs.

2024-12-29 07:05 UTC, closed without merging