phpstorm meta
doctrine/doctrine2 pull request #7676
Opened 2019-04-09 18:13 UTC by MartkCz

Supports only few methods:

# Parameter enums

`Doctrine\ORM\EntityManager::find(X)`
`Doctrine\ORM\EntityManagerInterface::lock(_,_,X)`
`Doctrine\ORM\EntityManagerInterface::newHydrator(X)`

`Doctrine\ORM\AbstractQuery::getResult(X)`
`Doctrine\ORM\AbstractQuery::execute(X)`
`Doctrine\ORM\AbstractQuery::setParameter(_,_,X)`
`Doctrine\ORM\AbstractQuery::setFetchMode(,,X)`
`Doctrine\ORM\AbstractQuery::setHydrationMode()`

`Doctrine\ORM\QueryBuilder::getDQLPart(X)`
`Doctrine\ORM\QueryBuilder::resetDQLPart(X)`
`Doctrine\ORM\QueryBuilder::setCacheMode(X)`
`Doctrine\ORM\QueryBuilder::add(X)`

`Doctrine\ORM\Query::setCacheMode(X)`

# Return enums

`Doctrine\ORM\QueryBuilder::getType()`
`Doctrine\ORM\QueryBuilder::getCacheMode()`
`Doctrine\ORM\QueryBuilder::getState()`

`Doctrine\ORM\Query::getCacheMode()`

`Doctrine\ORM\AbstractQuery::getHydrationMode()`

# Return types
`Doctrine\Common\Persistence\ObjectManager::find(X)`

`Doctrine\ORM\EntityManagerInterface::copy(X)`
`Doctrine\ORM\EntityManagerInterface::getReference(X)`
`Doctrine\ORM\EntityManagerInterface::getPartialReference(X)`
`Doctrine\ORM\EntityManagerInterface::merge(X)`

# Preview

![image](https://user-images.githubusercontent.com/10145362/55824268-d5b5c600-5b03-11e9-998b-3a20f20fdcc9.png)

![image](https://user-images.githubusercontent.com/10145362/55824281-dc443d80-5b03-11e9-8ed7-086be7ca3fda.png)

2019-04-09 19:36 UTC, greg0ire commented
I'm against putting IDE-specific files in Doctrine repositories… have you considered [creating a plugin](https://github.com/artspb/phpstorm-library-plugin) instead?

2019-04-09 19:51 UTC, Majkl578 requested changes
Fully agree with @greg0ire.

2019-04-09 20:57 UTC, Ocramius commented
I'm mostly for these changes (for some of these APIs), but I'd first need to know whether these meta files are actually used when located in a subpath: as far as I know, they need to live in your project root directory.

2019-04-09 21:00 UTC, greg0ire commented
@Ocramius https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

> By using example metadata below It can reside anywhere, but we recommend using .phpstorm.meta.php file in project root.

2019-04-09 21:22 UTC, Ocramius commented
And only one of these, or multiple ones?

2019-04-09 21:33 UTC, greg0ire commented
From the same page:

> 2016.2 + -> you can have multiple separate files in FOLDER named `.phpstorm.meta.php`

2019-06-17 11:42 UTC, mabar commented
@Ocramius `.phpstorm.meta.php` files in vendor work. I tested it with [nette/utils](https://github.com/nette/utils/blob/master/.phpstorm.meta.php) and got correct typehints.

2019-08-24 12:19 UTC, Ocramius commented
I'd like to respawn this: I've successfully integrated this in https://github.com/sebastianbergmann/phpunit/pull/3708, and it is a net gain for all downstream consumers, with no negative impact (as far as I know).

What I'd rather say is that we should keep it minimal: less constants, only cover (very) commonly used API, remove enums. The important bits are certainly `getRepository`, `find` and so on.

2022-05-11 09:04 UTC, derrabus commented
We're doing some housekeeping on the 3.0.0 milestone. Since nobody seems to be actively working on this topic I'm removing this PR from the 3.0.0 milestone. I you want to pick up the work, please target the ORM's next feature release (currently 2.13.0) instead.

2024-12-29 03:10 UTC, closed without merging