Add info on Criteria missing methods
doctrine/doctrine2 pull request #7705
Opened 2019-05-08 21:37 UTC by voltel

Add info from StackOverflow post on missing "isNotNull" and "isLike" methods.

2019-05-09 09:32 UTC, SenseException requested changes
Thank you for your contribution.

The `Criteria` class is part of the Doctrine Collections project/repository and information about it should be written in the [Doctrine Collections documentation](https://www.doctrine-project.org/projects/doctrine-collections/en/current/expression-builder.html#expression-builder). The methods there lack a description you offer in this PR, which is why I would appreciated it if you could put the descriptions as a new PR in [doctrine/collections](https://github.com/doctrine/collections).

Please don't use terms like "may be changed in future versions" because software is always changing and a documentation is about "what currently is" and not "what might be". Don't write function names as code that don't exist in a documentation.

* Please move descriptions of the `Criteria` methods to the collections documentation (new PR).
* Put a link to the doctrine/collections documentation I provided earlier here to prevent redundancy between documentations of different Doctrine projects. This ORM PR of yours will only add the referring link to the doctrine/collections documentation with a hint like "for more information about Criteria (and so on)".

2019-05-27 23:38 UTC, Ocramius requested changes

2019-05-27 23:38 UTC, Ocramius commented on docs/en/reference/working-with-associations.rst
> +Unfortunately for *Criteria::expr()->notLike()* and the other LIKE variants, the \Doctrine\Common\Collections\ExpressionBuilder used by Criteria does not support them.
Do we have an issue for this?

2019-05-27 23:38 UTC, Ocramius commented on docs/en/reference/working-with-associations.rst
> +   Read this StackOverflow post(https://stackoverflow.com/questions/26653651/collections-criteriaexpr-isnotnull-and-notlike) for filtering collections.
Unlikely to be added here - instead, we should expand this as docs in here, if relevant.

2019-05-28 04:43 UTC, Fedik commented on docs/en/reference/working-with-associations.rst
> +Unfortunately for *Criteria::expr()->notLike()* and the other LIKE variants, the \Doctrine\Common\Collections\ExpressionBuilder used by Criteria does not support them.
even a pull request #1219

2019-05-28 06:32 UTC, greg0ire requested changes

2019-05-28 06:32 UTC, greg0ire commented on docs/en/reference/working-with-associations.rst
> +   To have an **is not null** that acts like a *Criteria::expr()->isNotNull('field')* you can use
I think you miss 2 words here:

To have an **is not null** $word1 that acts like a *Criteria::expr()->isNotNull('field')* $word2 you can use

Also, a colon at the end would be nice IMO

2019-05-28 06:32 UTC, greg0ire commented on docs/en/reference/working-with-associations.rst
> +   $collection->matching($criteria->where($expr->neq('field', null)));
Does this php code block render inside the note?

2019-05-28 06:32 UTC, greg0ire commented on docs/en/reference/working-with-associations.rst
> +   To have an **is not null** that acts like a *Criteria::expr()->isNotNull('field')* you can use
Also, please use double backticks around pieces of code

2019-05-28 06:32 UTC, greg0ire commented on docs/en/reference/working-with-associations.rst
> +For the *Criteria::expr()->like()* functionality, **Criteria::expr()->contains('property', 'value')** is the equivalent of the SQL property LIKE %value%. However it does not allow for changing to val
```suggestion
For the ``Criteria::expr()->like()`` functionality, ``Criteria::expr()->contains('property', 'value')`` is the equivalent of the SQL syntax ``LIKE %value%``. However it does not allow for changing to `value%` or `%value` (may be changed in future versions).
```

2019-05-28 06:32 UTC, greg0ire commented on docs/en/reference/working-with-associations.rst
> +Unfortunately for *Criteria::expr()->notLike()* and the other LIKE variants, the \Doctrine\Common\Collections\ExpressionBuilder used by Criteria does not support them.
```suggestion
Unfortunately for ``Criteria::expr()->notLike()`` and the other ``LIKE`` variants, the ``\Doctrine\Common\Collections\ExpressionBuilder`` used by Criteria does not support them. 
```

2024-12-29 03:10 UTC, closed without merging