Prevents unexpected errors from bubbling up when attempting to
doctrine/doctrine2 pull request #7716
Opened 2019-05-22 08:22 UTC by gargoyle

autodiscover a cache provider.

The worst case scenario for this situation is when the cache extension *is* installed, but the service is not running on the localhost. For example, our app was attempting to setup doctrine as follows:-

```php
            $config = Setup::createAnnotationMetadataConfiguration([
                __DIR__ . DIRECTORY_SEPARATOR,
            ], $isDevMode);

            if ($isDevMode) {
                // In development we don't want anything being cached for longer than a single request.
                $cache = new ArrayCache();
            } else {
                // Allow Doctrine to cache queries and metadata using Redis
                $redisCredentials = $this->getRedisCredentials();

                $redis = new \Redis();
                $redis->connect((string)$redisCredentials->getHost(), $redisCredentials->getPort()->value());
                $redis->setOption(\Redis::OPT_PREFIX, 'AUTHAPI:' . $this->getAppVersion() . ':');

                $cache = new \Doctrine\Common\Cache\RedisCache();
                $cache->setRedis($redis);
            }

            $config->setQueryCacheImpl($cache);
            $config->setResultCacheImpl($cache);
            $config->setMetadataCacheImpl($cache);
>setResu
```

Given that the error message in our stack trace was:-

```
PHP Warning:  Redis::connect(): connect() failed: Connection refused in /var/www/vhosts/auth-api/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php on line 185
PHP Fatal error:  Uncaught RedisException: Redis server went away in /var/www/vhosts/auth-api/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:28
```

It took us a long time to discover that it was the call to `Setup::createAnnotationMetadataConfiguration` which was attempting to create a connection to a local redis instance which doesn't exist (We're using ElastiCache on AWS).

An alternate approach might be to throw a more helpful error message.

2019-05-22 09:50 UTC, greg0ire commented
> An alternate approach might be to throw a more helpful error message.

I would like that approach way better, because the attempt to connect will still be there and waste time.

2019-05-22 09:51 UTC, greg0ire requested changes
Please create a new exception class just for this, with a clear error message. Also, I think that feature is bad and should be deprecated.

2019-05-22 09:51 UTC, greg0ire commented on lib/Doctrine/ORM/Tools/Setup.php
> +            For backwards-compatability, attempt to create to a caching provider with
```suggestion
            For backwards-compatability, attempt to create a caching provider with
```

2019-05-22 09:51 UTC, greg0ire commented on lib/Doctrine/ORM/Tools/Setup.php
> +        } catch (\Exception $ex) {
```suggestion
        } catch (\Throwable $ex) {
```

2019-05-22 10:27 UTC, gargoyle commented
If you want to keep it fully BC, you are going to have to attempt the connections anyway to allow for the cases where it might have worked.

I'll see what I can do from just the internals of this class. I really have no knowledge about the other internal workings of Doctrine.

2019-05-22 11:00 UTC, Ocramius requested changes
I'd probably deprecate any public API on this class that is also leading to that `private` method to be called. This kind of defaults cannot be changed easily (sneaky and very problematic BC break), and defaults like these would be rejected with the current code review process that we have.

Deprecation for 2.x, and removal for 3.x would be best.

2019-07-11 09:38 UTC, gargoyle commented
I've wired up a custom exception. This should be the closest to BC as possible - Instead of a PHP fatal error a custom exception is thrown.

I have not marked anything as deprecated because all but one of the public methods lead to `createCacheInstance` being called and I do not know enough about Doctrine to figure out what the proposed alternative should be.

I think someone else will need to pick-up if more needs to be done.

Hope this helps. :-)

2024-12-28 03:04 UTC, closed without merging