Fix for TransientMetadata on joined subclass
doctrine/doctrine2 pull request #7828
Opened 2019-09-24 02:05 UTC by andrews05

This PR changes JoinedSubclassPersister to check for and skip TransientMetadata properties while inserting. This prevents an exception being thrown if a non-ORM property is declared on a joined subclass.
Fixes #7824.

2019-09-25 19:27 UTC, SenseException requested changes
Thank you for your test case and your first attempt to fix the issue of #7827 

Can you please fix the coding style issues that are listed in travis.ci: https://travis-ci.org/doctrine/orm/jobs/588738823?

It also seems that your first try for a fix broke some other tests.

2019-09-25 20:46 UTC, andrews05 commented
Thanks, I've fixed the coding style. I'm not too familiar with travis, however I'm pretty sure the other test results are unchanged from before and after my fix. Are you able to tell if there's anything that has broken as a result of this change?

2019-09-29 18:54 UTC, SenseException requested changes
Thank you for the fixes. Some of the tests fail, but are temporary excluded from a successful build. I'm not sure about those but it might have something to do with the FK constraints errors.

Can you please be more specific with your commit messages of tests and coding styles? "Add tests" and "Fix CS" are too generic.
https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches

2019-10-01 23:09 UTC, andrews05 commented
@SenseException sure, I've reworded them now.

2019-10-03 19:47 UTC, SenseException submitted a review, later dismissed

2019-10-03 20:38 UTC, greg0ire commented
Please squash both of your commits together, as there would be no reason to revert one and not revert the other too. When doing so, please use the following as a commit message:

```
Skip transient metadata while inserting

This prevents an exception being thrown if a non-ORM property is declared on a joined subclass.
Fixes #7824.
```

2019-10-03 21:12 UTC, andrews05 commented
@greg0ire sure, done.

2019-10-03 21:22 UTC, greg0ire approved these changes

2019-10-08 20:57 UTC, SenseException approved these changes

2019-11-15 05:14 UTC, guilhermeblanco approved these changes
LGTM

2019-11-15 05:14 UTC, merged