UnitOfWork::clear() misses $eagerLoadingEntities
doctrine/doctrine2 pull request #7869
Opened 2019-10-15 21:54 UTC by BenMorel

AFAICS, eager loading entities should be cleared as well when the UnitOfWork is cleared.

Actually, this is [already the case](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L1982) on `master`!

2019-10-15 22:05 UTC, greg0ire commented
`phpcs` has a weird complaint I don't understand… can you try running `vendor/bin/phpcbf`?

2019-10-15 22:34 UTC, BenMorel commented
I'm not sure why this happens either... Locally, `phpcs` reports, and `phpcbf` fixes, thousands (!) of CS issues.

I'm not familiar with `phpcs`, but I suspect from the command:

    php git-phpcs.phar origin/$TRAVIS_BRANCH...$TRAVIS_PULL_REQUEST_SHA

that it only reports issues on the line(s) modified by the PR. And due to the surrounding lines, there is not much I can do to fix this.

2019-10-16 05:45 UTC, greg0ire commented
Maybe you could try aligning all equal signs, including in the surrounding lines?

2019-10-16 08:09 UTC, BenMorel commented
Let's try this!

2019-10-16 08:37 UTC, greg0ire commented
Hey! That actually worked! :)

2019-10-16 08:42 UTC, greg0ire commented
Original commit: d070fc62a76cfe7b9ae35c3236335ab888762833

2019-10-16 08:42 UTC, greg0ire submitted a review, later dismissed

2019-10-16 08:44 UTC, greg0ire commented
The commit above contains a similar change for `$persisters`, should it be applied too?

2019-10-16 08:46 UTC, BenMorel commented
I have unfortunately no idea. For sure anything that contains a reference to an entity must be cleared, hence this PR, for the rest I'm not the right person to ask ;)

2019-10-16 09:04 UTC, greg0ire commented
Let's wait for feedback from contributors that know the UOW better than I do.

2019-10-16 10:31 UTC, lcobucci requested changes
@BenMorel thanks for the patch. The fix is 100% valid but we need a test to be able to get it merged :+1:

2019-10-16 11:25 UTC, BenMorel commented
@lcobucci Adding a test does not look like a trivial task, as there is no setter/getter for `$eagerLoadingEntities`.

Suggestions:

- test using reflection 🤢
- side-test using `triggerEagerLoads()`; this would require a complex setting, where you have to somehow set up an eager loading entity, and check that its `EntityPersister` is not invoked when calling `triggerEagerLoads()` after `clear()`; *really* not trivial, in comparison to the fix!

2019-10-20 20:05 UTC, SenseException commented
Suggestion: You could use an EntityManager in a functional test to setup eagerloading entities and test the clear-method of the UOW.

2019-11-14 21:44 UTC, ostrolucky commented
Test case added

2019-11-14 21:54 UTC, BenMorel commented
@ostrolucky Thank you!

2019-11-14 21:56 UTC, greg0ire approved these changes

2019-11-15 05:26 UTC, guilhermeblanco approved these changes
This was an issue I found when i was working on ephemeral unit of work support. It also helps on freeing resources as eager loaded entities hang there forever. Patch on its own is great.

2019-11-15 05:27 UTC, merged

2019-11-15 07:33 UTC, ostrolucky commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH7869Test.php
> +    public function testDQLDeferredEagerLoad()
I forgot to rename test case 😞 Let me know if I Should create new PR with just this change