remove rsmBuilder restriction on joined table inheritance schemes
doctrine/doctrine2 pull request #7878
Opened 2019-10-24 03:52 UTC by jnfry

See https://github.com/doctrine/orm/issues/7151#issuecomment-545289066

2019-10-30 12:18 UTC, SenseException submitted a review, later dismissed
In would like to see another reviewer take a look at this PR. I'm not sure if the tests are sufficient for this change.

2019-11-30 23:37 UTC, beberlei requested changes
This is missing a test in `LazyCriteriaCollectionTest` that triggers the code in `ManyToManyPersister::loadCriteria` with a joined table inheritance entity example.

2019-11-30 23:37 UTC, beberlei commented on tests/Doctrine/Tests/ORM/Functional/NativeQueryTest.php
> +     * @group rsm-sti
```suggestion
     * @group GH-7151
```

2019-11-30 23:37 UTC, beberlei commented on tests/Doctrine/Tests/ORM/Functional/NativeQueryTest.php
> +     * @group rsm-sti
```suggestion
     * @group GH-7151
```

2020-01-21 11:48 UTC, chq81 commented
@jnfry Hey there. Thanks for your work. Did you have the possibility to look over the missing tests?

2020-05-01 05:04 UTC, jnfry commented
Hey there @chq81, sorry for taking so long to get back to this.

I've had a look at what @beberlei is asking and am unsure what to do. The current `LazyCriteriaCollectionTest` appears to effectively cover the responsibilities of the class (ie. only calling methods on the `Persister` when necessary and caching the result). It doesn't care which type of `Persister` it wraps, and adding a test which asserts it calls `Persister::loadCriteria()` would not test the change I've made.

I agree that there likely needs to be more tests to cover this change, but the `LazyCriteriaCollection` appears to be unaffected. Did you perhaps mean a different test case @beberlei?

I think adding a PersisterTest with a join table inheritance example would be better? Though I'm not sure which of the `*PersisterTest`'s to add this to. If you could perhaps elaborate on what exactly needs to be tested that would greatly help me out. This is my first contribution to Doctrine so I'm a bit lost :sweat_smile:

2020-05-22 21:18 UTC, SenseException commented
@jnfry The current tests are covering a `ManyToOne` relation case with `CompanyEvent` / `CompanyAuction`. Please take a look at the content of the mapping of these classes. What's now needed are `ManyToMany` cases.

2020-12-06 18:36 UTC, beberlei commented
@jnfry your change suggests this just works, but I am not convinced. What I am missing here is a functional test of the scenario end to end. In one of the joined table inheritance tests you need to add a test case for ->matching that triggers this code.

Your tests at the moment only check small things on ResultSetMapping, but what if the contents of the RSM are wrong so that *other* parts of the system fail, mainly the persisters?

2021-03-11 01:16 UTC, closed without merging