Updated composer.json and made unit tests run, not necessarily pass...
doctrine/doctrine2 pull request #7921
Opened 2019-11-25 02:22 UTC by guilhermeblanco

Current status as of first commit... 

<img width="574" alt="Screen Shot 2019-11-24 at 9 19 52 PM" src="https://user-images.githubusercontent.com/208883/69507410-6e1c8180-0f00-11ea-8078-65b7e856bda7.png">

2019-11-25 13:51 UTC, lcobucci requested changes
@guilhermeblanco a few minor things here, thanks for making this more visible

2019-11-25 13:51 UTC, lcobucci commented on composer.json
> +        "ext-pdo": "*",
What's the need for keeping PDO around?

2019-11-25 13:51 UTC, lcobucci commented on composer.json
> +        "doctrine/dbal": "dev-master",
using `3.0.x-dev` should help us prevent issues with branch dancing (not that it should happen again)

2019-11-25 13:51 UTC, lcobucci commented on composer.json
> +        "phpstan/phpstan": "~0.11",
I'd say using `^` is more appropriate here to avoid having phpstan upgraded with lots of unintended CI breaks

2019-11-25 13:51 UTC, lcobucci commented on tests/Doctrine/Tests/Mocks/ConnectionMock.php
>      private $lastInsertId = 0;
Should have a string as default then

2019-11-25 13:51 UTC, lcobucci commented on tests/Doctrine/Tests/Mocks/HydratorMockStatement.php
> +        return;
This should be dropped

2019-11-26 18:34 UTC, guilhermeblanco commented
Current state 
![Screen Shot 2019-11-26 at 1 33 27 PM](https://user-images.githubusercontent.com/208883/69661968-6cae9e80-1051-11ea-8b3d-4958167fad28.png)

2020-05-01 18:17 UTC, merged