Improve docs: INSTANCE OF needs class metadata as parameter value
doctrine/doctrine2 pull request #7963
Opened 2019-12-23 10:02 UTC by flaushi

…r value for the INSTANCE OF DQL expression

As discussed on slack and in relation to https://github.com/doctrine/orm/issues/6483, one could clarify in the docs that it's not enough to just bind a class name by its FQCN.

2019-12-23 10:06 UTC, malarzm commented on docs/en/reference/dql-doctrine-query-language.rst
> +    To use a class as parameter, you have to bind it's class metadata: ``$query->setParameter(0, $em->getClassMetadata(CompanyEmployee::class);``.
it should be `its` as it's a possessive

2020-01-01 15:37 UTC, greg0ire commented
Please squash your commits and please improve your commit message according to [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches).

Also, please associate your email address with your Github account, or change the
email in your commits to an address already associated with it. If you do not
want to expose your personal email address, you may use
`flaushi@users.noreply.github.com`, that way we can still reach you through Github.
Additionally, you will get credit for this contribution on your Github profile.

2020-01-01 15:41 UTC, greg0ire commented
Also, this should probably target 2.7 or 2.8.x otherwise your changes will not appear in the docs people actually read until 3.0 is released.

2020-01-02 22:59 UTC, flaushi commented
@greg0ire Yes, that should be done of course. So should I create a new fork of the branch '2.7'?

2020-01-02 23:19 UTC, flaushi commented
I applied my note to a branch basing on 2.7, and pushed it here https://github.com/flaushi/orm/tree/note-instance-of (commits squashed, email address changed)

Can you change the merge request or should I start a new one?

2020-01-03 12:54 UTC, greg0ire commented
You can reset your `master` branch to `note-instance-of` and force push. It will be confusing, but I guess this is why you should not use `master` when making a PR. Once it is done, click the `Edit` button and change the target branch. Once this is merged, I recommend you delete your `master` branch, that way it will be hard for you to commit on it.

2020-01-03 13:37 UTC, flaushi commented
I am too unexperienced with this git s**t. Argh, now I have all my messages twice 😩.
Can't I just open a new PR for the note-instance-of branch? I guess it's also better because it already targets 2.7?

2020-01-03 13:41 UTC, greg0ire commented
Please just `git checkout master && git reset --hard note-instance-of && git push --force`

2020-01-03 14:03 UTC, flaushi commented
I think that's it. One commit, with email address. Anything else required from my side? You spoke about merging...🤷‍♂️

2020-01-03 14:06 UTC, greg0ire commented
Your commit does not seem to start from 2.7

2020-01-03 14:07 UTC, greg0ire commented
If you can find your commit in the git history, try `git reset --hard 2785cde && git cherry-pick yourCommitHashHere && git push --force`

2020-01-03 14:08 UTC, greg0ire commented
I'm on the symfony-dev slack if you want to chat

2020-01-03 14:15 UTC, greg0ire commented
It looks sane now :)

2020-01-03 22:21 UTC, ostrolucky submitted a review, later dismissed

2020-01-03 22:26 UTC, greg0ire requested changes

2020-01-03 22:26 UTC, greg0ire commented on docs/en/reference/dql-doctrine-query-language.rst
> +    $query->setParameter(1, $em->getClassMetadata(CompanyEmployee::class);
```suggestion
    $query->setParameter(1, $em->getClassMetadata(CompanyEmployee::class));
```

2020-01-03 22:26 UTC, greg0ire commented on docs/en/reference/dql-doctrine-query-language.rst
> +    To use a class as parameter, you have to bind its class metadata: ``$query->setParameter(0, $em->getClassMetadata(CompanyEmployee::class);``.
```suggestion
    To use a class as parameter, you have to bind its class metadata: 
    ``$query->setParameter(0, $em->getClassMetadata(CompanyEmployee::class);``.
```

2023-12-12 10:00 UTC, cs278 commented
What's needed to get this merged?

2023-12-12 13:15 UTC, greg0ire approved these changes

2023-12-12 13:15 UTC, greg0ire commented
One more approval I'd say.

2023-12-12 13:51 UTC, derrabus approved these changes

2023-12-12 13:51 UTC, merged