Added check for empty SELECT expression
doctrine/doctrine2 pull request #8010
Opened 2020-02-02 20:49 UTC by oleg-andreyev

While working on https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/938 noticed that it's possible to generate DQL (eventually a SQL) with an empty SELECT expression which should not be possible

2020-02-02 22:07 UTC, SenseException requested changes
What about having a full select of all properties (`select('e')`) in those cases instead of throwing an exception? Did you run into this behaviour because you expect that it would work when `select()` is omitted?

2020-02-03 10:41 UTC, oleg-andreyev commented
@SenseException 
> Did you run into this behavior because you expect that it would work when select() is omitted?

This behavior is not expected. I've run into this while working tests for https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/938 and noticed that QueryBuilder does not emit any errors when I didn't define any `select()` and tried to generate DQL

2020-02-09 20:43 UTC, oleg-andreyev commented on lib/Doctrine/ORM/QueryBuilder.php
> +            throw new Query\QueryException('SELECT expression is required for building DQL');
done. I have updated other methods also.

2020-02-09 21:37 UTC, SenseException commented
Is it possible to add the select if it was forgotten? Or are there disadvantages if we would do so?

2020-02-11 21:05 UTC, oleg-andreyev commented
@SenseException what do you mean by "add the select" - automatically add `*` and select everything?

2020-02-12 14:43 UTC, SenseException commented
> What about having a full select of all properties (select('e')) in those cases instead of throwing an exception?

Yes, what would be the disadvantages of that?

2020-02-12 14:47 UTC, oleg-andreyev commented
@SenseException I think it's doable but it may be unintuitive for developers to understand why "SELECT * FROM" was executed.

2024-12-26 03:06 UTC, closed without merging