use unitOfWork::identityFlattener
doctrine/doctrine2 pull request #8020
Opened 2020-02-13 16:06 UTC by youssefbenhssaien

# Modifications
- Use UnitOfWork instanciated identityFlattener instead of reinstanciate it in `BasicEntityPersister`.

2020-02-13 21:03 UTC, SenseException requested changes

2020-02-13 21:03 UTC, SenseException commented on lib/Doctrine/ORM/UnitOfWork.php
> +    public function getIdentifierFlattener(): IdentifierFlattener
```suggestion
    public function getIdentifierFlattener() : IdentifierFlattener
```

Also please remove the method doc-block to fix the coding style issues mentioned in the travis-ci build.

2020-02-14 19:12 UTC, greg0ire commented
Hi! Can you please explain why this is needed? It makes the public API of UnitOfWork bigger, not sure we want that.

2020-02-15 22:17 UTC, youssefbenhssaien commented
@greg0ire for two reasons :
- Working on an already instantiated IdentityFlattener instead doing it twice.
- Allow hacking UnitOfWork to add some custom Persister (like BulkInsertPersister on MySQL) since there is no way to custom persisters.

2020-02-16 19:23 UTC, greg0ire commented
> Allow hacking UnitOfWork to add some custom Persister (like BulkInsertPersister on MySQL) since there is no way to custom persisters.

Can you please elaborate on this? It's not obvious for me.

2020-02-17 09:02 UTC, youssefbenhssaien commented
> > Allow hacking UnitOfWork to add some custom Persister (like BulkInsertPersister on MySQL) since there is no way to custom persisters.
> 
> Can you please elaborate on this? It's not obvious for me.

UnitOfWork creates a Persister per inheritance type (cannot add a custom persister), Adding a custom BulkUnitOfWork inherit from UnitOfWork (this is not a good solution but had to) then return the new custom persister (BulkInsertPersister)
> Using ReflectionApi to bypass many inheritance limits (Some class constructs excpect EntityManager instead of EntityManagerInterface + Others expect instance of UnitOfWork instead the custom BulkUnitOfWork....)

This is a basic example : https://github.com/youssefbenhssaien/doctrine-bundle/blob/master/src/Doctrine/BulkUnitOfWork.php

> This example (only experimental) works only with one case when persisting an entity without inheritance Map.

2020-02-17 10:43 UTC, greg0ire commented
Thanks I understand better now. Here is a related issue: https://github.com/doctrine/orm/issues/4767

2020-02-17 13:55 UTC, youssefbenhssaien commented
> Thanks I understand better now. Here is a related issue: #4767

Thank you, but still not resolved and cannot inject a custom persister ! the only workaround is doing it with Reflection (but with BulkInsert it is more complicated)

2020-02-17 20:55 UTC, greg0ire commented
I know it's not resolved, I was including here in case other maintainers were wondering why there is no support for custom persisters, and maybe give it another look.

IMO there could maybe be a `PersisterRegistry` object that would be configurable and be able to provide the right persister for each case.

I'm not super sure about that design, but I don't think allowing hacks that involve inheritance + making public things that should probably not be is the way.

I hope a more seasoned ORM maintainer sees this and gives a better recommendation regarding what should be done here.

2024-12-24 03:06 UTC, closed without merging