Optimize paginator removing useless left joins in subselect
doctrine/doctrine2 pull request #8073
Opened 2020-03-17 16:07 UTC by xavren

Hi

Here is a draft of what cool be a huge performance boost for Paginator

Actually, to optimize database db queries, we could join nested fields but, when using it with the paginator and some filter, the distinct subselect injected suffer of all that left joined data that could be removed on that subselect returning ids

I am not hoping that could be merge like this but it opens the discussion

Thanks in advance for your opinion and tips

2020-03-18 22:54 UTC, SenseException commented
Thank you for your draft. Have you tested the performance impact and can provide test-code where we can see the impact of your new Walker?

2020-03-19 13:50 UTC, xavren commented
Hi @SenseException,

I just wrote some test and as you imagine, it is actually difficult to give a number for performance impact because it depends of the database set

I tested it on a project and got about 70% performance boost using this walker, because database have some thousands rows now and growing and fixtures does not represent production data volume, it's too bad that Paginator slow down queries with data that are not useful

2020-03-24 14:53 UTC, neverdane commented
Great job! Perhaps you could just add a configuration to enable this walker at will?

2020-03-24 14:58 UTC, xavren commented
Here is a real usage case

570.86 ms vs 138.06 ms = 66 % performance gain

Without removing left joins: 570.86 ms
```
SELECT DISTINCT p0_.id                                            AS id_0,
                CASE WHEN p0_.public_id IS NULL THEN 0 ELSE 1 END AS sclr_1,
                p0_.public_id                                     AS public_id_2,
                p0_.id                                            AS id_3
FROM property p0_
         LEFT JOIN property_file p1_ ON p0_.id = p1_.property_id
         LEFT JOIN file f2_ ON p1_.file_id = f2_.id
         INNER JOIN program p3_ ON p0_.program_id = p3_.id
         INNER JOIN developer d4_ ON p3_.developer_id = d4_.id
         INNER JOIN address a5_ ON p3_.address_id = a5_.id
         LEFT JOIN city c6_ ON a5_.city_id = c6_.id
         LEFT JOIN department d7_ ON c6_.department_id = d7_.id
WHERE p0_.id IN (SELECT p8_.id
                 FROM property p8_
                          LEFT JOIN property_file p9_ ON p8_.id = p9_.property_id
                          LEFT JOIN file f10_ ON p9_.file_id = f10_.id
                          LEFT JOIN program p11_ ON p8_.program_id = p11_.id
                          LEFT JOIN developer d12_ ON p11_.developer_id = d12_.id
                          LEFT JOIN address a13_ ON p11_.address_id = a13_.id
                          LEFT JOIN city c14_ ON a13_.city_id = c14_.id
                          LEFT JOIN department d15_ ON c14_.department_id = d15_.id
                 WHERE p11_.validation_status IN (?)
                   AND p8_.status IN (?)
                   AND p11_.status IN (?))
ORDER BY sclr_1 DESC, p0_.public_id ASC, p0_.id ASC
LIMIT 30
OFFSET
30
Parameters:
[▼
  [▼
    "1"
    "2"
  ]
  [▼
    1
    2
  ]
  [▼
    1
  ]
]
View formatted query    View runnable query    Hide query explanation
Limit  (cost=13291.48..13291.56 rows=30 width=25)
  ->  Sort  (cost=13291.41..13402.69 rows=44514 width=25)
        Sort Key: (CASE WHEN (p0_.public_id IS NULL) THEN 0 ELSE 1 END) DESC, p0_.public_id, p0_.id
        ->  HashAggregate  (cost=11309.00..11754.14 rows=44514 width=25)
              Group Key: CASE WHEN (p0_.public_id IS NULL) THEN 0 ELSE 1 END, p0_.public_id, p0_.id, p0_.id
              ->  Hash Semi Join  (cost=6977.38..10759.46 rows=54954 width=25)
                    Hash Cond: (p0_.id = p8_.id)
                    ->  Hash Join  (cost=2304.36..5186.79 rows=109820 width=17)
                          Hash Cond: (p3_.address_id = a5_.id)
                          ->  Hash Join  (cost=2263.86..4856.79 rows=109820 width=21)
                                Hash Cond: (p3_.developer_id = d4_.id)
                                ->  Hash Join  (cost=2258.07..4527.82 rows=109820 width=25)
                                      Hash Cond: (p0_.program_id = p3_.id)
                                      ->  Hash Right Join  (cost=2194.57..4175.06 rows=109820 width=21)
                                            Hash Cond: (p1_.property_id = p0_.id)
                                            ->  Seq Scan on property_file p1_  (cost=0.00..1692.20 rows=109820 width=8)
                                            ->  Hash  (cost=1638.14..1638.14 rows=44514 width=21)
                                                  ->  Seq Scan on property p0_  (cost=0.00..1638.14 rows=44514 width=21)
                                      ->  Hash  (cost=47.67..47.67 rows=1267 width=12)
                                            ->  Seq Scan on program p3_  (cost=0.00..47.67 rows=1267 width=12)
                                ->  Hash  (cost=5.35..5.35 rows=35 width=4)
                                      ->  Seq Scan on developer d4_  (cost=0.00..5.35 rows=35 width=4)
                          ->  Hash  (cost=28.00..28.00 rows=1000 width=8)
                                ->  Seq Scan on address a5_  (cost=0.00..28.00 rows=1000 width=8)
                    ->  Hash  (cost=4217.60..4217.60 rows=36434 width=4)
                          ->  Hash Join  (cost=2092.37..4217.60 rows=36434 width=4)
                                Hash Cond: (p8_.program_id = p11_.id)
                                ->  Hash Right Join  (cost=2027.86..4008.36 rows=54954 width=8)
                                      Hash Cond: (p9_.property_id = p8_.id)
                                      ->  Seq Scan on property_file p9_  (cost=0.00..1692.20 rows=109820 width=8)
                                      ->  Hash  (cost=1749.43..1749.43 rows=22275 width=8)
                                            ->  Seq Scan on property p8_  (cost=0.00..1749.43 rows=22275 width=8)
                                                  Filter: (status = ANY ('{1,2}'::integer[]))
                                ->  Hash  (cost=54.00..54.00 rows=840 width=12)
                                      ->  Seq Scan on program p11_  (cost=0.00..54.00 rows=840 width=12)
                                            Filter: ((validation_status = ANY ('{1,2}'::integer[])) AND (status = 1))
```

And removing left joins: 138.06 ms
```
SELECT DISTINCT p0_.id                                            AS id_0,
                CASE WHEN p0_.public_id IS NULL THEN 0 ELSE 1 END AS sclr_1,
                p0_.public_id                                     AS public_id_2,
                p0_.id                                            AS id_3
FROM property p0_
         INNER JOIN program p1_ ON p0_.program_id = p1_.id
         INNER JOIN developer d2_ ON p1_.developer_id = d2_.id
         INNER JOIN address a3_ ON p1_.address_id = a3_.id
WHERE p0_.id IN (SELECT p4_.id
                 FROM property p4_
                          LEFT JOIN program p5_ ON p4_.program_id = p5_.id
                 WHERE p5_.validation_status IN (?)
                   AND p4_.status IN (?)
                   AND p5_.status IN (?))
ORDER BY sclr_1 DESC, p0_.public_id ASC, p0_.id ASC
LIMIT 30
OFFSET
30
Parameters:
[▼
  [▼
    "1"
    "2"
  ]
  [▼
    1
    2
  ]
  [▼
    1
  ]
]
View formatted query    View runnable query    Hide query explanation
Limit  (cost=5013.01..5013.09 rows=30 width=25)
  ->  Sort  (cost=5012.94..5049.86 rows=14768 width=25)
        Sort Key: (CASE WHEN (p0_.public_id IS NULL) THEN 0 ELSE 1 END) DESC, p0_.public_id, p0_.id
        ->  HashAggregate  (cost=4355.25..4502.93 rows=14768 width=25)
              Group Key: CASE WHEN (p0_.public_id IS NULL) THEN 0 ELSE 1 END, p0_.public_id, p0_.id, p0_.id
              ->  Hash Join  (cost=2167.00..4207.57 rows=14768 width=25)
                    Hash Cond: (p1_.address_id = a3_.id)
                    ->  Hash Join  (cost=2126.50..4128.14 rows=14768 width=21)
                          Hash Cond: (p1_.developer_id = d2_.id)
                          ->  Hash Join  (cost=2120.71..4078.89 rows=14768 width=25)
                                Hash Cond: (p0_.program_id = p1_.id)
                                ->  Hash Semi Join  (cost=2057.20..3976.49 rows=14768 width=21)
                                      Hash Cond: (p0_.id = p4_.id)
                                      ->  Seq Scan on property p0_  (cost=0.00..1638.14 rows=44514 width=21)
                                      ->  Hash  (cost=1872.60..1872.60 rows=14768 width=4)
                                            ->  Hash Join  (cost=64.50..1872.60 rows=14768 width=4)
                                                  Hash Cond: (p4_.program_id = p5_.id)
                                                  ->  Seq Scan on property p4_  (cost=0.00..1749.43 rows=22275 width=8)
                                                        Filter: (status = ANY ('{1,2}'::integer[]))
                                                  ->  Hash  (cost=54.00..54.00 rows=840 width=4)
                                                        ->  Seq Scan on program p5_  (cost=0.00..54.00 rows=840 width=4)
                                                              Filter: ((validation_status = ANY ('{1,2}'::integer[])) AND (status = 1))
                     [...]

2020-03-24 15:00 UTC, xavren commented
@neverdane Thanks, is `query hints` a good way to configure that kind of features ?

2020-04-07 08:39 UTC, xavren commented
Hi !

I tested and figured that `Functions` like `BitAndFunction` will not work for detection due to custom accessor.

Is there an other/better way to find joins usages ?

Thanks

2020-04-14 06:50 UTC, xavren commented
Hi

I read AST and was wondering if looking for left joins usage could be a preg_match in DQL query ?

Have you an other way to do that ?

2020-04-23 09:44 UTC, xavren commented
Thanks @SenseException for the review request :)

Looking forward to suggestions with excitement !

2020-05-21 13:49 UTC, ostrolucky requested changes
We should probably also have some new Paginator tests. Also, please add type declarations everywhere where it's possible.

2020-05-21 13:49 UTC, ostrolucky commented on lib/Doctrine/ORM/Tools/Pagination/RemoveUselessLeftJoinsWalker.php
> +        if (! isset($AST->whereClause) || ! isset($AST->whereClause->conditionalExpression) || ! isset($AST->whereClause->conditionalExpression->simpleConditionalExpression)) {
```suggestion
        if (! isset($AST->whereClause, $AST->whereClause->conditionalExpression, $AST->whereClause->conditionalExpression->simpleConditionalExpression)) {
```

2020-05-21 13:49 UTC, ostrolucky commented on lib/Doctrine/ORM/Tools/Pagination/RemoveUselessLeftJoinsWalker.php
> +    private function removeUnusedJoins(SelectStatement $AST)
This feature takes care only about joins in subselect? Method should be renamed then, probably also whole class.

2020-05-21 13:49 UTC, ostrolucky commented on tests/Doctrine/Tests/ORM/Tools/Pagination/RemoveUselessLeftJoinWalkerTest.php
> +            'SELECT m0_.id AS id_0, m0_.title AS title_1, c1_.id AS id_2, a2_.id AS id_3, a2_.name AS name_4, m0_.author_id AS author_id_5, m0_.category_id AS category_id_6 FROM MyBlogPost m0_ WHERE
Coud you explain how does your feature work better? In all assertions I see select is being done on aliases that are missing in SQL, so this is not obvious.

2024-12-23 03:07 UTC, closed without merging