Update events.rst
doctrine/doctrine2 pull request #8257
Opened 2020-09-02 08:43 UTC by ThomasLandauer

Improved code formatting

2020-09-02 19:03 UTC, SenseException requested changes

2020-09-02 19:03 UTC, SenseException commented on docs/en/reference/events.rst
> +-  onClear - The onClear event occurs when the ``EntityManager#clear()`` operation is
```suggestion
-  onClear - The onClear event occurs when the ``EntityManager::clear()`` operation is
```

2020-09-03 08:50 UTC, ThomasLandauer commented on docs/en/reference/events.rst
> +   database ``INSERT`` operations. Generated primary key values are
I changed it to "the operation", cause it's "the" for the other events too.

2020-09-03 20:42 UTC, SenseException approved these changes

2020-09-03 20:44 UTC, merged

2020-09-03 20:44 UTC, SenseException commented
Thank you @ThomasLandauer