[GH-8818] Deprecate entity namespace short aliases.
doctrine/doctrine2 pull request #8820
Opened 2021-07-04 19:09 UTC by beberlei

This PR deprecates entity namespace short aliases as advertised in issue.

Fixes #8818

2021-07-05 07:12 UTC, greg0ire commented
Blocked by https://github.com/doctrine/orm/pull/8821

2021-07-05 08:13 UTC, greg0ire commented
Let's document this in `UPGRADE.md`? Also, the wrong branch is being targeted here.

2021-08-04 21:43 UTC, SenseException requested changes
https://github.com/doctrine/orm/blob/2.10.x/docs/en/reference/dql-doctrine-query-language.rst#terminals

AFAIK this seems the only occurrance of an alias in the docs. I think removing the last trails of aliases should be done with the deprecation.

2021-08-05 17:39 UTC, SenseException approved these changes

2021-08-05 17:49 UTC, merged

2021-08-05 17:50 UTC, greg0ire commented
Thanks @beberlei !