Allow params of function substring to also an expression function
doctrine/doctrine2 pull request #9018
Opened 2021-09-16 13:02 UTC by karstennilsen

This is something which should work:
```
 $qb->expr()->substring(
                    $qb->expr()->literal($var),
                    1,
                    $qb->expr()->length($qb->expr()->concat('cc', 'ndc'))
                )
```

2021-09-16 15:46 UTC, greg0ire commented
> Allow params of function substring to also an expression function

I think a word is missing :stuck_out_tongue:

2023-09-04 13:48 UTC, gmta commented
👍 According to the DQL EBNF, the 2nd and 3rd arguments to `::substring()` are indeed SimpleArithmeticExpressions and as such a subexpression should be possible.

2024-03-08 08:35 UTC, gmta commented
@greg0ire Can I help unblock this PR? It seems a simple enough change :-)

2024-03-09 10:27 UTC, greg0ire commented
Retargeted to 2.19.x. There is a conflict now, which needs to be fixed by @karstennilsen or by you in another PR.

2024-03-11 09:42 UTC, karstennilsen commented
> Retargeted to 2.19.x. There is a conflict now, which needs to be fixed by @karstennilsen or by you in another PR.

Should be fixed now. If there is anythin else needed, please let me know.

2024-03-11 09:59 UTC, greg0ire commented
It seems there are CI jobs failing. Please take a look at [this guide](https://www.doctrine-project.org/contribute/#dealing-with-checks-and-tools) for more on how to handle those.

2024-03-11 10:00 UTC, greg0ire commented
Also, I retargeted to 3.2.x since this MR does not improve compatibility with ORM 3. Sorry for not thinking of that sooner.

2024-03-13 15:50 UTC, karstennilsen commented
@greg0ire New version targets 3.2.x and should pass CI (tried it locally). Please approve 😊

2024-12-02 09:06 UTC, gmta commented
@greg0ire I think this can be merged as-is

2024-12-02 10:42 UTC, greg0ire approved these changes
Kinda BC-breaky, but I don't expect many people to extends that class.

2024-12-03 23:18 UTC, SenseException requested changes
I'd expect a test that covers a case with `Expr\Func` as arguments.

2025-03-11 03:10 UTC, closed without merging