Explaining the two major ways to register an event
doctrine/doctrine2 pull request #9102
Opened 2021-10-06 12:11 UTC by ThomasLandauer

Second attempt of https://github.com/doctrine/orm/pull/9097

2021-10-06 22:42 UTC, SenseException requested changes

2021-10-06 22:42 UTC, SenseException commented on docs/en/reference/events.rst
> +(see :ref:`Lifecycle Callbacks`)
You need to set the references atop the specific headlines like this:

```
.. _transitive-persistence:

Transitive persistence / Cascade Operations
-------------------------------------------
```

to be able to use something like

```
:ref:`transitive-persistence`
```

2021-10-06 22:53 UTC, ThomasLandauer commented on docs/en/reference/events.rst
> +(see :ref:`Lifecycle Callbacks`)
Thanks!

2021-10-07 20:58 UTC, SenseException approved these changes

2021-10-15 08:54 UTC, derrabus commented
@ThomasLandauer can you rebase on 2.10.x and resolve the conflict?

2021-10-15 11:53 UTC, ThomasLandauer commented
Closing in favor of https://github.com/doctrine/orm/pull/9128

2021-10-15 11:53 UTC, closed without merging