Merging Lifecycle Callbacks code samples for PHP + XML + YAML
doctrine/doctrine2 pull request #9159
Opened 2021-10-28 23:14 UTC by ThomasLandauer

IMO, the text I deleted just repeated things that are obvious in the example anyway.

I didn't change anything in the three code blocks - just merged them. GitHub Diff looks a little weird...

2021-10-29 22:10 UTC, SenseException requested changes

2021-10-29 22:10 UTC, SenseException commented on docs/en/reference/events.rst
> -event types are the ones listed in the previous Lifecycle Events section.
Can you please put the text below the code configuration block like you did with the annotation one?

2021-10-29 22:10 UTC, SenseException commented on docs/en/reference/events.rst
> -defined on your ``User`` model.
Can you please put the text below the code configuration block like you did with the annotation one?

2021-10-30 11:53 UTC, ThomasLandauer commented on docs/en/reference/events.rst
> -event types are the ones listed in the previous Lifecycle Events section.
I wanted to take care of this in another PR ;-) - now included it in the second commit here.

The larger problem I'm seeing is that the three code blocks were showing *different* events ;-) I now shortened the PHP block and made all three consistent.

About the specific (deleted) text: I think the example shows it all! The name of the functions, and that they need to be public. So all that's left is `@HasLifecycleCallbacks`, and that I included in the code block.

2021-11-02 22:13 UTC, SenseException commented on docs/en/reference/events.rst
> -event types are the ones listed in the previous Lifecycle Events section.
>  I think the example shows it all!

Maybe it is self-explaining. for the code blocks. Okay, let's keep it that way.

2021-11-02 22:13 UTC, SenseException approved these changes

2021-11-03 20:13 UTC, merged

2021-11-03 20:14 UTC, greg0ire commented
Thanks @ThomasLandauer !