Fixed array hydration
doctrine/doctrine2 pull request #9186
Opened 2021-11-11 12:02 UTC by LinasRam

Resetting `$this->_identifierMap` of base element children each time the new to-many relation is added to base element.

fixes #9185

2021-11-14 11:47 UTC, bhushan requested changes

2021-11-14 11:47 UTC, bhushan commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH9185Test.php
> +     * form CmsArticle a
```suggestion
     * from CmsArticle a
```

2021-11-14 11:47 UTC, bhushan commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH9185Test.php
> +     * Sometimes, the way DBMS is ordering rows is kinda random.
```suggestion
     * Sometimes, the way DBMS is ordering rows randomly.
```

2021-11-14 11:47 UTC, bhushan commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH9185Test.php
> +     * instead of correct elements.
```suggestion
     * instead of correct values.
```

2021-11-14 11:47 UTC, bhushan commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH9185Test.php
> +                        ['phonenumber' => '9876543210'],
JFI asking:

these values were returning null before right?

2021-11-14 11:50 UTC, bhushan commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH9185Test.php
> +                'p__phonenumber' => '9876543210', // Different order than in previous rows
```suggestion
                'p__phonenumber' => '9876543210', // Different order of phone number than in previous rows
```

2021-11-14 11:51 UTC, bhushan commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH9185Test.php
> +                'p__phonenumber' => '1234567890', // Different order than in previous rows
```suggestion
                'p__phonenumber' => '1234567890', // Different order of phone number than in previous rows
```

2021-11-14 12:05 UTC, bhushan commented on tests/Doctrine/Tests/ORM/Functional/Ticket/GH9185Test.php
> +     * join a.user u
```suggestion
     * join a.users u
```

2021-11-15 08:59 UTC, bhushan submitted a review, later dismissed
@greg0ire please review.. looks good to me

2021-11-15 17:16 UTC, greg0ire reviewed
2 questions: 

1. Why does this fix the bug? I understand what the bug is (great explanation BTW), but I don't understand why it happens.
2. Is this going to have consequences in terms of performance? I think the hydration is in the hot path of `doctrine/orm`, and I think resetting an array means loosing data. We have a benchmark to test that kind of thing: https://github.com/doctrine/orm/blob/2.10.x/tests/Doctrine/Performance/Hydration/SimpleQueryArrayHydrationPerformanceBench.php

2021-11-15 21:10 UTC, LinasRam commented
1. It's difficult to explain... You could comment out my code change and run my written test with debugger. Pay attention at `ArrayHydrator:135` when the phone number mapping is being set. After setting 'Article 1' phone number elements, you will get `$this->_identifierMap` values (I'm only adding `u.p` relationship here):
```
[
    'u.p' => [
        '|1' => [
            '|1234567890' => '0',
            '|9876543210' => '1',
        ],
    ],
]
```
So far, everything works as expected, but then comes 'Article 2' phone numbers in different order than before. If `$this->_identifierMap['u.p']['|1']` values are not reset, algorithm gets array index of `9876543210` number from mapping. Index is `1`, but on `line 135` `|9876543210` value in `$this->_identifierMap` will be overridden to `0` and mapping will look like this:
```
[
    'u.p' => [
        '|1' => [
            '|1234567890' => '0',
            '|9876543210' => '0',
        ],
    ],
]
```
Two array elements with different keys, but same values. That will cause unexpected behavior in `updateResultPointer` method called on `line 154`. Then, on `line 268` if statement will be valid with `$index = 1`, but `$coll` will only have one element as the only the first phone number was set till this point (second phone number will be set on next iteration):
```
$coll = [
    0 => [
        'phonenumber' => '9876543210',
    ],
];
```
Because of that, on `line 269` `$coll[1]` is treated as `null` and this is the line where those null values are being set.
So, resetting `$this->_identifierMap` of base element children each time the new to-many relation is added to base element solves this problem, because new elements are not getting previous element indexes. It may not be the best solution, but it works. I am not deeply familiar with Doctrine internals.
Also, it may not be any easier to understand the bug after my explanation, but I tried my best.

2. I have run the benchmark, didn't notice performance difference between current and modified version.

2021-11-15 21:17 UTC, LinasRam commented
Also, while trying to explain this bug right now, I noticed another problem. If you changed the order of article rows in my test case (order by ids: 1, 2, 1, 2), results would be interesting, too.

2021-11-15 21:23 UTC, greg0ire commented
Thanks for your explanation! I can't say it helps me because I too am not very familiar with that part of the code, but I will try to get the right people to review this.

2021-11-16 08:31 UTC, beberlei commented
Does ObjectHydrator have similar code to handle this already? I find it strange this never came up before.

I am confused why its nested, since you dont fetch the object but properties. Can you turn this into a real DQL query as per your comment? I am wondering if the problem is just a wong ResultSetMapping

2021-11-16 09:28 UTC, LinasRam commented
Yeah, query didn't correspond to what I was trying to accomplish. I updated it, I want nested results.

2021-12-13 12:36 UTC, LinasRam commented
Is anybody looking at this issue? I don't want it to be forgotten.

2024-12-04 03:15 UTC, closed without merging