Update IdentifierFlattener.php
doctrine/doctrine2 pull request #9793
Opened 2022-05-26 07:46 UTC by olegsuvorkov

Hello, I would like to make a small change.
The need arose when using \Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator in "symfony/doctrine-bridge" composite foreign keys
I'm sure these changes will not hurt performance
and allow other objects to be used as identifiers

2022-05-26 13:59 UTC, derrabus requested changes
Please describe the issue that you'd like to solve and add a test that covers your change.

2022-05-27 09:10 UTC, beberlei commented
I don't understand why a UUID is stored in the field instead of the associated entity when the ID is an association. That is the wrong result. I believe you are doing something wrong with your code and its not a Doctrine issue.

2022-05-27 10:03 UTC, olegsuvorkov commented
Thanks for the comments.
I am sure that in the object in the corresponding field of my code. an instance of the class specified in "targetEntity" is stored.
But "targetEntity" uses an instance of [\Symfony\Component\Uid\Uuid](https://github.com/symfony/uid/blob/5d1bba611fcd5d7ccc6435fd4ea8580f9ed75406/Uuid.php#L19) as an identifier.
And since the flattenIdentifier method is called recursively on the line
[\Ori\Eav\Utility\IdentifierFlattener:67](https://github.com/doctrine/orm/blob/48e4e333c7bf4757e9a4e19416d1a3e833ea28b0/lib/Doctrine/ORM/Utility/IdentifierFlattener.php#L67), on the next iteration, a ReflectionException occurs at the line 
[Doctrine/ORM/Mapping/ClassMetadataInfo:839](https://github.com/doctrine/orm/blob/48e4e333c7bf4757e9a4e19416d1a3e833ea28b0/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L839).
I will definitely write tests on this issue.

2022-05-27 10:11 UTC, olegsuvorkov commented
Details can be found here
[Storing UUIDs in Databases](https://symfony.com/doc/current/components/uid.html#storing-uuids-in-databases)

2022-07-21 08:30 UTC, louisezetterlund commented
Hi!
This PR solves issue #9335, which I'm also experiencing. The issue also contains a link to a repo with a simplified case where this bug exists. Do you want me to convert it to a test, so we can merge this PR? @derrabus @beberlei

2022-07-21 08:40 UTC, derrabus commented
Yes, the PR needs a test that proves the bug exists and makes sure it won't be introduced again by a future change.

2022-07-21 12:34 UTC, louisezetterlund commented
I've added a test in this commit https://github.com/rdey/orm/commit/58368e910589f58076197129d00d0d86bf3f5703.
Do you want me to create a new PR or can you add it to this PR? @derrabus

2022-07-21 15:54 UTC, derrabus commented
Please open a new PR that contains your test and the changes from this PR.

2022-07-24 13:21 UTC, merged